### ISSUE TITLE
Wizard Fixups and additions

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#272] opened 2016-02-21 15:35 UTC
Grouping wizard fixups - will maybe open separate issues if it proves necessary.

By @saebel:
- [x] Wizard: Notes function does not appear to be working.  Syntax used is
  Note "Text for the note" (Utumno: reported fixed: http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/page-5#entry25162918)
- [x] Wizard: Weird issues with displayed images.  When selecting an option, sometimes the image size would expand from the default 210 x 210 to 230 x 230, even though it was unnecessary for it to do so.  It stays at the zoomed ratio while toggling between selections, but returns to normal when continuing forward or back.  Blown up images look blurry and unprofessional.  My recommendation would be to have it set up so that an image never zooms larger than it's actual size.  That would solve the problem nicely, and graphic designers everywhere will thank you. (Utumno:related to the description text changing size ?)
- [x] Another issue with images from same post:
  
  > In a situation where there is a pop up with three options listed, if you click the option, the graphic to the right changes along with the description as expected, with the clicked on option highlighted.
  > However, let's say you have selected the second option on the list, and then click in the empty space below the third option.  The image and description switch to that associated with the third option, but the second option remains highlighted.
- [x] Also couple requests by @saebel from here: http://forums.bethsoft.com/topic/1589330-wrye-bash-thread-107/#entry24938868  (Utumno: not needed - see discussion below and: http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/page-5#entry25162918)
  
  > Wizard - GetFileExists
  > Boolean, looks for any file starting at the Oblivion.exe game directory, following path to target file.
  > Examples:
  > GetFileExists "Oblivion.exe"
  > GetFileExists "Data/Ini/SomeMod.ini"
  > 
  > or if that's too challenging, or perhaps in addition to:
  > 
  > Wizard - GetOBSEpluginExists
  > Boolean, Checks the OBSE/Plugins directory for an existing .dll
  > Examples:
  > GetOBSEpluginExists "sdr"
  > GetOBSEpluginExists "emc2"
- [x] docs edit for DataFileExists : http://forums.bethsoft.com/topic/1589330-wrye-bash-thread-107/page-6#entry25077056
- [x] On installing an ini tweak - refresh glitches: http://forums.bethsoft.com/topic/1599816-wrye-bash-thread-108/page-3#entry25123418:
  
  > The first is that it didn't refresh the SDR installer package after applying the .ini tweak, which would have displayed the correctly tweaked sdr.ini as a mismatched file. That initially gave me the impression that it hadn't been tweaked, so I ended up going into the Ini Tweaks tab to verify. Once I saw it had, I manually refreshed the installer package and the mismatched file showed up.
  > 
  > The other thing it said it didn't do was apply the OblivionReloaded.ini tweak. That's to be expected, because it's not part of the installer package. However, the OblivionReloaded.ini file had already been tweaked, and the tweaks that SDR's installer package were to apply had already been applied - meaning that the tweaks matched the current Oblivion Reloaded.ini file settings.
  > Bells and whistles request: If the .ini tweaks for a given file match the existing settings, there should be no need to have a pop up to tell me to apply the tweaks when it is isn't actually necessary. But you can save that for 308 if you like. 
- [x] ~~Another one - no images wizard displays error: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=167386~~ - confirmed by Beermotor on Discord to no longer be a problem
- [x] And ( http://forums.bethsoft.com/topic/1602198-wrye-bash-thread-109/page-5#entry25163236 ):
  
  >  If the .ini file doesn't already exist, it applies the tweaks during installation without a pop up.  If you reapply the wizard, the .ini tweaks are not automatically applied because it sees there is already an .ini file there.  If that's the desired behavior, then it is correct.  My recollection though was that if the .ini file was part of the original installation package, it should always have the tweaks applied silently when done by the autowizard.

**Comment by Utumno** [comment] 2016-03-18 23:24
@saebel: I 'd  rather not go into wizards now but here is the issue (will be split up later if needed but let's keep it simple for now) - the ideal solution you refer to at your post at http://forums.bethsoft.com/topic/1589330-wrye-bash-thread-107/page-6#entry25075362 is those GetFileExists, GetOBSEpluginExists right ?

**Comment by saebel** [comment] 2016-03-18 23:32
Yes.  Those two things would be awesome.  If you want I can take a look at
the parser over the weekend.  No promises I will figure anything out
though.  I have never dealt with Python before.

**Comment by Utumno** [comment] 2016-03-19 02:17
Haha - be my guest :) I am neck deep to BAIN and recently some work on the installer (#235) - not to mention the skyrim patchers so yeah - but as soon as I get a chance I will have a look too

**Comment by saebel** [comment] 2016-03-19 02:25
I think I may have figured it out.   Posted it on the forum thread:

http://forums.bethsoft.com/topic/1589330-wrye-bash-thread-107/?p=25075954

**Comment by Utumno** [comment] 2016-11-19 11:43
@saebel: I would appreciate verification for the checked items so I can close this and go on with design in https://github.com/wrye-bash/wrye-bash/issues/318

**Comment by Utumno** [comment] 2017-07-09 16:01
Another one - no images wizard displays error: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=167386

**Comment by Utumno** [comment] 2017-12-30 22:37
@BeermotorWB could you test that the issues reported here are closed ? I think high time we shut down this one

**Comment by BeermotorWB** [comment] 2018-01-12 16:42
@Utumno seeing this late, but I will write a test wizard that hits all the issues and report.

**Comment by Infernio** [comment] 2019-10-11 21:08
Forgot to mention this a few days ago - the last entry in here exposed an FOMOD bug (fixed in ca006b1fb1cf3cc7f4b4bdca8eb3d58550b7dd48), but after that was fixed, Beermotor and I were unable to reproduce it. When installing with an existing INI, a tweak is successfully created. If the INI is missing, WB pops up a warning about the missing INI and offers to create it from the game's default INI. Since none of the mentioned problems are reproducible anymore, I'm closing this - feel free to reopen if one of these does resurface.

**Closed by Infernio** 2019-10-11 21:08 UTC
Labels: enhancement
