### ISSUE TITLE
Windows Insider Build 16288 - Does not open from Mod Organizer 2 Skyrim Special Edition

### ISSUE THREAD

**Issue by TucoPacifico1980** [wrye-bash/wrye-bash#387] opened 2017-09-16 14:14 UTC
### Info on your installation

Windows 10 Insider 16288

Wrye Bash 307.beta1, WBSA https://www.nexusmods.com/skyrimspecialedition/mods/6837/? Beta 1 - Installer

 - bashbugdump.log:
[spoiler]
testing UAC
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
  File "bash\bash.pyo", line 370, in main
  File "bash\env.pyo", line 563, in testUAC
  File "bash\bolt.pyo", line 897, in rmtree
  File "shutil.pyo", line 256, in rmtree
  File "shutil.pyo", line 254, in rmtree
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'c:\\users\\0wner\\appdata\\local\\temp\\WryeBash_e2zbgn'
[/spoiler]

### Info on the bug

After isntalling Windows Insider preview 16288, when running Wrye Bash from Mod Organizer 2 I get this:
https://imgur.com/a/C2S0k

Wrye Bash does not start when I click one of the options. The same problem was reported by users here:
http://forum.step-project.com/topic/12328-wryes-bash-wont-run-from-inside-mo2/

**Comment by TucoPacifico1980** [comment] 2017-09-16 14:43
It was working fine until I installed the Insider build of Windows.

**Comment by TucoPacifico1980** [comment] 2017-09-16 15:07
Informed Microsoft about the problem:
https://aka.ms/Ov5soz

**Comment by D4id4los** [comment] 2017-09-16 15:07
None of the Wrye Bash team use MO or MO2 so we can not support issues specific to those programs. Does the same error appear when you start Wrye Bash on it's own, without MO being involved?

**Comment by TucoPacifico1980** [comment] 2017-09-16 15:07
Can someone check if you can start Wrye Bash from Mod Organizer 2 with Win10 16288?

**Comment by TucoPacifico1980** [comment] 2017-09-16 15:20
@D4id4los no it works fine on it's own. And it was working fine from MO2 with Windows standard installation. It does not work started from MO2 with Insider build 16288.

**Comment by D4id4los** [comment] 2017-09-16 15:28
In that case you will have to report this to the MO2 team. I do not have any personal experience with it, but I have read reports of it not working well on the Win 10 Insider Ring so it will probably need an update on their side.

**Comment by TucoPacifico1980** [comment] 2017-09-16 15:40
Allright, will post there, thanks for looking into it.

**Comment by Utumno** [comment] 2017-09-16 16:21
Thanks @D4id4los - btw @TucoPacifico1980 please always use latest to test - links in front page here - please also always post me the bugdump. This traceback may have been fixed in latest (see front page here)

**Comment by Helidoc65** [comment] 2017-09-16 16:31
Good Morning @Utumno not to hijack a closed issue but incase your curious the thread referenced by @TucoPacifico1980 [http://forum.step-project.com/topic/12553-wrye-bash-with-mo2-failure-to-launch-win-10-insiders/](url) was posted by me and I posted both dump files from WB and MO2 in that post, also to mention I was using test build 307.201709152046 which was the latest at the time of the report. I do believe it to be an MO2 issue but at first run on stand alone for Skyrim SE (outside of MO2 on its own)I did get a popup asking to overwrite which I allowed and then WB ran fine.

**Comment by TucoPacifico1980** [comment] 2017-09-16 17:28
@Utumno can you point me to the thread with the latest? I will bookmark it. Thanks.

**Comment by TucoPacifico1980** [comment] 2017-09-16 17:47
IT WORKED! Using utumno-wip branch python version I can open it in Windows Insider 16288 from MO2. So it is not an MO2 issue in the end?

https://imgur.com/a/NB1Vp

**Comment by Helidoc65** [comment] 2017-09-16 18:19
@TucoPacifico1980 so python version is working and standalone is not. Interesting...

**Comment by TucoPacifico1980** [comment] 2017-09-16 18:31
@Helidoc65 At least it starts! But it pulls the deactivated and merged plugins to Overwrite folder. After I delete them, gone for good. Auto Ghosting is disabled. I am trying again

**Comment by GrantSP** [comment] 2017-09-16 22:41
I am still on Windows 10 version 1607 and using MO2 and the same WB version as mentioned here everything works perfectly fine.
Clearly this is another issue caused by the Windows update.

**Comment by TucoPacifico1980** [comment] 2017-09-16 23:16
@GrantSP of course it is :). And we are here to fix it. Just remodding my game with MO2 and the aforementioned python version of Wrye Bash. I joined windows Insider program to protect myself and the community from future sudden incompatibilities.

**Comment by GrantSP** [comment] 2017-09-16 23:19
What I meant was, like the other "Creator" updates issues, MS will likely come to the party and fix it, not MO2.
However if there are still coders wanting to try and fix it from this end, go for it.

**Comment by TucoPacifico1980** [comment] 2017-09-17 01:19
@GrantSP just redid my whole modding guide with MO and help of the python version of WB 🗡 
Back in game 💃 
https://imgur.com/a/Cryrw

**Closed** 2017-09-20 16:59 UTC
Labels: R-wont-fix
