### ISSUE TITLE
Bashed Patch with Nehrim still trying to add Oblivion.esm

### ISSUE THREAD

**Issue by Forlini91** [wrye-bash/wrye-bash#214] opened 2015-06-10 09:56 UTC
Could you stop the bashing patch from putting "Oblivion.esm" as master everywhere, even if using Nehrim or another total conversion/overhaul (where Oblivion.esm doesn't exists)?
When I build the bashed patch for Nehrim and use some Tweak Settings or Tweak Assorted, it place "Oblivion.esm" (spawned from nowhere) as first master mod, followed by Nehrim.esm (and all other master files).

The problem is: I can't simply create a dummy "Oblivion.esm" and place it there, because there are mods which check for "Oblivion.esm" to determinate if we're playing Oblivion or Nehrim, and these mods go insane if they try to use some content from Oblivion.esm (which is obviously missing from a dummy Oblivion.esm).
I can't even delete Oblivion.esm, because the Bashed Patch depends on it for the game settings.

So everytime I need to use Tes4Gecko to put Nehrim.esm back on top in the masterlist, then rename Oblivion.esm to another master. I created an empty "Dummy.esm" for this.
This screenshot show the Bashed Patch settings which are assigned randomly to the Nehrim.esm (00x) or Dummy.esm (01x) masters. (some of them even to MigMagipuke.esp (06x)...)
![screen](https://cloud.githubusercontent.com/assets/12827228/8079742/fb2fe5d8-0f66-11e5-9d82-cf74023f23f6.jpg)

 If the Bashed Patch stop using Oblivion.esm as absolute requirement and use whatever esm it find instead, it would be great.

**Comment by Utumno** [comment] 2015-06-11 04:59
PBash or CBash ?

**Comment by Forlini91** [comment] 2015-06-11 06:16
PBash

**Comment by jfpelland** [comment] 2015-07-28 20:38
@Forlini91 Can you test this branch: https://github.com/wrye-bash/wrye-bash/tree/trira-issue_214

Should be fixed now.

**Comment by Forlini91** [comment] 2015-07-28 21:53
No luck. The Oblivion.esm is still placed in it's master list, but it's odd: I created a dummy Oblivion.esm and used TES4Edit to open the bashed patch and... no Oblivion.esm record is taken/altered.
Something I noticed: in the previous version, the Oblivion.esm was placed in the first position in the masterlist (above Nehrim.esm). Now it's placed as very last esm.

**Comment by jfpelland** [comment] 2015-07-29 14:56
Hmm. I can't reproduce that on my end. Can you post/upload your load order and patch config somewhere?

**Comment by Forlini91** [comment] 2015-07-29 20:10
I found it!
Tweak Assorted -> Magic: Script Effect Silencer.
When enabled, Oblivion.esm appear. When disabled it disappear!
I guess it's because all magic effects have default/null values and WB needs to read Oblivion.esm to get the SEFF data.
I'm afraid this option depends on the esm, but it could be changed so it can use any esm, not just "Oblivion.esm".
An idea: when you select the option, a drop down list will allow you to select the esm here to get the SEFF data (instead of search blindly for it).

I don't know if another option could place Oblivion.esm in the list, but I think you could check them faster than me (I would need to build too many bashed patch to check all them!).



As for the other bug (Bashed Patch take a setting from another esp instead of the main esm), just create a little esp which change a game setting like "fEssentialDeathTime" or "iArrowInventoryChance", then override that same setting in the Bashed Patch with the relative Tweak Settings option. When the patch is complete, just right click on it and select "Details".
That setting should appear with the mod index of the little esp. (same if you check in Tes4Edit).

My Bashed Patch config: https://drive.google.com/file/d/0B5L6ymIjm7muY3N1c1FhbWlVSVk/view?usp=sharing
Here's a screen of what's happening on my end: fEssentialDeathTime and fPlayerDeathReloadTime (and few other settings) are changed by both my esp NehrimMod (which require all above Nehrim* esps/esms) and the Bashed Patch tweaks. As you can see in the bottom right corner (the bashed patch details), those settings have index 03, which in the master list is NehrimMod.esp.
![image](https://cloud.githubusercontent.com/assets/12827228/8968523/0ff36fa0-363e-11e5-8d3c-f1c6524de34f.png)

**Comment by jfpelland** [comment] 2015-08-03 00:44
Script effect silencer doesn't actually depend on any particular master file. The problem was that Bash creates null forms to replace some references and the null forms had `Oblivion.esm` hard-coded as their parent mod. I've set it to use whatever bosh.modInfos has as the game's master file. Try out my branch again. Should work now.

There's a similar issue with the `Tweak Actors -> As Intended:Boars` patcher. This one's a bit different though. It adds a spell to boars. That spell isn't present in `Nehrim.esm`, so I can't just change the parent mod to Nehrim. One of two things can be done:
1. Create the spell as a new record in the Bashed Patch and add it to boars.
2. Skip the patcher entirely. Ideally, don't even show it in the patcher dialog.
I'm leaning towards the latter. I assume SureAI team explicitly left out the record, so "As Intended" might be a bit of reach for Nehrim. @Utumno, thoughts? 

There's several other patchers (all on the CBash side, it seems) that have `Oblivion.esm` as a hard-coded parent for some forms. Gonna change all of those too if it's safe to do so.

Haven't looked at the GMST/form id issue yet. Probably better to gave that one its own issue as it sounds like something completely separate.

**Comment by Utumno** [comment] 2015-08-03 14:47
Second I' d say yes. I leave this up to you - feel free to open an issue for the GMST if it proves such. Will review before merge, let me know when ready - just keep in mind that before merges you need to always rebase on dev to have a quasi linear history.

On my end I will try to merge the last (and surprisingly tricky) bits of refactoring on dev over the next few days and smooth out the rest for branching release off.

Thanks :)

**Comment by Forlini91** [comment] 2015-08-04 10:18
Ok, now it works as expected. Thanks!
I'll open another bug report for the GMST/Form ID issue.

**Comment by Utumno** [comment] 2015-08-09 10:08
@jfpelland do you think this could go to 306 ?

**Comment by jfpelland** [comment] 2015-08-09 19:26
I won't have time to finish it up properly before then, so no. Will be done for 307 though.

**Comment by Utumno** [comment] 2016-09-07 20:25
Hit the same issue from another path - was optimizing out GPath calls and run across  `GPath(bush.game.masterFiles[0])` - see https://github.com/wrye-bash/wrye-bash/commit/8221094ba84693b0e7503fcebbe5a2b7da0cf910

Reverted my changes as I do not grok that code - any chance you finalize this for the 307 beta ?

**Closed** 2020-06-14 09:49 UTC
Labels: A-patchers, C-bug, G-nehrim

**Comment by Infernio** [comment] 2020-06-14 09:51
Should be fixed as of 1bdcd9df2cd9cee164645b74beec1f513aa24129, but be aware that we no longer support manually installing Nehrim. It *should* still work, but the Steam version is recommended.
