### ISSUE TITLE
Keyword data from winning records is not copied

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#305] opened 2016-05-14 05:25 UTC
This may be due to a larger problem with keywords not copying at all, but this one in particular is noted because there's a merged mod in between the winning record and the Bashed Patch. The keyword data should be copied over because the merge mod is not supposed to blank that out.

Either that or you can take this as the ticket to request a proper keyword patcher :p

https://i.imgur.com/b2o8nqn.jpg

To reproduce, use the attached files. Mark WiningKeywordModToMerge.esp as mergeable. Set the load order to have WinningRecordKeyword.esp load before it. Then process the Bashed Patch and let it merge the second WITHOUT merging the first. The keyword data will not be copied but it should be due to winning record logic from previous games that did work.

[WinningKeywordRecord.zip](https://github.com/wrye-bash/wrye-bash/files/264372/WinningKeywordRecord.zip)

**Comment by Arthmoor** [comment] 2016-10-02 23:14
As of 307.201610020028 this issue is still present.

**Comment by Infernio** [comment] 2019-09-15 12:14
May be superseded by #461, if that would be an acceptable solution.

**Comment by Infernio** [comment] 2019-11-10 22:14
Same situation as in #306. Merging the plugin completely overwrites the previous one. Adding the `Keywords` tag (see linked issue above) is the correct way to resolve this:

![Keywords-Merged](https://user-images.githubusercontent.com/2845240/68551686-c6875580-040f-11ea-96c4-634b8ea75a02.png)

Closing as duplicate of #306 / superseded by #461.

**Closed by Infernio** 2019-11-10 22:14 UTC
Labels: R-duplicate, G-skyrim, A-patchers

**Comment by BLACKBERREST3** [comment] 2021-12-21 09:51
Issue still present in 2021/2022? [picture](https://i.imgur.com/wZrhMIN.png)

**Comment by Infernio** [comment] 2021-12-21 09:54
This wasn't an issue, it was a feature request (to add a Keywords patcher). Which now exists, so all you have to do is tag the plugins you want keywords imported from with `Keywords`.

**Comment by BLACKBERREST3** [comment] 2021-12-21 09:56
oh! I will look up how to do that. thanks.
