### ISSUE TITLE
Names patcher does not override correctly.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#301] opened 2016-05-14 04:47 UTC
The names patcher for Skyrim is not correctly processing two mods in a row that are using the Names tag. The second mod using the tag gets ignored even when the first is a vanilla record.

https://i.imgur.com/RF92Hgh.jpg

Attached should be 2 files which can replicate this.
[NamesPatcherOverride.zip](https://github.com/wrye-bash/wrye-bash/files/264362/NamesPatcherOverride.zip)

**Comment by Utumno** [comment] 2016-05-14 10:29
Haha Saturday morning spree - thanks :)

Now don't hold your breath but since it's Saturday here too - is this what I need to select to build the patch ?
![build patch](https://cloud.githubusercontent.com/assets/1365079/15267925/77cd4f54-19cf-11e6-9d9d-6f38f3788aed.jpg)

**Comment by Arthmoor** [comment] 2016-05-14 21:48
Well it appears that somewhere between when I last tested this and last night when I made the mini files to replicate the conditions, the issue was fixed. I'm no longer seeing this one crop up in my full load order.

So I guess we can close this :P

**Comment by Utumno** [comment] 2016-05-14 22:05
Ninjaed trying to merge the code 4- see my comments above - I run across a bug there - can you answer me the questions there ?

**Comment by Arthmoor** [comment] 2016-05-14 22:37
I'm probably not the one to ask about writing up a high level overview of esp structure. The xEdit crew would be the better choice since they know more about the deeper details and could probably summarize it better.

MGEF records are for magic effects. I'm almost positive that whatever you're looking at for those is only relevant to Oblivion, and I'm afraid I don't remember why after all this time.

**Comment by Arthmoor** [comment] 2016-05-14 22:43
Actually, wouldn't this work? http://www.uesp.net/wiki/Tes5Mod:Mod_File_Format

**Comment by Utumno** [comment] 2016-05-15 02:09
> Actually, wouldn't this work? http://www.uesp.net/wiki/Tes5Mod:Mod_File_Format

Enough for now thanks. And enough for today - spent some hours trying to track the memory leak we have in the patcher - #113 - goose chase, perilous waters

When you get some time please have a look at https://github.com/wrye-bash/wrye-bash/issues/167 - are any of the bugs there the same as yours ? I think the first one there is this one here.

**Comment by Arthmoor** [comment] 2016-05-15 02:58
Top one in #167 looks like what happens when you let Bash use Skyrim.esm in the names patcher. I never really understood why that's the only patcher with that exception, none of the others list the game's master file.

Second image in that issue is a winning record problem. The price data should get pulled over to the end assuming the USKP in his image isn't also changing the price, because then the "Gold Worth Something" mod would need the Stats tag to counter the USKP's Stats tag.

**Comment by Utumno** [comment] 2016-05-15 13:51
> Top one in #167 looks like what happens when you let Bash use Skyrim.esm in the names patcher. I never really understood why that's the only patcher with that exception, none of the others list the game's master file.

Hmmm - as you can see in my pics above I made my patch including Skyrim.esm. Still don't understand - isn't the first picture exactly same as this issue here ? Name is not carried to  the BP

Should I remove Skyrim.esm from the Name patcher masters ? There may be a code reason but is there a use for it being there ?

> Second image in that issue is a winning record problem. 

Is it similar to any you have reported ? What about the third pic ?

**Comment by Arthmoor** [comment] 2016-05-15 20:34
I don't think Skyrim.esm used to be part of the names patcher back in the day, but that's been a long time now. I don't know why it would be included there but nowhere else. So if it's not needed by some code I'd say take it out of the list.

That second pic is probably similar to #306 

Third pic I've not seen so I'm not sure what's going on there. I don't know what Bash is supposed to do when the spawn chance is different.

**Comment by Utumno** [comment] 2016-10-29 11:39
@Arthmoor: can I close this now ?

**Comment by Arthmoor** [comment] 2016-10-29 18:13
No. This issue still exists. I've still got the name being pulled from Dragonborn.esm into the bashed patch even though USLEEP is tagged for names and removed it. The removed name should be what's taken because of that.

**Comment by Utumno** [comment] 2016-10-29 18:33
Hmm - can I have a minimal reproducer - btw you said befor:

> So I guess we can close this :P

Is this the same issue or another ?

**Comment by Sharlikran** [comment] 2016-10-29 19:08
Could this be combined with #328.  Or have #328 combined with this issue?  Both issues address the names patcher.

Can Wrye Bash compare strings like that Utumno?  The DLC has strings pointers.  Plugins have either an actual string or simply a small pointer to the string in the localization file.  This applies to Skyrim, Fallout 4, and Skyrim SE.  While Oblivion has the string embedded into the plugin.  Does the code support that?  I believe I heard it does but I have always wanted definite confirmation that you see an actual string from the strings file.

Is Wrye actually displaying "Tamriel" during the patching process and not "^&$" instead because it's comparing the pointer and not the actual string?  Currently without BA2 support and without lz4 support to access the new BSA format for Skyrim SE, the only way for you to test this is with the original Skyrim.  This issue simply can't be tested with Fallout 4 or Skyrim SE for now.  Do you have Skyrim Utumno?

Please look at this also.  If the FULL record for USLEEP (or any mod) has an empty string or the record is gone entirely then the FULL record should not be written to the Bash Patch.  It's pointless to save a FULL record with an empty string.

Right now the Names patcher is simply broken.  Once you have time to try it Utumno and verify you see actual strings being compared and not integers I would be happy to test it also with Skyrim.  Just remember that the winning record with the same bash tag wins.  If another mod loaded after USLEEP (or any mod), also with the Names tag, has the Strings pointer to "Tamriel" then the FULL record has to be preserved.  If there are 1 or more mods loaded after USLEEP (or any mod), none with the Names Bash Tag, then the change from USLEEP (either a string or a string deletion) should win.

**Comment by Utumno** [comment] 2016-10-29 19:14
There are many separate issues with the name patcher no use combining them - on the contrary - one thing at a time.

To attempt to fix however I need minimal reproducers. I have skyrim

Btw - I have rebased your fallout3 branch on dev again and used some of your skyrim se branch leaving out the saves stuff as we need much work for that turns out (l4z...) - I would appreciate if you tested utumno-wip is working ok for skyrim se

**Comment by Sharlikran** [comment] 2016-10-29 19:24
Lets talk on the oblivion forum for a bit Utumno about collaborating on the project again.  If we can come to some kind of mutual agreement lets do that.  Otherwise rebasing is kind of pointless.  I'll explain more there.

In regards to the plugins you need sure, I'll make a few for you to test with.  However, I'm going to push the science to its full extent.  Because I want to focus on the one unfortunate side effect of all the patchers.  The side effect is that when the Names bash tag is applied is is not exclusive to one record type.  Therefore an armor mod that adds a chest to a cell will overwrite the cell change from USLEEP.  That should be expected and is not a bug.  My test plugins won't require USLEEP of course.

**Comment by Infernio** [comment] 2019-11-10 21:44
I can't reproduce this - not with the linked plugins or with the two that were originally used for the screenshot (USLEEP and ASLAL).

**Comment by Infernio** [comment] 2019-12-18 00:02
Please reopen if this can be reproduced again.

**Closed by Infernio** 2019-12-18 00:02 UTC
Labels: G-skyrim, R-works-for-me, A-patchers
