### ISSUE TITLE
Ghosted Plugins Sorted after the Bash Patch

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#164] opened 2014-10-04 00:27 UTC
Revelant posts: WrinklyNinja felt this could be a [possible bug here](https://forums.bethsoft.com/topic/1505167-relz-wrye-bash-thread-37/?p=23750393).  Original post with [steps to reproduce](http://forums.nexusmods.com/index.php?/topic/478460-wrye-bash/?p=17861429).

stickman1024's detailed steps to reproduce:

1. I launched BOSS by clicking the shortcut on the toolbar of Wrye Bash
2. In Bash ghosted plugins are sorted in alphabetically below active plugins.
 
I repeated test case again, took more detailed notes, as in the forum post:
 
Background:
 
1. Uninstalled BOSS and deleted directory C:\BOSS
2. Uninstalled LOOT
3. Deleted %LOCALAPPDATA%\Skyrim\DLCList.txt, plugins.txt, loadorder.txt
4. Downloaded and installed BOSS 2.3.0 from github
5. Uninstalled all versions of Python, deleted directory C:\Python27
6. Uninstalled all previous versions of Wrye Bash via uninstaller
7. Verified all /Mopy directory are deleted
8. Verified BashSettings.dat, Converters.dat, Installers.dat, Table.dat are deleted
9. Downloaded Wrye.Bash.305.-.Installer.exe
10. Installed Wrye Bash 305 standalone
11. Plugins ghosted by previous Bash install are left as-is, all non-ghosted plugins are activated via Skyrim Launcher in Steam

Test (numbers are actions, sub-points are observations):

1. Ran Wrye Bash 305:
  * auto-ghosting was disabled default on startup
  * active plugins sorted alphabetically (as sorted by Skyrim Launcher)
  * ghosted plugins sorted alphabetically below active plugins
  * when right click on BOSS shortcut in Bash, "BOSS disable lock load order" is checked, "Launch BOSS GUI" is unchecked.
   
2. Lauched BOSS 2.3.0 from shortcut on Wrye Bash toolbar:
  * masterlist updated
  * BOSS completed sorting
  * BOSS log displayed in browser
  * loadorder.txt changed
   
3. Refocused on Wrye Bash window 
  * no change in Mods tab plugin order
  * plugins still display as same order from 1b and 1c
  * did not reflect changes in loadorder.txt
   
4. Quit Wrye Bash then ran Wrye Bash again immediately:
  * active (non-ghosted) plugins reflected order in loadorder.txt
  * ghosted plugins sorted alphabetically below active plugins - did not match loadorder.txt

**Comment by Sharlikran** [comment] 2015-02-07 18:22
I was testing the dev branch to provide Utumno with a tracelog from the dev branch.  Two things happened.  All my inactive plugins were automatically ghosted when I don't have the enabled and they were all sorted after the bash patch.

@wrye-bash/active I remember at one point Utumno had commented on a fix from wrinklyninja-liblo-6-support.  IIRC there was an error.  Was that resolved in commit 89d3fb581545d898d22be65079d5876e6339a8f5?

**Comment by Utumno** [comment] 2015-06-13 10:00
@Sharlikran: can you please try and reproduce this on my latest HEAD: https://github.com/wrye-bash/wrye-bash/commit/ee68ccc1a79621faf4b89e55c9ec4330e59c6f48

**Comment by Utumno** [comment] 2015-07-13 15:38
Can't find BOSS - will close this as works for me except if someone manges to reproduce at my current branch

**Closed** 2015-07-17 13:49 UTC
Labels: bug

**Comment by Utumno** [comment] 2015-07-17 14:14
Closing this as I can't reproduce it - see linked commits for the possible fixes - ghosting was a can of worms both in libloadorder and Bash
