### ISSUE TITLE
Better warning for leveled list overflow

### ISSUE THREAD

**Issue by MisterB1969** [wrye-bash/wrye-bash#327] opened 2016-10-01 19:06 UTC
After creating a bashed patch for Skyrim. I get the following error:
ubyte format requires 0 <= number <= 255
<bash.brec.ModWriter instance at 0x0E1CDD00> LLCT B (264,)
ubyte format requires 0 <= number <= 255
<bash.brec.ModWriter instance at 0x0E1CDFA8> LLCT B (258,)
ubyte format requires 0 <= number <= 255
<bash.brec.ModWriter instance at 0x0E1CDD00> LLCT B (258,)

**Comment by Utumno** [comment] 2016-10-01 20:10
Please see https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug on reporting a bug

Also I need all the information on the patch - try to reduce patch settings and loaded mods to the minimal set that reproduces the bug

**Comment by Arthmoor** [comment] 2016-10-02 22:20
You're trying to merge too many records into leveled lists. Skyrim limits how many entries each list can hold to 255 records. Your error indicates at least one list wanting 264, and the other two wanting 258 each.

**Comment by Utumno** [comment] 2016-10-02 22:33
Thanks @Arthmoor - so is this invalid ?

**Comment by MisterB1969** [comment] 2016-10-02 22:55
Thanks Arthmoor, I thought that might be it. Even though it says my active mods were below 250.

**Comment by Arthmoor** [comment] 2016-10-02 23:13
It doesn't have anything to do with how many active mods you have. It's the leveled lists themselves that ALSO can't hold past 255 records. The 255 limit is inherent to how the entire mod system works in Bethesda's games.

@Utumno Yes, unless you intend to cook up some way to automatically have Bash split an overloaded list into two parts in the patch.

**Comment by Utumno** [comment] 2016-10-03 06:52
Marked as won't fix as it would be nice to have a warning some place - but for now I have no reproducer - heck I don't even know where this error is shown

**Comment by Sharlikran** [comment] 2016-11-06 01:48
Lojack mentioned this in the forums before and thought splitting them might be an idea but could lead to issues.  Probably more trouble then it's worth for now.  What people need to do is stop merging mods with Merge Plugins or scripts that allow the leveled list to go beyond 255.

**Comment by Infernio** [comment] 2019-10-28 17:53
Reopening because it came up on Discord and I made a commit that will fix it (for now, we should offer an option to auto-split these eventually): aca6b15d32b3cde7d0bc7f8f3d6bd89a266e4ec3

**Closed** 2019-12-02 00:44 UTC
Labels: enhancement, patcher
