### ISSUE TITLE
[FO4] BAIN not installing MCM files

### ISSUE THREAD

**Issue by nephatrine** [wrye-bash/wrye-bash#397] opened 2017-11-14 14:55 UTC
MCM configuration in FO4 has mods use an MCM top-level folder in the FO4 Data directory. Looks like it mcm needs added to the dataDirsPlus list in Mopy/bash/game/fallout4/__init__.py . Should be pretty trivial to do.

**Comment by BeermotorWB** [comment] 2017-11-14 19:21
Thanks @nephatrine, and yes that should be the right place if you want to edit that file to include that path for the time being.

Is it correct that MCM's for FO4 always install to `Fallout4\Data\MCM\`?

**Comment by nephatrine** [comment] 2017-11-15 02:29
Yes, the structure looks like this with everything in Data/MCM

Data/
└── MCM/
    ├── Config/
    │   ├── Mod1/
    │   │   ├── config.json         (Required) Menu Layout
    │   │   ├── lib.swf             (Optional) Image library
    │   │   ├── keybinds.json       (Optional) Keybind Definitions
    │   │   └── settings.ini        (Optional) Mod Setting Defaults
    │   ├── Mod2/
    │   │   └── ...
    │   └── Mod3/
    │       └── ...
    └─── Settings/
         ├── Mod1.ini               Mod Settings for Mod1
         ├── Mod2.ini               Mod Settings for Mod2
         └── Mod3.ini               Mod Settings for Mod3

**Comment by BeermotorWB** [comment] 2017-11-15 21:55
@nephatrine  excellent thank you that's perfect.

**Comment by BeermotorWB** [comment] 2017-11-15 21:56
List of MCM enabled FO4 mods [available here](https://www.nexusmods.com/fallout4/mods/21497/?).
I'll probably go through and snag a few for compatibility testing.

**Comment by BeermotorWB** [comment] 2017-11-16 23:15
@Utumno I can add this fairly quickly since it is a single-line edit. Do you want me to base it off of WIP or Dev?

**Comment by BeermotorWB** [comment] 2017-11-17 22:49
@nephatrine  The fix is in. 

@Utumno   Readme was updated, but Pycharm decided the Readme Template needed committing despite it being identical to the original. I'm going to switch to doing everything in Vim if this keeps up.

**Comment by Utumno** [comment] 2017-11-17 23:09
It's not identical it's the line endings diffs. Please use git Bash or the terminal in those cases - don't use PyCharm (or any third party tool) to interact with git, they are buggy, as shown by this last example and a billion others. Be sure to wrap your commit messages to 72 chars also. To get rid of the line endings see the workaround in the wiki on line endings. Always use git gui and commit in git gui this way you see what you commit. You can use git gui to amend this commit - hit amend, unstage the readme template, commit ( after wrapping the message) then issue the commands in the wiki to clean the line endings. I will look into curing this - however we should rename the readme template and this needs discussion

Thanks!

**Comment by Utumno** [comment] 2017-11-17 23:50
The wiki links:

https://github.com/wrye-bash/wrye-bash/wiki/[git]-Commit-guidelines

https://github.com/wrye-bash/wrye-bash/wiki/[git]-Issues-with-line-endings-preventing-checking,-merge,-etc#another-possible-solution

**Comment by BeermotorWB** [comment] 2017-11-18 12:19
Don't worry, I have decided to start using the Git Bash command line for *everything* from here on.
I did use it for 'git diff" (it didn't see a difference) and of course the final push so I could make sure it pushed into a branch.   

If you want to nuke that branch have me re-do it I will be glad to.

**Comment by Utumno** [comment] 2017-11-18 17:05
Oh I always have three windows open - git bash for rebase and other commands, git gui for committing amending and reviewing status of files and gitk for checking out, switching branches, diffing between commits. From my experience (and I got a lot, I even have a bronze batch in stackoverflow for git :P) that's the best workflow. Give it a whirl. In particular do _not_ use git Bash for everything - in particular commits and status you should always use git gui.

**Comment by Utumno** [comment] 2017-11-28 22:11
@BeermotorWB could you please redo the commit to remove the readme template and also in the tables put the actual folders we added and in parenthesis the mods they are for ?

Thanks!

**Comment by BeermotorWB** [comment] 2017-12-01 22:41
@Utumno Will do!
Re: commit messages - I'll just use Vim.  😁

**Comment by Utumno** [comment] 2017-12-02 14:02
>  Re: commit messages - I'll just use Vim. 😁

I use notepad++ with the margin set at 72 lines :P

**Comment by BeermotorWB** [comment] 2017-12-02 15:00
Just for future reference, to change your default commit editor to Notepad++ (assuming 64-bit version):
`git config core.editor "'C:\Program Files\Notepad++\notepad++.exe' -multiInst -notabbar -nosession -noPlugin`

**Comment by BeermotorWB** [comment] 2017-12-02 15:07
@Utumno Done - branched `beemotorwb-397-redo` off dev and pushed.  Should be ready for your perusal.

**Comment by BeermotorWB** [comment] 2017-12-04 16:15
@Utumno  I've tested this and confirmed the fix. This can be closed pending merge. 

The original (munged) `beermotor-307` branch can also be removed since it is just cluttering things up. I can take care of it if you want.

**Comment by Utumno** [comment] 2017-12-04 17:12
@BeermotorWB - yes please remove the other branch - will close this via the commit.

Thnaks!

**Comment by BeermotorWB** [comment] 2017-12-04 19:31
@Utumno  Done. 👍

**Comment by Utumno** [comment] 2017-12-05 10:40
Hmm - I see also a **tools** extra folder for all games except oblivion see fb61f8857fc7831bafbaee73137e62f36b5ab270 - should be added to the readme - could you do this @BeermotorWB  in an extra commit on this branch and let me squash them ?

**Comment by BeermotorWB** [comment] 2017-12-07 12:01
@Utumno  I will make it so.  👍

**Comment by BeermotorWB** [comment] 2017-12-09 17:10
@Utumno Updated and pushed to same branch. Unless you see any more edits this should close this one.

**Closed** 2017-12-23 13:30 UTC
Labels: bain, enhancement
