### ISSUE TITLE
[Skyrim SE] Plugins.txt should no longer contain official files at all.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#345] opened 2016-11-11 04:05 UTC
Ok. So. I know I know. This is controversial, but it needs to be addressed now.

Skyrim Special Edition no longer officially stores the 5 official data files in the plugins.txt file when using the internal mods menu. So I do not think it's prudent for Wrye Bash to continue doing so either.

Skyrim.esm
Update.esm
Dawnguard.esm
Hearthfires.esm
Dragonborn.esm

The game will load these 5 files regardless of what's specified, and it will load them in that order [Bethesda's timestamp bug not withstanding]. The game will ignore changes in the placement of these files in Bash (or NMM for that matter).

So Bash either needs to simply list these files and make them untouchable, or it needs to stop listing them at all. If other tools still need this stuff to be listed in the file, it ought to be safe to continue writing them, but the game will utterly ignore these 5 files being there, and they need to be locked to this specific order.

This lockin was already done for Fallout 4 for the same reasons.

In addition, Bash should no longer honor clicks to deactivate the DLCs since the game will refuse to comply with that anyway.

**Comment by Utumno** [comment] 2016-11-11 12:15
> So Bash either needs to simply list these files and make them untouchable, or it needs to stop listing them at all. If other tools still need this stuff to be listed in the file, it ought to be safe to continue writing them

Let's wait and see (to list or not to list)

>In addition, Bash should no longer honor clicks to deactivate the DLCs since the game will refuse to comply with that anyway.

That'd be easy

> and they need to be locked to this specific order.

That'd be harder

> [Bethesda's timestamp bug not withstanding]

I beg your pardon ?

**Comment by Sharlikran** [comment] 2016-11-11 13:47
> Skyrim Special Edition no longer officially stores the 5 official data files in the plugins.txt

I'll test this as I want to see what it does.

**Comment by Sharlikran** [comment] 2016-11-11 14:07
Also I don't think this should be changed until 1.2.39 is live but once it is the current beta then how the Skyrim SE version of Wrye Bash handles Skyrim.esm, Update.esm, and the DLC should change to eliminate confusion with players.

**Comment by Sharlikran** [comment] 2016-11-11 14:12
Utumno, in case this goes live really soon.  Would it be possible for you to make a branch off of dev and make the changes there?  Would it be possible for you to do that when you get time, maybe over the weekend?  Then I can test this during the Beta so all the details get worked out.

**Comment by Sharlikran** [comment] 2016-11-11 14:30
For my first test of just what happens to plugins.txt this is what I started with.

*Skyrim.esm
*Update.esm
*Dawnguard.esm
*Hearthfires.esm
*Dragonborn.esm
*Campfire.esm
*3rdEraWeaponsMoS.esm
*Riftrun_HF_v_2_0.esp <<- False Flagged ESP with Hearthfires as a master
*3rdEraWeapMoS-lvlList.esp
*Unofficial Skyrim Special Edition Patch.esp
*Bashed Patch, 0.esp

This is how the in game menu changed plugins.txt, I didn't change the position of the mods I just moved one and put it back to see what happened.

# This file is used by Skyrim to keep track of your downloaded content.
# Please do not modify this file.
*Campfire.esm
*3rdEraWeaponsMoS.esm
*Riftrun_HF_v_2_0.esp <<- False Flagged ESP with Hearthfires as a master
*3rdEraWeapMoS-lvlList.esp
*Unofficial Skyrim Special Edition Patch.esp
*Bashed Patch, 0.esp

Then the save header, without the DLC in plugins.txt listed this.

Skyrim.esm
Update.esm
Hearthfires.esm
Dragonborn.esm
Dawnguard.esm
Campfire.esm
3rdEraWeaponsMoS.esm
Riftrun_HF_v_2_0.esp <<- False Flagged ESP with Hearthfires as a master
3rdEraWeapMoS-lvlList.esp
Unofficial Skyrim Special Edition Patch.esp
Bashed Patch, 0.esp

**Comment by Sharlikran** [comment] 2016-11-11 14:42
With this: 

*Skyrim.esm
*Update.esm
*Dawnguard.esm
*Hearthfires.esm
*Dragonborn.esm
*Campfire.esm
*3rdEraWeaponsMoS.esm
*Riftrun_HF_v_2_0.esp
*3rdEraWeapMoS-lvlList.esp
*Unofficial Skyrim Special Edition Patch.esp
*Bashed Patch, 0.esp

I got this in the header

Skyrim.esm
Update.esm
Hearthfires.esm
Dragonborn.esm
Dawnguard.esm
Campfire.esm
3rdEraWeaponsMoS.esm
Riftrun_HF_v_2_0.esp
3rdEraWeapMoS-lvlList.esp
Unofficial Skyrim Special Edition Patch.esp
Bashed Patch, 0.esp

**Comment by Sharlikran** [comment] 2016-11-11 15:33
However, with all that said.  We might want to just wait until WrinklyNinja does his own tests and then decides what he is going to do.  I still think we should hash out some kind of support in the meantime so that it's ready but finalize it according to what LOOT does.

**Comment by Sharlikran** [comment] 2016-11-11 15:44
I think the support should do this

 - Not write Skyrim.esm, Update.esm, Dawnguard.esm, Hearthfires.esm, or Dragonborn.esm to plugins.txt
 - Skyrim.esm Update.esm should always be displayed first
 - Dawnguard.esm, Hearthfires.esm, or Dragonborn.esm should be order by time date stamp
 - All ESM and false flagged ESP files should be listed in plugins.txt
 - All remaining ESP files (not false flagged)

The test it and hold it and once WrinklyNinja decides what he feels is best for LOOT then follow what LOOT does.

**Comment by Sharlikran** [comment] 2016-11-11 16:13
Just test this I really messed with the Time Date stamp:

Skyrim.esm ```Modified: 11/11/2016 7:51 AM Created: 11/11/2016 7:51 AM```
Update.esm ```Modified: 11/10/2016 7:51 AM AM Created: 11/10/2016 7:51 AM```
Dawnguard.esm ```Modified: 11/7/2016 7:51 AM Created: 11/7/2016 7:51 AM```
Hearthfires.esm ```Modified: 11/9/2016 7:51 AM Created: 11/9/2016 7:51 AM```
Dragonborn.esm ```Modified: 11/8/2016 7:51 AM Created: 11/8/2016 7:51 AM```

Plugins.txt

*Campfire.esm
*3rdEraWeaponsMoS.esm
*Riftrun_HF_v_2_0.esp
*3rdEraWeapMoS-lvlList.esp
*Unofficial Skyrim Special Edition Patch.esp
*Bashed Patch, 0.esp

*Dawnguard.esm ```Modified: 11/7/2016 7:51 AM Created: 11/7/2016 7:51 AM```
*Dragonborn.esm ```Modified: 11/8/2016 7:51 AM Created: 11/8/2016 7:51 AM```
*Hearthfires.esm ```Modified: 11/9/2016 7:51 AM Created: 11/9/2016 7:51 AM```
*Update.esm ```Modified: 11/10/2016 7:51 AM AM Created: 11/10/2016 7:51 AM```
*Skyrim.esm ```Modified: 11/11/2016 7:51 AM Created: 11/11/2016 7:51 AM```

Dwanguard being the oldest, Skyrim.esm being the newest.

Result:

Skyrim.esm
Update.esm
Hearthfires.esm <<- \
Dawnguard.esm <<-- | All three ignored time date stamp.
Dragonborn.esm <<- \
Campfire.esm
3rdEraWeaponsMoS.esm
Riftrun_HF_v_2_0.esp
3rdEraWeapMoS-lvlList.esp
Unofficial Skyrim Special Edition Patch.esp
Bashed Patch, 0.esp

**Comment by Sharlikran** [comment] 2016-11-11 16:51
Just test this I really messed with the Time Date stamp:

*Skyrim.esm ```Modified: 11/11/2016 7:51 AM Created: 11/11/2016 7:51 AM```
*Update.esm ```Modified: 11/10/2016 7:51 AM AM Created: 11/10/2016 7:51 AM```
*Dawnguard.esm ```Modified: 11/1/2016 7:51 AM Created: 11/1/2016 7:51 AM```
*Hearthfires.esm ```Modified: 10/1/2016 7:51 AM Created: 10/1/2016 7:51 AM```
*Dragonborn.esm ```Modified: 9/1/2016 7:51 AM Created: 09/1/2016 7:51 AM```
*Campfire.esm
*3rdEraWeaponsMoS.esm
*Riftrun_HF_v_2_0.esp
*3rdEraWeapMoS-lvlList.esp
*Unofficial Skyrim Special Edition Patch.esp
*Bashed Patch, 0.esp

*Dragonborn.esm ```Modified: 9/1/2016 7:51 AM Created: 09/1/2016 7:51 AM```
*Hearthfires.esm ```Modified: 10/1/2016 7:51 AM Created: 10/1/2016 7:51 AM```
*Dawnguard.esm ```Modified: 11/1/2016 7:51 AM Created: 11/1/2016 7:51 AM```
*Update.esm ```Modified: 11/10/2016 7:51 AM AM Created: 11/10/2016 7:51 AM```
*Skyrim.esm ```Modified: 11/11/2016 7:51 AM Created: 11/11/2016 7:51 AM```

Dwanguard being the oldest, Skyrim.esm being the newest.

Result:

Skyrim.esm
Update.esm
Dragonborn.esm <<- \
Hearthfires.esm  <<-- | Time Date stamp observed
Dawnguard.esm <<- \
Campfire.esm
3rdEraWeaponsMoS.esm
Riftrun_HF_v_2_0.esp
3rdEraWeapMoS-lvlList.esp
Unofficial Skyrim Special Edition Patch.esp
Bashed Patch, 0.esp

**Comment by Utumno** [comment] 2016-11-11 17:24
@Sharlikran please summarize, also as noted I don't know what this timestamp bug is
As I said in relation to fallout4 enforcing the order is complicated - will eventually do but not an immediate priority, doesn't break anything
Loot is not related here I think - load order handling by Bash is pretty solid

Will enforce non deactivation iif present in my next iteration - plus hey, no more default tweaks files

Stay tuned

**Comment by Sharlikran** [comment] 2016-11-11 17:26
Okay I will clear out all my testing then.  I'll just keep it to myself and let you do what you want.  Then if users sort with LOOT and it's different in Wrye Bash they can come to you with their complaints and requests.

**Comment by Utumno** [comment] 2016-11-11 17:32
Oh come on no need to get grumpy! Come on sharlikran - I do need your tests but in a more condensed way plus info on what exactly should I look out for in respect to loot

**Comment by Sharlikran** [comment] 2016-11-11 17:51
Most of the time nobody believes me, period or cares what I say  Which is usually why I do what I want because it always works.  Because I make it do it that way.  Answering users questions is frustrating because they usually just argue with me.  Sometimes I am wrong and when I am, I am deeply sorry and make a note of my mistake.  And I am actually wrong sometimes because I don't know everything.  

However, I do know a lot and I can do things nobody else can do when it comes to repairing or merging plugins with xEdit.  I already fixed three files for Skyrim SE authors using the broken version of SPGD.  I just need to show how I did it because it would be useful until Bethesda fixes the issue.  Then again they may never fix it who knows.  I haven't tested 1.2.39 though which reminds me I have to test SPGD with that later too.  No rest for the weary.

I am going to kind of revert to my turtle shell for now though.  Not really because of just this, you have not been disrespectful to me, your request for condensed information is actually okay, but just because of everything.  I will finish rebasing my Skyrim SE branch though as it's turning out to be a pain to update common records used between Skyrim and SSE.  I just wish I had the Form Version check that xEdit has.

I'm not really grumpy or mad so to speak.  I know you appreciate the test and feedback.  However, one test didn't respect the time date stamp when the files were within a day.  It did respect it when the time date stamp was within a month.  I feel I need to do more testing though.

We don't have to introduce lobloadorder.dll again.  Not including that is fine.  I'm just saying LOOT is relevant and is what Wrye Bash should be "modeled" after.  When any tool deviates from what users see when they sort with LOOT then it causes confusion.  It's not about what any one individual or tool developer wants.  It's about no confusing users and you have to look at the lowest common factor in that case.  Meaning how can you make it the least confusing to users.

**Comment by Sharlikran** [comment] 2016-11-11 17:53
While I can't program in Python I muddle along to add the functionality I need and that is useful for other users.  Sometimes what I add or change may not be a priority but users should be the priority and not the code base.

**Comment by Utumno** [comment] 2016-11-11 18:26
Sharlikran if you didn't have these outbursts it would be much easier for me - they really disrupt me. So please go on with your testing and post me your results as condensed as possible. I do care what you say and I know you do care what I say because of your recent excellent work on cleaning up your branches. So please next time you feel like deleting your posts take a stroll or a deep breath or something to that effect first. And I would like to cleanup the tracker from the drama - it really makes a bad impression

>  users should be the priority and not the code base.

There is no difference in my level between the two - it may appear that there is but if you actually knew what I know you'd see that actually the codebase is the users. If I had (more) people following my lead I could address the user visible stuff faster - but I have to address everything and it would help if I didn't have to repeat the obvious fact I know what I am doing and when I ask something I ask it not cause I have any superiority complex but simply because it must be done. That's the way it is with software - the lead engineer knows too much to try and explain every single time it requests a change. It's plain impossible to convey my years of working with the code - you have to trust me.

**Comment by Sharlikran** [comment] 2016-11-11 18:32
> the lead engineer knows too much to try and explain every single time it requests a change. It's plain impossible to convey my years of working with the code - you have to trust me.

That is why I rebased my branches and will continue to do so.  

Sorry for the drama sometimes.  I don't think I can help it but I can try to do it less or in a different way at least.

**Comment by Utumno** [comment] 2016-11-11 18:41
Thanks Sharl - will go on explaining but mostly in commit messages. Was off work today and I took the opportunity to finally addressing hardcoding the ini tweaks. I did it before the beta (not after as I planned) cause with skyrim se we'd have to commit a gazillion files on dev again - so I went ahead, needs some more testing but will merge to dev so we can base the game support branches on that (will do the rebase myself so you can easily compare).

**Comment by Arthmoor** [comment] 2016-11-11 19:06
So exactly what condensed information do you need? I think the report I gave you was already pretty cut and dry - the DLC files are being sorted in-game by their timestamp. Several users have verified this already. Wrye Bash is deviating from behavior the game itself expects to happen, but it seems like people don't want that corrected for some reason and I honestly don't get why.

**Comment by Utumno** [comment] 2016-11-11 19:17
>  the DLC files are being sorted in-game by their timestamp

I addressed my comments to sharlikran - you probably missed some posts

> > [Bethesda's timestamp bug not withstanding]

> I beg your pardon ?

So this is the timestamp bug - but is it a timestamp one ? Or does bethesda load those esms in this order by their name ? One way or the other the worse this means (correct me if wrong) is that the load order may seem different to the user that it actually is - but in this case there would be no real problem, as if those load just after Skyrim and Update then they will load before dependencies. Would be nice to enforce this in the plugin txt and the UI but not an emergency - or do I get it wrong?

**Comment by Sharlikran** [comment] 2016-11-11 19:20
Despite all I said and deleted I'm pretty sure Utumno has said he will change the behavior.  WrinklyNinja wants to wait until the dust settles.  That might be a good idea.  I still think if and when Utumno has time a branch with some test code could be helpful because there is no way to know when this will go live.  

Since Utumno is probably out of time today I'm just going to be patient.  There is no way to know what Wrinkly will decide, what Wrye has to do, and whether or not Bethesda will slightly alter this behavior.  I'm defiantly going to ask Bethesda about it because it's a mess.

**Comment by Arthmoor** [comment] 2016-11-11 20:20
I'm really not sure what part of this is unclear. I explained it. The 3 DLC files get loaded into the game in the order of their timestamps. It's easy as pie to validate this. Change the dates to be wrong, load the game, find something from one of the DLCs, and use the console to get its ID. It will be plainly obvious at that point.

Right now, since the game will only put actual mods into plugins.txt and not any the official files, Wrye Bash gets confused, tosses them in, and presents you with a scrambled looking load order on the Mods tab. Confusing users is simply not acceptable IMO. The game will ignore it with Patch 1.2.39, but that's beside the point.

I'm also not demanding this be done immediately either. I opened the issue because it needs to be addressed, that's all. Maybe I'm misreading the tone from both of you but it's coming across as resistance to the very idea of correcting this.

**Comment by Sharlikran** [comment] 2016-11-11 20:25
> and use the console to get its ID. It will be plainly obvious at that point.

Utumno doesn't have Skyrim SE that I know of.  He has Skyrim.  So if he had all the DLC then he gets a free copy of Skyrim SE maybe he either doesn't know or didn't have all the DLC.

> Maybe I'm misreading the tone from both of you 

Maybe.

> I'm also not demanding this be done immediately either.

Then I think we are all on the same page.

**Comment by Utumno** [comment] 2016-11-11 20:28
Not at all - sharl tried to supply some tests and Arthmoor do I really come across this way ? Like I want to confuse users ?

You just forget I do not frequent the forums so I did not know anything about it - see your OP - you refred to the `[Bethesda's timestamp bug not withstanding]` which I did not know what it was.

please always read my posts thinking I am most interested in what you say, but also imagine me thinking on code terms ;)

Soooo:

> The game will load these 5 files regardless of what's specified

Will fix (easy)


> but the game will utterly ignore these 5 files being there, and they need to be locked to this specific order.

This specific relative order or absolute order - as in do they load in positions 0 - 4 ? Or they just keep their relative order ?

**Comment by Sharlikran** [comment] 2016-11-11 20:34
0 skyrim.sem, 
1 update.esm, 
2 anyoneofthethreedlc.esm (time stamp dependant), 
3 anyoneofthethreedlc.esm (time stamp dependant), 
4 anyoneofthethreedlc.esm (time stamp dependant)

Does that help because I can't tell You, put draagonborn.esm as 3, it's by time stamp for the three files like Oblivion,fnv,fo3 used time stamps.

Then it's dtarvload order for everyhing else.

**Comment by Sharlikran** [comment] 2016-11-11 20:40
Just display them in that order on the mods tab.  Make sure the DLC shows the name and the current time date stamp so users know what is going on.  Make it so you can't enable them or disable them.  It should be like a facade or false store front.  You can even grey out the text if you want.  Then what Arthmoor is saying is don't write them to plugins.txt.  It should be purely cosmetic for 0-4.

**Comment by Utumno** [comment] 2016-11-11 20:43
> Just display them in that order on the mods tab.

Hard

> Make sure the DLC shows the name and the current time date stamp so users know what is going on.

Well yes :P

> Make it so you can't enable them or disable them.

Easy - no need for bells and greys as we already do that for master esm etc

>Then what Arthmoor is saying is don't write them to plugins.txt.

Needs thinking

**Comment by Arthmoor** [comment] 2016-11-11 21:27
Why does not writing them to plugins.txt need thinking? This is how the game officially handles it. Shouldn't Wrye Bash be following the same example?

The game will completely ignore them if they're there anyway so I don't see the point - and incidentally I'm told this is exactly what NMM is already doing, leaving them out. I refuse to install NMM though because I don't want it's dumb virtualization system screwing things up.

**Comment by Sharlikran** [comment] 2016-11-11 21:33
> Why does not writing them to plugins.txt need thinking?

How to do that since the code is currently embedded with ways to write all files in the data folder for all the games.  This is kind of like the saves game issue.  Not hard to conceptualize, hard to implement programing wise.

**Comment by Utumno** [comment] 2016-11-11 21:38
> hard to implement programing wise.

> please always read my posts thinking I am most interested in what you say, but also imagine me thinking on code terms ;)

:)

**Comment by Arthmoor** [comment] 2016-11-11 22:35
Ah, well, I'll leave the programming to people who can actually do it. :)

It's just that when you phrase things that way, not everyone will assume you always mean in terms of code. It really does come across as needing to debate the reason for doing it entirely.

**Comment by Utumno** [comment] 2016-11-12 15:12
@Arthmoor @Sharlikran: final se support branch:

https://github.com/wrye-bash/wrye-bash/tree/skyrim-se-support

Please test this works ok

@Sharlikran in particular - please verify the recod definitions and the constants in this commit:

ccfa66faf82aa8b01b984e7c2e67af7dca06b8cc

We can't afford errors in records as remember Bash will corrupt files (on editing description for instance as you both remember from 306 dev) - so verify I got the correct edits in there

Also please generate atag list based on loot 10 and mention me so I chgerry pick it - the loot 10 by wrinkly has one - is it correct ?

Thnaks everybody we are good to go - will address the timestamp DLC bug soon - but lets wiat for more info

For now deactivating the DLCs is not allowed by Bash

**Comment by Sharlikran** [comment] 2016-11-12 16:44
> Please test this works ok .. in particular - please verify the record definitions and the constants in this commit .. We can't afford errors in records as remember Bash will corrupt files (on editing description for instance as you both remember from 306 dev) - so verify I got the correct edits in there

As with your discussion with Arthmoor please read my comments with the intent to clarify what you are asking, I'm not talking down to you, I'm not questioning your Python programming skills, I'm not showing mistrust for your goals for the project or as the  lead engineer.  I do ask you trust the record definitions I provide as that is what I do for xEdit.  There will always be the need for testing and refinement.

Currently the biggest issue isn't the record definitions themselves but the information the patcher places into the Bash Patch.  However, that can't be addressed by you until the code is in dev and re-evaluated like you did with the Tweaks Patcher.

When using my code please use it as is.  If I have changed code since your last pull from downstream. then as you request I do, don't change the constants and rebse off of my changes.  If you don't the only way the code will be broken is because you didn't use the code I provided.  I don't need to test it, the code needs to be merged or imported as I have indicated.

I understand your concerns but this has been working since Oct 27 and has been used by approximately 11,729 people.  All updates and code changes have been made by testing from people using the record definitions and reporting issues.  The testing has been done with a wide variety of plugins in real game play situations.  Not with small minimal reproducers but mods with thousands of records that are patched or merged into the Bashed Patch.

Code will never be perfect.  User reports of issues is part of development, which you know.  Even with xEdit there have been many refinements in the last 5 years to the original record definitions that Elminster first submitted.  All carefully verified by the xEdit team.

If you constantly question the changes I make, remind me that accuracy is important when I already know that, ignore that there will always be regressions, forget that I have pointed out some regressions you didn't intentionally make, then I see no reason to continue providing updates.

**Comment by Sharlikran** [comment] 2016-11-12 16:45
I didn't mean to post my comment here.  Please disregard.

**Comment by Arthmoor** [comment] 2016-11-12 21:27
@Utumno As far as I can tell, that test branch is working fine, the only issue I see is that when exiting the game and focusing back onto Bash, it decides the load order arbitrarily instead of putting things back in a proper order.

The DLC at least can't be deactivated though.

**Comment by Utumno** [comment] 2016-11-12 21:49
>  it decides the load order arbitrarily instead of putting things back in a proper order.

Ooops - an example ? Cause I can't exit the game :P

I guess the game removes the official DLCs ?

**Comment by Arthmoor** [comment] 2016-11-12 22:09
This is what Bash sees before loading the game: https://i.imgur.com/TEkSviR.jpg

Plugins.txt looks like this:

```
*Skyrim.esm
*Update.esm
*Dawnguard.esm
*HearthFires.esm
*Dragonborn.esm
*Unofficial Skyrim Special Edition Patch.esp
404Update.esp
Alternate Start - Live Another Life.esp
Bashed Patch.esp
```

Run the game, access mods menu, tweak load order, and while the game is still running, plugins.txt now looks like this:

```
# This file is used by Skyrim to keep track of your downloaded content.
# Please do not modify this file.
*Unofficial Skyrim Special Edition Patch.esp
404Update.esp
Alternate Start - Live Another Life.esp
Bashed Patch.esp
```

Close the game. Switch back to Bash, and now it looks like this: https://i.imgur.com/rIaPiQJ.jpg

and plugins.txt looks like this:

```
*Skyrim.esm
*Unofficial Skyrim Special Edition Patch.esp
*Update.esm
*HearthFires.esm
*Dragonborn.esm
*Dawnguard.esm
404Update.esp
Alternate Start - Live Another Life.esp
Bashed Patch.esp
```

Now, again, I want to stress that even though the plugins.txt file is messed up, the game will simply ignore the fact that the official files are there, even if they're in the wrong order.

Bash just needs to not end up making it look like the last one because people using it will get horribly confused by that.

**Comment by Utumno** [comment] 2016-11-12 22:16
Gosh, yep Bash sees the plugins as missing and readds them after the first esm that it's there, duh

Thanks for detailed examples I now have a clear picture - so I must really address this issue ASAP. It's just a bit tricky

**Comment by Utumno** [comment] 2016-11-12 22:18
@Arthmoor can you confirm that the load order of dlcs is as stated by Sharlikran ? That is:

0 skyrim.sem,
1 update.esm,
2 anyoneofthethreedlc.esm (time stamp dependent),
3 anyoneofthethreedlc.esm (time stamp dependent),
4 anyoneofthethreedlc.esm (time stamp dependent)

That is they will always load just after the master and Update esms ?

**Comment by Arthmoor** [comment] 2016-11-12 23:22
Yes. That's exactly how the game currently handles it as of 1.2.39. I'm hoping they'll close up that last one, but don't count on it. I think it would be prudent to include something like the old BSA redate thing to set the DLCs to 10/28/2016 at one minute intervals.

Not only will that keep the game in line, it'll help with the CK too since the CK is exclusively timestamp driven.

**Comment by Sharlikran** [comment] 2016-11-12 23:26
I think trying to meld Skyrim classic load order, Oblivion plugin redating, and the Star Load order system is a bit much at this time.  Plus you can verify this if you wish Arthmoor.  If you verify your game cache then all the dates are the same but the game will still load them how it wants to.  If you then go into the Mods menu in game it will not redate the DLC.

**Comment by Arthmoor** [comment] 2016-11-13 00:28
I really REALLY do not understand the resistance to this. Actively allowing mod management tools to leave a possible breakdown in place seems negligent.

**Comment by Sharlikran** [comment] 2016-11-13 00:44
Again you are thinking I am or someone else is resistant.  You are asking for complex code to be altered that would take a major rewite.  I am sure it can be done, I'm just saying it will be difficult, and for now you may only get plugins.txt to not contain the DLC but not redating the masters.

Anyway I am done arguing.  I have more important things to do and I plan on dealing with this in an objective mannor.  I still don't want to ruin my friendship with you or Utumno so yet again I have to shut up and stop talking.

Which is disappointing because I'm waiting for Utumno to merge the changes into dev.  Then I have to test his changes to see if they inadvertently fixed an issue I am researching, which I mentioned to him in a PM.

If I use Wrye Bash with classic Skyrim this plugin 
[No Vampire Attacks In Towns.zip](https://github.com/wrye-bash/wrye-bash/files/587532/No.Vampire.Attacks.In.Towns.zip) will be assigned the proper FormID in relation to it's master, which is Dawnguard.esm.  

The code as of commit https://github.com/wrye-bash/wrye-bash/commit/aedf071bb25d20721affec2e80f1add6c51f6e76 when used with Skyrim SE makes two of the FormIDs in those records end up with a prefix of 02 when it should be in line with the Dawnguard master and have a prefix of 01.

So while you are all fretting over everything, I'm looking into why Wrye Bash is creating an unresolved reference in the Bash Patch.  It doesn't for Skyrim, but it does when the same plugin made with the Skyrim SE CK is used with Skyrim SE.

Partial functionality is possible and there are other issues to resolve.

**Comment by Utumno** [comment] 2016-11-13 03:39
>  I think it would be prudent to include something like the old BSA redate thing to set the DLCs to 10/28/2016 at one minute intervals.

Hmm I was just thinking of loading those mods internally based on their timestamp which is not likely to change

**Comment by Arthmoor** [comment] 2016-11-13 04:17
It might end up in an ambiguous state though. I've had at least one person other than Sharlikran say that if you revalidate the game's files through Steam that the 3 DLC files will emerge with identical timestamps, and I think we all remember what a mess stuff like that made in Oblivion.

**Comment by Utumno** [comment] 2016-11-13 04:47
For the moment I added a commit that addresses most of the stuff - dlcs can't be reordered they are ordered by timetsamps, plugins txt is cleaned from the entries and testing needed :)

Now if that's ok I can go on and nail the order of the plugins, think/discuss what's best and provide me with a exact specification covering all possible scenarios (there are many and since I don't have the game I can't even start to imagine what the User can do to mess timestamps etc or with the loader and then Bash starts, Bash already running etc variations)

And go easy on me everybody, I start getting tired ;)

**Comment by Sharlikran** [comment] 2016-11-13 04:49
Get some rest.  I appreciate you willing to look into the matter.

**Comment by Sharlikran** [comment] 2016-11-13 04:56
I like it so far.  I can redate the plugins and it shows up in Wrye Bash just fine.  I'm going to test a save game though to see if it has the same order as I see in Wrye bash.

**Comment by Sharlikran** [comment] 2016-11-13 05:23
The save game header reflects the order seen in Wrye Bash even though the order is (cosmetic?) static at this time.

**Comment by Arthmoor** [comment] 2016-11-13 07:04
Looks good to me.

I like how if you restart Bash after messing with the timestamps it shows the results of doing it too. That should provide a pretty clear picture that something is wrong and needs fixing.

**Comment by Utumno** [comment] 2016-11-13 13:24
Ok thanks. @Arthmoor do you think anything further must be done ?

**Comment by Arthmoor** [comment] 2016-11-13 20:23
Other than automatically setting the dates in the proper order, no, I think it's fine as is and can go into dev whenever.

**Comment by Utumno** [comment] 2016-11-24 13:04
So closing this @Arthmoor ? Or do we need to go and redate after all ? Or would this borg save games ? Or... ?

**Comment by Arthmoor** [comment] 2016-11-24 19:06
I think it would be best if the DLCs were automatically redated so that they always load correctly. Unless Bethesda surprises us all and fixes it, this will remain an ongoing problem.

**Comment by Utumno** [comment] 2016-11-24 19:20
Yes - but look a bit at the threads, people are surprised by Bash handling of the issue already. How do we go about that ?

**Comment by Arthmoor** [comment] 2016-11-24 20:08
I'm not sure I understand. Bash isn't handling it right now, at least not automatically. If it were, this problem would go away and you wouldn't have threads popping up every 3 minutes :P

**Comment by Utumno** [comment] 2016-11-24 20:15
What I mean is that maybe users would still be confused by Bash rearranging their lo (other tools are behind I guess)

Well will hash up a patch and let you know to test it

**Comment by Arthmoor** [comment] 2016-11-24 21:29
As I understand it, LOOT and NMM are already doing this, so it's Bash that's a little behind at this point.

**Comment by Arthmoor** [comment] 2016-11-27 23:38
Like SSE, Fallout 4 needs to have its DLC load order locked in place. Some folks have been testing and found that the game wants to hard lock everything like so:

00  Fallout4.esm
01  DLCRobot.esm
02  DLCworkshop01.esm
03  DLCCoast.esm
04  DLCworkshop02.esm
05  DLCworkshop03.esm
06  DLCNukaWorld.esm

Since Bash can see masters on FO4 saves we can confirm absolutely that the first 7 slots of any load order are always as listed.

Further, the game does not write the official files to the plugins.txt file, just like SSE. So the logic you wrote up to handle that needs to be applied to FO4 as well. This includes not being able to switch the DLC's positions with each other OR to deactivate any of them since the game will not honor the changes.

LOOT is already handling this in the proper manner which is leading to the same level of confusion when Bash regains focus and scrambles the display on the mods tab, which the game ignores, etc.

The only thing that doesn't need to be done is changing timestamps. FO4 seems happy enough to ignore those.

The only complication I can see coming from this is that not everyone has every DLC since they were sold separately in addition to the Season Pass. So there may need to be some extra logic to maintain the relative order of things if some of the DLCs are not present.

**Comment by Utumno** [comment] 2016-11-28 02:59
Excellent thanks - will do ASAP

**Comment by Utumno** [comment] 2016-11-28 19:17
@Arthmoor - try latest utumno-wip please :)

**Comment by Arthmoor** [comment] 2016-11-28 22:59
So far as I can tell, it's all working good. Thanks :)

**Closed** 2016-12-03 17:57 UTC
Labels: skyrim-se, TODO
