### ISSUE TITLE
Wrye bash error code on windows 10

### ISSUE THREAD

**Issue by Madpaddy** [wrye-bash/wrye-bash#410] opened 2018-05-02 23:28 UTC
I get this error code when running Wryebash just on windows, it happens with WB 307 and also the Dev builds, I'm running windows 10 ver 1803 build 17134.5. Please at least take the time to investigate it before saying its not WB related, maybe its a Windows 10 issue but unless your willing to find out Wryebash isn't going to be as useful and bug free as we all want it to be and Windows 10 is going to be a system WB will need to work on, many thanks for your time.

windows 10 ver 1803 build 17134.5

Wrye Bash encountered an error.

Traceback (most recent call last):
  File "bash\bash.py", line 227, in main
    _main(opts)
  File "bash\bash.py", line 393, in _main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 3981, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4021, in InitData
    bosh.saveInfos.refresh(booting=True)
  File "bash\bosh\__init__.py", line 2726, in refresh
    return refresh_infos and FileInfos.refresh(self, booting=booting)
  File "bash\bosh\__init__.py", line 1382, in refresh
    notify_bain=not booting)
  File "bash\bosh\__init__.py", line 1358, in new_info
    notify_bain=notify_bain)
  File "bash\bosh\__init__.py", line 1277, in new_info
    load_cache=True)
  File "bash\bosh\__init__.py", line 393, in __init__
    super(FileInfo, self).__init__(g_path, load_cache)
  File "bash\bosh\__init__.py", line 274, in __init__
    self._reset_cache(self._stat_tuple(), load_cache)
  File "bash\bosh\__init__.py", line 405, in _reset_cache
    if load_cache: self.readHeader()
  File "bash\bosh\__init__.py", line 1108, in readHeader
    self.header = get_save_header_type(bush.game.fsName)(self.abs_path)
  File "bash\bosh\save_headers.py", line 60, in __init__
    self.load_header(ins)
  File "bash\bosh\save_headers.py", line 76, in load_header
    self.load_image_data(ins)
  File "bash\bosh\save_headers.py", line 340, in load_image_data
    self._drop_alpha(ins)
  File "bash\bosh\save_headers.py", line 94, in _drop_alpha
    itertools.compress(ssData, itertools.cycle(reversed(range(4)))))
MemoryError

**Comment by Arthmoor** [comment] 2018-05-02 23:56
I'm on Windows 10 build 1803 and cannot reproduce this problem. What were you trying to do?

**Comment by Madpaddy** [comment] 2018-05-03 00:47
I'm trying to run Wrye bash, it was working perfectly until about 2 wks ago now it won't run at all even just trying to fire it up on its own it always comes up with that error. It tries it comes up with the Wrye bash window but when it would normally open it stops with that error.

**Comment by Arthmoor** [comment] 2018-05-03 01:01
Mine says 17134.1 but I doubt that could make much of a difference. No updates are pending either.

All I can tell you is that for me it works fine, but I'm also running it directly, not via a shortcut from MO.

**Comment by Madpaddy** [comment] 2018-05-03 02:14
Im not running it through MO atm as i have said even just running in windows it says the same error. Does that error not tell you something ??. It is also possible that windows update is the problem i have had windows updates before that have broke things so its not out the question. The error seems to point to a Python error and something about memory.

**Comment by Madpaddy** [comment] 2018-05-03 04:04
But as it still does the same without MO I don't see why it's even a chain of thought, yes I did think that was the cause at first but I've taken that out the equation and get the same result. At the end of the day I didn't post this to try and be a pain in the ass I posted it because I assumed that the guys working on Wrye bash would want to see that error so they could find out what is causing it, it shouldn't be running out of memory as I have 32GB of ram and 8GB Vram. Also, I'm not trying to convince anyone logic would dictate the WB guys want to make it as best as they can and stable for as many as possible, but maybe I'm wrong. I can get by with Mator smash for the time being and hopefully someone may look at that error and find a fix if not then I know for future reference reporting bugs is not well received.

**Comment by Arthmoor** [comment] 2018-05-03 04:30
Not sure why you're reacting the way you are. I'm merely stating that I can't reproduce your problem and IMO that's as relevant as the bug report itself.

Someone else who might know more will certainly see this soon enough.

**Comment by Utumno** [comment] 2018-05-03 10:43
As is said when you open an issue here and as I instructed you personally on the previous issue _you should first post on the forums_. Please post there, adding all the rest of the info requested. Till this is discussed at the forums closing this - after all a MemoryError is a memory error we can't do anything about it, but you may get hints as to why you get it at the forums.

**Closed by Utumno** 2018-05-03 10:43 UTC
Labels: R-invalid

**Comment by Infernio** [comment] 2022-07-01 19:12
Obsolete as of 308 (64bit upgrade).
