### ISSUE TITLE
Crash when changing status bar icon size

### ISSUE THREAD

**Issue by E10X11** [wrye-bash/wrye-bash#334] opened 2016-10-29 17:31 UTC
I found this to be rather strange but whenever I try to change the size of the icons on the status bar it crashes. If I click on anything in that submenu, it crashes.

I might be the only one having this issue but its really irritating because I cannot really see the status bar at the default icon size.

**Comment by Utumno** [comment] 2016-10-29 18:30
I had a similar report a long time ago but should be something peculiar in your setup - please see https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug fro reporting a bug

**Comment by Sharlikran** [comment] 2016-11-01 01:37
I'm able to change that without any issue.  However, I do have Windows 7 and I don't have a 4K display or anything like that.  Where did you download Wrye from? What version is it?

**Comment by E10X11** [comment] 2016-11-27 07:21
First thing. Sorry for the late response! I'm not on Github very often.

I have Windows 8.1 installed on a 1080p monitor with the like resolution. It seems to happen with 306 and 307 and 306 was picked up from Nexus and 307 here. At the time I had Classic Shell installed and then I uninstalled it and reinstalled Wrye Bash and somehow it fixed it.

**Comment by Utumno** [comment] 2016-11-27 11:31
Alright so it's a classic shell thing ? The fact that happens on 306 too means it's probably something with wx (the graphics library we're using) and some third party program - not windows 7 at least as I run Bash countless times and never had this crash.

Closing as `works for me` but I keep the needInfo label just in case you come with something more specific

**Comment by E10X11** [comment] 2016-12-04 17:35
@Utumno @Sharlikran 

Did a bit more testing. This time it seems to be more 307/8.1 specific since it does not happen with 306. It will crash at random and sometimes always crash when changing the icon size.

It might be an issue with the Windows 8.1 File Explorer and 307 not liking it very much. If anyone also running 8.1 could reproduce it that would be helpful. If not it's something with my installation.

**Comment by Utumno** [comment] 2016-12-04 17:42
I am on 7 so can't reproduce - interested in any findings

**Comment by E10X11** [comment] 2016-12-14 04:12
It's a Windows Explorer issue. The issue seems to only happen when it glitches out and has to be restarted.

[https://www.easytechguides.com/windows-8-start-button-problem.html](https://www.easytechguides.com/windows-8-start-button-problem.html) Might not be much use, though.

**Comment by Utumno** [comment] 2017-04-28 04:29
I merged some icon work that may help with this one:
https://github.com/wrye-bash/wrye-bash/commit/c894892790702bd2b44c79a8ff1a734dbc7caecd

**Comment by JamesYeoman** [comment] 2018-01-24 11:44
I have Bash 306 on Win 8.1 and am getting the crash upon changing Icon Size.

I use Standalone Bash and I executed \["Wrye Bash.exe" -d\] and went through and caused the crash to occur (change the status bar icon size to 24 from 16) but there wasn't anything written to BashBugDump.log so... idk what else to upload other than the crash dump that was generated in AppData\\Local\\CrashDumps 

[CrashDump.zip](https://github.com/wrye-bash/wrye-bash/files/1659637/CrashDump.zip)

I also use Classic Shell if that info is of any use.

**Comment by Utumno** [comment] 2018-01-24 12:29
@JamesYeoman - thanks - this is still elusive - removing compatibility mode fixes it ?

**Comment by JamesYeoman** [comment] 2018-01-24 12:55
@Utumno yes, removing compatibility mode does indeed fix it. In fact, I currently have Wrye Bash open with an icon size of 32

**Comment by Utumno** [comment] 2018-01-28 15:11
See: https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=171418 and ex

**Comment by jfgagnon328** [comment] 2018-08-20 21:21
Hi!  I am adding the comment for "archiving" purposes.
I am on Windows 10, no compatibility mode, running as administrator because the games are installed in "Program Files", no Classic Shell.
Changing the icon sizes would crash instantly.
I clicked on the Installers tab (waited for the updating window).
I then could change the icon size.
Thank you for the tool!

**Closed** 2023-12-29 22:40 UTC
Labels: C-bug, A-wx, A-gui
