### ISSUE TITLE
Attempting to Resize Window Regions Raises TypeError with Lambda

### ISSUE THREAD

**Issue by jamesbiederbeck** [wrye-bash/wrye-bash#356] opened 2017-01-05 01:02 UTC
The specific error text is : 

`TypeError: <lambda>() takes exactly 2 arguments (1 given)`

I suspect that the lambda is getting called by an iterator somewhere, and expecting "self" as one of its arguments.

**Comment by Utumno** [comment] 2017-01-05 03:51
See https://github.com/wrye-bash/wrye-bash/wiki/[github]-Reporting-a-bug

In particular the full traceback and - errrr - the window ?

**Comment by Infernio** [comment] 2019-01-05 09:43
I've actually hit this with some development builds before as well... I'll see if I can replicate it.

**Comment by Utumno** [comment] 2019-01-05 09:51
Thanks @Infernio as it stands it's not really useful but please reopen as needed. Should have been a trivial fix with the bugdump

**Comment by Infernio** [comment] 2019-07-21 16:34
Randomly figured out how to reproduce this while setting up a new Skyrim installation:
Double click on any 'window separator' (e.g. the separator between the *Description* and *Masters* sections in the Mods tab)

Unfortunately, the [bug dump](https://gist.github.com/Infernio/0af9ab629070d3578d841a237f942e67) is less than helpful since it doesn't give a trace, only the error message

**Comment by Utumno** [comment] 2019-07-22 09:04
Hey @Infernio glad to see you back - grep for lamdas with two arguments is where I would start from (hopefully they are few). Let's hope it's not on wx side. Can't be of much help now as away from windows machine. We need to post a nightly though, nightly branch contains couple fixes and the feles readmes (at last). If you could do this it would be great - keep the bass.py version change and commit it to nightly, that way we can check people are using that version (I just stage it from the gui while executables are building). One issue I have not had time to look at is #441 - should be an easy fix, just make dialog resizeable or something.

Thanks :)

**Comment by Infernio** [comment] 2019-07-22 22:36
Should be fixed as of https://github.com/wrye-bash/wrye-bash/commit/3777650f1aa4820e5e48124017eab85117c2e2b7.

**Comment by Infernio** [comment] 2019-07-23 02:37
@Utumno Built a new nightly ([307.201907230210](https://github.com/wrye-bash/wrye-bash/commit/46139bf88110f8fd22c244a10832ba3d45452ffe)) and pushed it to dropbox.

**Closed** 2019-07-31 14:55 UTC
Labels: bug
