### ISSUE TITLE
Status bar launchers not updating when switching games via Settings

### ISSUE THREAD

**Issue by RavenMind** [wrye-bash/wrye-bash#399] opened 2017-12-03 10:21 UTC
Ref threads [here](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=170726), and [here](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=170752).

Possible related issue: Switching games more than twice causes WB to close/reopen only to the last selected game. (See first "Noticed Behavior" below.)

**Setup:**

- Wrye Bash v307.201711250133 (Python)
- Windows-8-6.2.9200 (Win10 Home v1709, Build 16299.64)
- Python v2.7.10, wxPython v2.8.12.1, Scandir v1.6
- FO4, SSE, Oblivion installed & detected via registry
- Separate Mopy folders in each game directory, with dedicated bash.ini for each
- Shortcut for LOOT present in \Mopy\Apps directory for FO4 & SSE; but not in Oblivion

**Repro:**

1.  Launch Wrye Bash via Wrye Bash Launcher.pyw, Wrye Bash Debug.bat, or shortcut.
2.  Click Settings "gear" icon.
3.  Mouse over Game, choose any other game.
4.  WB closes, then reopens to selected game. (Triggers Status Bar launcher issue.)
5.  Repeat 2-4. (game doesn't matter)
6.  Repeat 2-4 once more, triggers first noticed behavior)

**Noticed Behaviors:**

- Switching games more than twice does not work. Wrye Bash will close/reopen to the last selected game.    
          **Example-1:** Open WB from ..\Oblivion\Mopy. Switch to FO4, switch to SSE, try to switch to either other game - WB reopens only to SSE (second game switched to).
          **Example-2:** Open WB from ..\Fallout 4\Mopy. Switch to SSE, switch back to FO4, try to switch to either other game - WB reopens only to FO4 (second game switched to).
- Status bar apps are incorrect. E.g., only shows apps added via INI or Apps folder for the game WB originally launched for.
          **Example** (_Originally launched WB for Oblivion_): After switching to any other game, showing Insanity's Readme Generator, TES4Gecko, & BOSS, which are not activated in the SSE or FO4 bash.ini's.
- xEdit & xLODGen are showing "TES4" instead of "SSE"/"FO4", and when launched, operate on Oblivion not SSE or FO4.
- LOOT, which is included in the ..\Skyrim Special Edition\Mopy\Apps directory, (and FO4), does not appear.
- Command line window does not reappear after switching games, when originally launched in Debug mode.
- Items in Installers/Mods/Saves/INI Edits appear correct.
- Other attempted Bash functions appear to be working; Install/Uninstall, reordering, Patch rebuilding, etc.

**Comment by Utumno** [comment] 2018-01-06 14:45
@RavenMind 

> Switching games more than twice does not work. Wrye Bash will close/reopen to the last selected game.

Had different behavior - started for Fallout4 that's not installed in registry then naturally disappeared but switching games worked. _More  info needed on this one_

> Status bar apps are incorrect. E.g., only shows apps added via INI or Apps folder for the game WB originally launched for.

Nothing we can do - Bash launches the same _install_ just redirecting the game via `-o` cli argument 

- [ ] dialog here warning this will be the case with "Don't show this again" checkbox

> xEdit & xLODGen are showing "TES4" instead of "SSE"/"FO4", and when launched, operate on Oblivion not SSE or FO4.

That needs investigating

> Command line window does not reappear after switching games, when originally launched in Debug mode.

Does this affect debug functionality (ie the Dump) ?

----

Quick tests above performed on utumno-wip (that is _with_ rewritten `Restart`) - @RavenMind could you check that branch ?

@D4id4los - could you tak ethis up - again boot/restart related, but should be much easier than the rest.

It's also related to #250, Apps/game management

**Comment by Infernio** [comment] 2019-10-09 17:07
How relevant this issue at this point?
> Switching games more than twice does not work. Wrye Bash will close/reopen to the last selected game.

Can't reproduce. Tried switching like this: FNV -> FO3 -> Enderal -> FNV -> Skyrim -> SkyrimSE -> FNV. Worked fine.
> Status bar apps are incorrect. E.g., only shows apps added via INI or Apps folder for the game WB originally launched for.
> LOOT, which is included in the ..\Skyrim Special Edition\Mopy\Apps directory, (and FO4), does not appear.

Like Utumno said, this is expected. I'll add a dialogue warning about that.
> xEdit & xLODGen are showing "TES4" instead of "SSE"/"FO4", and when launched, operate on Oblivion not SSE or FO4.

Can't reproduce. Launched in FNV, where the xEdit link launched FNVEdit, then switched to SSE, where the xEdit link launched SSEEdit.
> Command line window does not reappear after switching games, when originally launched in Debug mode.

Pretty sure this no longer applies. I get no command line windows when I run the installer debug versions.

**Comment by Infernio** [comment] 2019-10-09 17:20
See 2ce09f3f32baeaa714b907882cace3814b691c6b - @Utumno is `Link.Frame` fine there? I couldn't think of anything else that would work as parent, IIRC `None` would crash on systems that can't do vista dialogs.

**Comment by Arthmoor** [comment] 2019-10-09 18:36
I've never been able to reproduce any of this behavior. I had heard about it before but didn't realize there was an open issue for it. Switching games has been working perfectly fine for me with no noticeable effects.

**Comment by Infernio** [comment] 2019-10-09 18:40
The status bar launchers definitely don't update. I have no files in `G:\steam\steamapps\common\Fallout New Vegas\Mopy\Apps`, but 6 shortcuts in `G:\steam\steamapps\common\Skyrim Special Edition\Mopy\Apps`. If I launch `Wrye Bash - FalloutNV` from the start menu, no launchers appear (as expected), and when I switch to SSE, it still has no launchers. This is expected behavior too, since we just relaunch the same installation with a different `-o` parameter.

Everything else seems to have been fixed somewhere along the way, I guess.

**Comment by Utumno** [comment] 2019-10-09 19:33
Thanks for looking at this - well real fix is ... #250. Moving to 308 we should revisit the whole wrye Bash install. The idea of one install per game does not make sense - we should install in a central location and create profiles per game. Main thing that has to change is exactly the App folder - it should have subfolders per game and top level common for all games

This will simplify the installer also - not an accident all those recent issues with game select etc

**Comment by Infernio** [comment] 2019-10-09 19:34
Should I keep the commit above for 307, or toss it entirely in preference of (eventual) profiles?

**Comment by Utumno** [comment] 2019-10-09 19:46
Keep it I would say and we can close this in favor of 250

**Closed** 2019-10-11 23:54 UTC
Labels: bug
