### ISSUE TITLE
Optionally skip instead of ignoring Skyrim .BSL

### ISSUE THREAD

**Issue by alt3rn1ty** [wrye-bash/wrye-bash#217] opened 2015-06-13 22:06 UTC
See post #103 http://forums.bethsoft.com/topic/1518379-wrye-bash-thread-103/page-5#entry24035658

.. And follow up posts

When uninstalling BAINs, which installed mod associated .bsl files - For example

UnOfficial Skyrim Patch.esp
UnOfficial Skyrim Patch.bsa
UnOfficial Skyrim Patch.bsl

The .bsl file will be left behind in Data

**Comment by Arthmoor** [comment] 2015-06-13 22:15
Strange that it would not remove something it installed itself. Is it only ignoring the .bsl files when uninstalling?

**Comment by Utumno** [comment] 2015-06-13 22:16
The strange think is that my medications are still just coffee

**Comment by alt3rn1ty** [comment] 2015-06-13 23:29
Yep ( so far as I have seen with the latest Utumno builds in the second post on the Oblivion topic )

**Comment by Utumno** [comment] 2015-06-14 00:02
Answer: they were meant to be skipped: https://github.com/wrye-bash/wrye-bash/blob/b347c073542075b76481427eb2459b777cb052e2/Mopy/bash/bosh.py#L5811-L5813
but somehow they are not - so what should I do with them ?

**Comment by Arthmoor** [comment] 2015-06-14 00:17
If that skip thing is why they're not being uninstalled, I'd say just remove that change in the code. Then BAIN will uninstall them like it should be. Assuming it's not actually easier to make BAIN skip installing them, which is what I assume was being attempted there.

The files are not 100% useless. Anyone wanting to extract a BSA with archive.exe needs that .bsl file or it won't work.

**Comment by Utumno** [comment] 2015-06-14 00:43
Well this should prevent the files being installed - or not, I have to dig in there and it's a dump place full of spiders and worms. Will remove this but may have unforeseen consequences - so just test it. Once I am back to BAIN will just go and debug and try to figure out what was intended to happen and why it doesn't - people that wrote that code should have commented it a bit, :sigh:

**Comment by Utumno** [comment] 2015-06-14 01:00
Lojack introduced this in this commit btw: e4e241a093150b9a1cda5df67bea60afee84a4bf

**Comment by alt3rn1ty** [comment] 2015-06-14 01:13
That cannot be working as intended, the only way I install is via BAIN

Looks like it is supposed to prevent them installing in the first place, but that was probably way back when we did not know if they could be useful for mod authors


I would say .bsl ought not to be among the .exe group of denied to install files.

Maybe it could at a future time be on the Installer Header Bar right click menu as a Skyrim Skip option and selected by default for most users, where mod authors would deselect it so that they do install.

But for now allow them to be installed / uninstalled. They do no harm being installed.

**Comment by Arthmoor** [comment] 2015-06-14 01:26
If that list is intended to be used as a security blocklist (which it looks like to me) then .bsl is out of place there since they're valid files for the archive generator.

If that's supposed to be an extension of the "skip these" menu that's in the UI, then maybe a new setting or something will fix that. Obviously a thought for a later version though.

For now, that commit should be reversed.

**Comment by Sharlikran** [comment] 2015-06-14 04:11
I use BAIN for Skyrim and it does not install .bsl files.  I also added .manifest files as well since those are for Curse.  The routine is intended to skip them meaning that when you install the mod BAIN skips the file and doesn't install it.  I don't have any issues with the current dev branch as of 47d21bfd632ef6afc012186cddffc6fd33ffa140.

**Comment by Utumno** [comment] 2015-06-14 04:14
@Sharlikran - can you test if they are installed with my current HEAD - if yes then the skip stuff was working before and I broke it and I would like to know this - I did rewrite parts of install/uninstal/anneal

**Comment by Sharlikran** [comment] 2015-06-14 04:32
Utumno, please make sure the files in skipExts are skipped on install.  I will test your latest changes to 306.201506132055 in a few minutes and see if any of your changes have altered the intended behavior.

**Comment by Sharlikran** [comment] 2015-06-14 04:47
![image](https://cloud.githubusercontent.com/assets/1912426/8147176/ca27b7c0-1215-11e5-88cf-b98549bfd3f0.png)

306.201506132055 does not change behavior, the files are still skipped as intended.

**Comment by Sharlikran** [comment] 2015-06-14 05:27
Alt3rn1ty, there are also updated links for both my Skyrim patcher updates and 306.201506132055 that does not have the Skyrim and Fallout updates in my WIP thread if you want to use either of those versions.

**Comment by Utumno** [comment] 2015-06-14 07:16
Great - thanks Sharl that would make me go chasing phantoms - @alt3rn1ty - so were those installed outside of BAIN ?

Bottom line - do you want BAIN to be able to install (and therefore uninstall) bsl files or not ?

**Comment by alt3rn1ty** [comment] 2015-06-14 11:08
Yes particularly for mod authors, we need to allow them to be installed and uninstalled

I guess I must have had a rogue version of Wrye Bash along the way which did install them .. when it should not have been doing .. And ever since Wrye Bash has been leaving them alone because of the lojack commit
I just tried deleting them manually - And then Wrye Bash 132055 will no longer install them.

However for mod authors it is desireable to be able to install them.

So either there should be choice in doing that -

A. Like a "Skip .BSL files" option on the installers tab menu ( like Skip Docs / Skip LOD ect )
or
B. Just let them install and remove that commit from Lojack ( so long as uninstalling them afterwards also then works )

In fact in both A and B if it was me I would remove the commit from Lojack because .bsl files do not make sense to be among the denied group of files in case of malware ( I recognise that group of dot extensions from one of the Wrye Bash Pictorial Guide and remember the bunch of reason on the forum when discussing that screen ) ..

http://static-1.nexusmods.com/15/mods/101/images/35230-1-1343150328.png

.. See the last line at the bottom, "Anything except .exe .py ..."

**Comment by titaniachkt** [comment] 2015-06-14 13:11
Just installed a mod with a bsl file, so thought it would be good to mention in here for additional confirmation (or refutation as the case may be):

For all the 'Unofficial X Patch.esp files (skyrim, dawnguard, hearthfire, dragonborn), the .bsl files have been **ignored** by Wrye Bash

This applies to other mods as well (the only one currently installed with a bsl file is [Take Notes - Journal of the Dragonborn] (http://www.nexusmods.com/skyrim/mods/48375))

Will provide screenshots if needed 

---
WB version: 305 standalone
OS: win7, full control enabled for file permissions in all relevant directories (C:\Steam\*)

BAIN 'Installers' options enabled (right click, context menu):
* avoid at startup
* enabled
* auto-anneal
* auto-anneal/install wizards
* auto-refresh projects
* skip bethsoft content
* auto-apply embedded BCFs
* clean data directory
* show inactive conflicts
* show lower conflicts
* show bsa conflicts
* wizard icon overlay
* skip screenshots
* skip docs
* auto-name string translation files 

BAIN 'Installers' options **not** enabled:
* Everything above and including 'Clean Data', 
* Skip SKSE/Script Dragon Plugins
* Skip Images
* skip DistandLOD
* Skip LOD Meshes
* Skip LOD Textures
* Skip LOD Normals

**Comment by alt3rn1ty** [comment] 2015-06-14 14:37
@Sharlikran 

I occasionally do have a look at your branch, but as Arthmoor says here ..
http://forums.bethsoft.com/topic/1509287-wipz-wrye-bashexp-skyrim-patcher-update-thread-2/page-5#entry23952459

.. Anyone who is anyone who can help at the level you need to ensure the patchers are working - Already have

I couldn't contribute anything confidently and competently on the patchers side of testing - Hence why I am just devoting attention to Utumno's refactored code and doing what I can to test the basic functionality of Wrye Bash

Anything that would be a combined problem between your updates AND Utumnos updates for me would just confuse the picture of testing Utumno's fixes, so that is why I am just using Utumno's rebuilds

Unfortunately there are not many people on the Skyrim side with enough knowledge that are actually participating from what I have seen, theres a bunch of capable people on the STEP forum, but they are mostly MO users and probably have not realised how much we still desire a fully functional set of patchers for Skyrim - Its a circumstance I recognise, but dont have the knowledge to help ( as previously mentioned back in post #2 of your Skyrim topic )

**Comment by Utumno** [comment] 2015-06-14 16:54
@titaniachkt thanks - no need for screens, we are the text crowd :)

Just waiting for feedback from Sharl then will probably revert this commit for 306

Re: skyrim patchers -  discuss in #151 please.

**Comment by Sharlikran** [comment] 2015-06-14 17:28
I'm with my wife at the store. I have an idea I'll pm you a little later.

**Comment by Utumno** [comment] 2015-06-21 14:41
Added optional global skip - please test

Actually this whole skip business needs a good facelift but this is 307+

**Comment by alt3rn1ty** [comment] 2015-06-22 06:34
The global skip option working well in the latest dev code :+1: 

See the following post http://forums.bethsoft.com/topic/1518379-wrye-bash-thread-103/page-6#entry24082154

Happy to close this issue

**Comment by Utumno** [comment] 2015-06-22 16:01
@alt3rn1ty hey thanks for confirming :)

For the future - please let me handle closing issues - I prefer to close them from commit messages (neater).

**Comment by alt3rn1ty** [comment] 2015-06-23 10:37
I understand

**Closed** 2015-07-17 13:49 UTC
Labels: enhancement, skyrim

**Comment by Utumno** [comment] 2015-09-15 18:47
Btw there was an issue on this: #28
