### ISSUE TITLE
Master list fixups and enhancements

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#192] opened 2015-02-07 17:34 UTC
__EDIT(Utumno):__ I split this into two issues - reserved this one for master lists updates and fixes and carried the original cosaves issue reported by @Sharlikran in #236.

__OP:__

On the saves tab you can assign a new master to the header of a save file.  For example Someplugin.esp might have an update to SomepluginV2.esp.  `class CoSaves:` seems to be using bush.game.se.shortName but `class ObseFile:` does not seem to do so.

Under `with sio(buff) as ins:` there is a line `if self.signature != 'OBSE':` that should probably be using `bush.game.se.shortName` which would be an easy change.  However, under `def save(self,path=None,mtime=0):` it uses `buff.write('OBSE')`.  Which is also an easy change.

Behavior without changes:

Wrye Bash errors in `def load(self):` for line `if self.signature != 'OBSE':`.

NOTE: You have to click the save button twice and the change is not reflected until you click in the box again.  Which then Wrye Bash auto updates the window with the new file name.  After which you have to save it again.

Behavior with minor changes:

Wrye Bash no longer has an error in the trace log.  However, when comparing the .ess and .skse files only the .ess files list of master files are updated.  The .skse file is untouched.

Expected behavior:

Both the .ess and .skse files should be updated to reflect the changes in file names for the save game headers.  You should only have to click the box once and the change in the file name should be reflected the first time rather then having to repeat the process.

**Comment by Utumno** [comment] 2015-02-07 17:39
Post also the traceback please - thanks for looking into the code

**Comment by Sharlikran** [comment] 2015-02-07 17:50
```Auto
Traceback (most recent call last):
  File "bash\basher\__init__.py", line 2437, in DoSave
    saveInfo.header.writeMasters(saveInfo.getPath())
  File "bash\bosh.py", line 1120, in writeMasters
    obse.load()
  File "bash\bosh.py", line 978, in load
    raise FileError(self.name,u'File signature != "OBSE"')
bash.bolt.FileError: Save 1705 - Lilly  Skyrim  00.27.52.skse: File signature != "OBSE"
```

Also on a side note.  Where is the file that keeps track of the names of the plugin files used with the save game headers.  For example, if I change Someplugin.esp to SomepluginV2.esp, then each save file I click on from that point forward will be changed automatically.  After I am done testing i kinda want to reset that file.

**Comment by Utumno** [comment] 2015-02-07 19:19
Did not get into this part of the code yet - it may modify the save file itself ? Otherwise some .dat file. Will keep you posted here once I get round to it

**Comment by Utumno** [comment] 2015-02-15 01:32
You mean when I click on a master name or when I right click > Change to ?

>  For example, if I change Someplugin.esp to SomepluginV2.esp, then each save file I click on from that point forward will be changed automatically. After I am done testing I kinda want to reset that file.

Can't reproduce this

I can the rest - plus is Load order listed for the save masters correct ?

Testing on 305

Oblivion: no exception but the .obse is not updated anyway I can see (?!)

**Comment by Utumno** [comment] 2015-02-15 02:18
The info is stored in BashSettings.dat - `'bash.mods.renames'` - well the logic of the whole thing is a bit twisted.

@Arthmoor is the .OBSE cosave edited in Oblivion when you use right click > Change to... in saves master list ? When clicking directly on a master and edit its label ? Should those two behave the same ?

Most importantly is Current LO column correct ?

How is this supposed to work after all ? How are renames reset ?

**Comment by Arthmoor** [comment] 2015-02-15 03:18
Sorry, I don't really know much of anything about how the saves tab should work, or what the OBSE/SKSE cosave files expect to happen.

**Comment by Sharlikran** [comment] 2015-02-15 03:22
What happens is that when you change the name of the plugin in the file header for the saves file it also updates the OBSE or SKSE co save header as well.

**Comment by Utumno** [comment] 2015-02-15 03:48
@Sharlikran: Quick testing in oblivion in 305 suggests that not - needs verifying. Quick test as in opening the .OBSE file and searching for the new master.

Do not see an easy way to reset renames

How you change the the name of the plugin ? Using right click > Change to or editing the label directly ?

**Comment by Sharlikran** [comment] 2015-02-15 04:04
To change the name of the plugin you right click, then choose Change To and then you are given the list of plugins in the Data folder.  You choose the file and then WB will use that fine name instead. 

These are face plugin names.  For example say the original plugin is RealWaters.esp.  There are now two new versions (again just ana example) RealWatersContinued, or ReadWatersV2.esp.  The feature allows you to assign one of the new file names to the save file instead of the old file name.

**Comment by Utumno** [comment] 2015-02-15 04:41
If you select a master and then click on it it allows you to rename it - this rename should have the same effect as right click, then choose Change To ?

Is the Current LO column correct ? In oblivion it displays I don't know what as LO numbers (I have some saves with huge masters lists that miss most of their masters)

In oblivion editing the masters list does not update the cosave file in any way (searching for the new master in the cosave does not turn up anything) - quick tests

Even if oblivion works (does edit the file or I fix it to) is really Obse class Skse ready ?

**Comment by Utumno** [comment] 2015-02-16 00:28
Well things are as you say plus in 305 _Change to_ leaves the old masters inside the `.obse` cosave - tested with notepad++. So this may prove a very insidious bug - or I am forgetting something ?

@Arthmoor please try to test (or ask around) if the OBSE cosaves are correctly edited when renaming saves masters.

To do so duplicate a save's master (a save with an obse cosave), edit the master save list - as described by Sharlikran - to rename the master to its duplicate and load the save with the duplicate master.
Or open the obse cosave with notepad++. I guess  that the cosave should contain the duplicate master's name - it does not on 305 and this may break things in an insidious way - IIUC.

Also I need to know if the Current LO values are correct in the master lists.

I can leave all this to 307 but I happen to be in this area of the code.

Will try and fix the interface bugs though and the `if self.signature != 'OBSE':`.

**Comment by Utumno** [comment] 2015-02-16 01:58
Ok - dunno what this means but the line that prevents the masters being edited in the OBSE case is no less than [`if opcodeBase == 0x2330:`](https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh.py#L1037) this comes from 3ac0142aa0096dc9f301e9a69c9b729e865315ee and stayed put since.

Still maybe the OBSE masterlist cosave needs not be edited - improbable

Also do not know how this code applies to SKSE if at all

I need info from someone who knows the code here - @lojack5 ?

I am tempted to just leave the exception in place

**Comment by Utumno** [comment] 2015-02-16 03:30
@Sharlikran any idea what the colors on the saves and mods master lists mean ?

**Comment by InsanePlumber** [comment] 2015-02-16 04:09
Wrye Bash Advanced Readme Save Tab description.
http://tesfans.org/guides/wrye%20bash/docs/Wrye%20Bash%20Advanced%20Readme.html#saves

**Comment by Sharlikran** [comment] 2015-02-16 04:32
![image](https://cloud.githubusercontent.com/assets/1912426/6207208/bee238c0-b551-11e4-8d66-e368c239aab8.png)

**Comment by Sharlikran** [comment] 2015-02-16 04:35
Mods Tab:
![image](https://cloud.githubusercontent.com/assets/1912426/6207241/3de6bb82-b552-11e4-8861-ae46fde86c91.png)

**Comment by Sharlikran** [comment] 2015-02-16 04:42
I can't think of a tactful and respectful way to say this, I'm not trying to be defiant or rude.  Be sure to check the documentation to verify functionality, intent of the tab, colors, and that sort of thing.  I don't suggest that to be disrespectful, I suggest it so you have accurate information from the previous programmers like @lojack5 and @PacificMorrowind.  Then you can better evaluate how to fix a bug or update a routine.

I feel this is the best approach so there aren't accidental changes to Wrye Bash's functionality.  People have come to expect it to do certain things for them.  While you are doing such good work to make it a maintainable and sustainable application, I hope referring to the documentation will keep it from loosing functionality people feel is vital to the way they mod their games.

> Even if oblivion works (does edit the file or I fix it to) is really Obse class Skse ready ?

If you can make Wrye Bash attempt to alter the obse and skse cosaves, I can update the definition.  @Hugues92 has already informed me that he has the cosaves file header information in xEdit.

**Comment by Utumno** [comment] 2015-02-16 12:59
Dear @Sharlikran the colors on the MASTERS lists not on the saves or mods themselves - plus your last post was on _installers_ - I would delete those if I were you.

Please understand that I am technical and 99% when I ask something it's not in the docs OR in the code.

**Comment by Utumno** [comment] 2015-02-16 13:18
See also #27 and the linked SVN bug I had reported http://sourceforge.net/p/oblivionworks/enhancements/249/ and links there.

**Comment by Sharlikran** [comment] 2015-02-16 17:20
> Dear @Sharlikran the colors on the MASTERS lists not on the saves or mods themselves - plus your last post was on installers - I would delete those if I were you.

You are correct, done.  @Utumno I have updated the response.

**Comment by Utumno** [comment] 2015-02-16 17:40
You are a awesome !
I agree about purple.
Please have a look into #27 and http://sourceforge.net/p/oblivionworks/enhancements/249/ and links there and update your post if needed - will go through your post in detail later this evening.

Please also edit your post (if you haven't already) with info on merged/imported mods (the ones with dots and crosses) - how those should affect the master list colors, and the save status.

Please note that the whole think is complicated by masters having other masters - some thought must go there too - and may explain some not expected behavior ? 

Time to fix this mess - docs included

**Comment by crazykilla15** [comment] 2015-02-16 18:13
Any work being done here will also be helpful for my python 3 port.

i DO want to keep the code in line with the current dev code.

**Comment by Sharlikran** [comment] 2015-02-16 22:44
> merged/imported mods (the ones with dots and crosses)

The Bash Patch does not include inactive, merged, or imported plugin in the header of the Bash Patch because they are inactive.  All the records for Merged or Imported plugins end up in the Bash Patch and thus have the same Current LO as the Bash Patch.  The records usually reference an active master.  This is consistent with the rule that plugins can't be merged if they introduce new records.

**Comment by Utumno** [comment] 2015-02-17 00:31
@Sharlikran I am neck deep in sorting so will look into it in detail later on. Will try to push to my branch a fix for #27 hopefully till tomorrow.

Thanks again for your support at this time of trolling.

**Comment by Utumno** [comment] 2015-02-23 14:43
TODOs:

- [ ] Bash tags should not be copied to description if this causes it to overflow (see #187)
- [ ] the UI must be reworked so that:
  - [ ] save and cancel are enabled _only_ when the user actually edited the masters
  - [ ] you do not need to click two times to refresh
- [ ] 'bash.mods.renames' should be exposed to the user - at least clearing them should be possible
- [ ] The info from this issue should be added to the readme
- [ ] squash the bugs in the LO display and status display
- [ ] and of course what this bug is about - cosaves are NOT edited in Oblivion (please confirm) or Skyrim
  - [ ] Add big fat warning for 306
  - [ ] SKSE class for 307
  - [ ] OBSE class patch to work with  [`if opcodeBase == 0x2330:`](https://github.com/wrye-bash/wrye-bash/blob/dev/Mopy/bash/bosh.py#L1037) - whatever this means

@Sharlikran : am I forgetting anything ? Here is your cosaves branch: https://github.com/wrye-bash/wrye-bash/tree/sharlikran-cosaves

I take this opportunity to ask you again to set up two factor authentication - please do

**Comment by Utumno** [comment] 2015-02-25 04:47
@Sharlikran just pushed a fix for LO display - plus enabled (and cleanup up) sorting in masters lists. Would this fix the 'this is a bug' in your post above ?

**Comment by Sharlikran** [comment] 2015-02-27 16:33
> Would this fix the 'this is a bug' in your post above ?

As of https://github.com/Sharlikran/wrye-bash/commit/8b19bc8e1e5a7bab28f166d1ffcd060104cb70bb the Current LO column looks much better.  The Hex value matches the Mods tab as it should.  The colors also seem to be working correctly.  For example 4 mods with a slightly different order make a brief section of orange.
![image](https://cloud.githubusercontent.com/assets/1912426/6416439/0f5a4b5a-be5b-11e4-80c7-aa6da3f74ab6.png)

While further down a newly added plugin causes some files to show a green checkbox because the addition of the plugin is a safe addition and should easily be handled by Skyrim's game engine.
![image](https://cloud.githubusercontent.com/assets/1912426/6416473/4812d336-be5b-11e4-9e4c-0b4161bb572d.png)

**Comment by Utumno** [comment] 2015-02-27 17:13
Thanks for confirming this sharl :)

**Comment by Utumno** [comment] 2015-06-02 15:16
@alt3rn1ty , @Sharlikran can any of you submit me a patched version of the readme including the info on the masters lists from Sharl's post in this issue ? Since MI confuses even old users...

No need to put all the info, just condensed, but add some screens too maybe

Just edit the readme and post me a link here

**Comment by alt3rn1ty** [comment] 2015-06-07 20:34
Well out of this issue, all I can figure which needs adding to the Wrye Bash Advanced html is the addition of MI and Current LO to the explanation boxouts for the Mods and Saves tabs - Masters List sections ..

http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#mods-details

http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#saves-overview

The above now read as in the following screenshots

http://i.imgur.com/7tA7sZj.jpg

http://i.imgur.com/f6hNoS6.jpg

Edited file is in my DropBox - https://dl.dropboxusercontent.com/u/86040572/Wrye%20Bash%20Advanced%20Readme.7z

**Comment by Utumno** [comment] 2015-06-13 19:11
@alt3rn1ty: excellent thanks ! Somehow I was not notified of your post (?!)

If you see post above by @Sharlikran (What the Masters Mean for Both the Mods Tab and the Saves Tab) there is a lot of info about the colors in the masters lists - I would like to have this in the readme too - someone posted a link to somewhere in http://wryemusings.com/Wrye Bash.html which I can't find anymore

Anyway every little bit helps - btw someone else opened an issue on the readme here: #215 - so if you could go through that too would be great

**Comment by alt3rn1ty** [comment] 2015-06-13 21:20
From the current ReadMe's

General ReadMe
----------------------

What Symbols & Colours mean - Installers Tab
http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#bain-symbols

What Symbols & Colours mean - Mods Tab
http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#load-symbols

What Symbols & Colours mean - INI Edits Tab
http://wrye-bash.github.io/docs/Wrye%20Bash%20General%20Readme.html#ini-symbols

Advanced ReadMe
------------------------

What Symbols & Colours mean - Saves Tab
http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#saves-symbols

What Symbols & Colours mean - People Tab
http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#people-symbols


The images are not linking correctly ( as in the other issue with image problems ), but I do not know how to resolve github problems and linking

**Comment by Utumno** [comment] 2015-06-13 21:30
Yes yes :sigh: - the colors on the _masters_ lists, Sharlikran  had made the same mistake - trust me I read the readme ;)

Btw now that comes to this I have no clue why those are split in those two readmes - the original readme had bits and pieces of info that went missing

**Comment by alt3rn1ty** [comment] 2015-06-13 21:40
Wrinkly condensed it all and split it for easier reading, part of the objective being to get away from its traditional wall of text which daunted the hardiest of readme readers

**Comment by Sharlikran** [comment] 2015-06-13 21:42
It's not perfect but I have had the [links updated](http://sharlikran.github.io/wrye-bash.github.io/) for a while.  I just haven't does anything to the main page so there are only links to the readme files.  I don't have time to update it right now but I will try to add some of the suggestions later.

**Comment by Utumno** [comment] 2015-06-13 21:54
@Sharlikran oh please do -  we would be almost doing the job two times - see #215 
I see the images work in your repo too - how did you do that ?

@alt3rn1ty I know, I mean why the images are explained part in the general part in the advanced readme...

Splitting is alright - condensing - no. Should go to the advanced one

**Comment by Utumno** [comment] 2015-06-21 16:47
@Sharlikran: deleted the cosaves branch - did not serve any purpose - is still the volunteer around ?

**Comment by Utumno** [comment] 2015-09-06 19:26
@Sharlikran: I am very pleased to announce that I squashed the rest of the bugs you reported - and added two more menu items - one to allow/disallow editing the masters list and one to clear the renames dictionary. The UI reflects user actions - and as an extra bonus renamed items display __bolded__.

The cosaves are still not edited as this is highly technical - but the masters list is now a _decent_ piece of code - decent enough for master. I added a big fat warning on the saves tab and that's all for 306.

It was a _dictionary definition of a Can of Worms_ - by the gods of programming, monkey or otherwise.

Remains to edit the Readme on renames (add the new menu items and say a couple words about the UI - "Bolded items are renamed inside Bash internal dictionaries - on allowing edit or clicking on the masterlist (if editing is allowed) the renamed items take their renamed names - you can save the mod/save by clicking on the Save button) - if you could do this for me it would be grand - if not at least please test the changes.

Thanks (and hope you are getting better).

**Closed** 2015-09-12 00:11 UTC
Labels: enhancement
