### ISSUE TITLE
Bodyslide/Calientetools directories not being installed

### ISSUE THREAD

**Issue by toynbeeidea** [wrye-bash/wrye-bash#379] opened 2017-07-03 01:45 UTC
Archives of Bodyslide files are not being installed.  307b1 does not even list the files in Calientetools, even if "extra directories" and "override skips" are checked.  These files are not binaries of any kind, so there is no good reason they shouldn't be installed.

Wrye Bash will mostly install the Calientetools directory if it is bundled with other files, however, but this means we have to manually repackage everything in a lot of cases.

**Comment by Sharlikran** [comment] 2017-07-03 17:32
This is a duplicate #363 and should be marked as you choose Utumno. You could mark it as a duplicate, not a bug, doesn't need fixing, or whatever.

My post about Issue 363 is still visible on the [Bethesda Forums](http://forums.bethsoft.com/topic/1615914-wrye-bash-thread-114/page-2#entry25313410).

Wrye Bash will not install to the root game folder.  For example the Skyrim.exe is normally in [some drive and path]\SteamApps\common\Skyrim and Wrye Bash doesn't install to that folder period no exceptions.

Wrye Bash will install Script Extender files but with a warning for each and every single file. So if you have a mod that has two plugins for SKSE then you will be prompted twice prior to installing the DLL files that the author has provided for use with SKSE.

The original authors decided long ago to never install EXE files under any circumstances as a security measure.  Things like Bodyslide, FNIS, TES5Edit, LOOT, and so on can't be installed by Wrye Bash no matter how you make the zip/rar/7Zip file.

Wrye Bash only installs to valid game folders for the game you are using Wrye Bash with.  These are the same folders you would find in the official Bethesda archives such as a BSA or BA2 file and the folders are always in the Data folder.

For Fallout 4 you have a folder named materials and it is only for Fallout 4. If you someone tried to install a Fallout 4 mod into the Skyrim Data folder, none of the files in the path .\Data\materials would be installed because it's an invalid folder for Skyrim.

![skyrimfolders](https://user-images.githubusercontent.com/1912426/27802704-5a7305dc-5fda-11e7-9aa0-5859fdbd6748.jpg)

The above image is only the Skyrim BSA files. There are other valid folders not shown that appear in other official Archives or folders that are created by the Skyrim CK.  Valid Skyrim folder are: dialogueviews, interface, meshes, strings, textures, video, lodsettings, grass, scripts, shadersfx, music, sound, and seq.  If the folder is any other folder it will not install with Wrye Bash and this is intended.

**Comment by Utumno** [comment] 2017-07-03 17:58
Thanks @Sharlikran - @toynbeeidea you must read the contributing.md file before filling a bug - or the reporting a bug wiki page - especially the part marked as IMPORTANT

**Comment by m0lz** [comment] 2017-07-04 13:13
@toynbeeidea See also the Advanced ReadMe, Skipped files section

http://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#bain-skipped

**Comment by Utumno** [comment] 2017-07-16 13:29
I decided I can enable installation on those directories - Bodyslides tools dir is already supported in the utumno-wip branch - please test and give me more info as needed

**Comment by BeermotorWB** [comment] 2017-07-16 14:23
In the 307.201707160231build the BodySlide directories for Fallout 4 work properly. The Skyrim versions are in a different data directory however.
FO4 
`data/tools/caliente tools/`

Skyrim and SSE:
`data/caliente tools/`

See [this forum post ](https://afkmods.iguanadons.net/index.php?/topic/4966-wrye-bash-all-games/&do=findComment&comment=167473)for a link to the package for example data.

**Comment by BeermotorWB** [comment] 2017-07-23 10:42
Update 7/23/2017
307.20170223WIP build (and the previous dropbox release) are still ignoring the "Caliente Tools" folder. 

Fortuitously someone has released Bodyslide-oriented mod recently which is in a simple BAIN format:  [UUNP Vanilla Outfits Bodyslides SE](www.nexusmods.com/skyrimspecialedition/mods/10980/?) by Shiva 182. 

This has the folder structure as it should be in-situ (in the Skyrim/SSE data folder) so this is fairly perfect for testing.

**Comment by BeermotorWB** [comment] 2017-07-23 21:26
Update on the Skyrim Caliente Tools issue:  I was incorrect on the Skyrim path, so WB is working just fine, it is a Beermotor's Eyes Bug.   My sincere apologies.

For Skyrim the path is actually `/data/CalienteTools/BodySlide/`   

Note the lack of a space between "Caliente" and "Tools".  

The Fallout 4 paths are working perfectly.

**Comment by Utumno** [comment] 2017-07-23 21:32
Both skyrim and skyrim SE ?

**Comment by BeermotorWB** [comment] 2017-07-24 10:10
Yes this is for both Skyrim and Skyrim SE.

**Comment by BeermotorWB** [comment] 2017-07-24 20:20
I can confirm this issue is resolve in WIP 20170723

**Comment by Utumno** [comment] 2017-07-25 01:49
Thanks @BeermotorWB. Your guide:

http://imgur.com/a/qsE6q

Are you familiar with github wikis ?

**Comment by BeermotorWB** [comment] 2017-07-25 10:56
Of course, `Markdown` is like a second language to me.  ;)

In all seriousness though I'll be glad to port it over to the wiki. I want to get a little feedback on it in regard to grammar and content before I publish it. 

Speaking of the wiki

**Comment by Utumno** [comment] 2017-07-25 23:53
I had a casual look but not my area of expertise. Hard part with wiki is pushing images - you need to clone the wiki repo and add the images in images/ folder then edit on your computer and push

**Comment by BeermotorWB** [comment] 2017-07-26 12:41
No worries, I've already cloned the [main project wiki.](https://github.com/wrye-bash/wrye-bash/wiki), and there's not a different one for end-user documentation, right? 

I plan on adding a new section called "Docs" or "End-User Docs" or something of that nature to make it easier for casual browsers to find.  If there are no objections to that I'll proceed.

**Comment by Utumno** [comment] 2017-07-26 13:15
It has no sections unfortunately - just add [Guide] to the title (we have [dev], [git] etc)

**Comment by BeermotorWB** [comment] 2017-07-29 00:31
@Utumno Done. Cloned, branched (BeermotorWB-wiki-guides), but I can't push.  I could be doing this all wrong or I'm forgetting something, or I just don't have permissions. :) I think it is probably a combination of the three.

**Comment by Utumno** [comment] 2017-07-30 12:04
Link me to the repo :D

**Comment by BeermotorWB** [comment] 2017-07-31 13:27
Disclaimer -  I suck at github:   https://github.com/BeermotorWB/wrye-bash/wiki

**Comment by Utumno** [comment] 2017-08-02 15:30
Thanks @BeermotorWB - this is however on your fork. Please clone the wiki from this organization then try to push your changes there - clone url:

    git clone https://github.com/wrye-bash/wrye-bash.wiki.git

**Comment by BeermotorWB** [comment] 2017-08-04 10:33
I think that's where I ran into issues earlier. I did exactly that and when I tried to push the change it gave me a permissions error. I'll give it another go from the cli since it may produce a more helpful error.

**Comment by Utumno** [comment] 2017-08-15 13:38
Hey sorry for late reply - will try to give you permissions - not as trivial as it seems - I added you as a collaborator, but maybe an ssh issue (define ssh keys ?)

**Comment by BeermotorWB** [comment] 2017-08-23 10:18
Sorry for my late reply back.  It wouldn't surprise me a bit if they locked git pushes to only allow key-based auth, that's actually fairly standard.   Give me a bit and I'll see what I can do. :)

**Comment by pipboycolor** [comment] 2017-08-23 13:51
> Now open your game folder and navigate to the Data folder. You will need to drill down from there to find where BodySlide lives. 

> Once you arrive at your BodySlide folder, it should look similar to the above with no exe files present. Leave the window open and Alt-Tab back to your archive manager. 

> Drag and drop the BodySlide executables into the BodySlide folder.

Just tested this:

One problem with installing the executables to `Data\Tools\BodySlide` is that they get wiped every time you run Clean Data.

A better suggestion would be to copy the `*.exe` files to a location outside of Data, and create a Shortcut with a "Start In" property that points to `...\steamapps\common\Fallout 4\Data\Tools\BodySlide`. 

As a bonus, you can suggest that users to place their new shortcut in `mopy\Apps` so that it's available as a custom launcher.  That way it's a true "set up once and forget" style of installation.

I'm using this setup now, with Bodyslide x64.exe installed to `C:\BodySlide`, and it's working flawlessly.

**Comment by BeermotorWB** [comment] 2017-08-24 12:24
Thank you for sharing this. Yes that's true and the shortcut trick is a _great_ idea.  I'm actually going to do that for myself since I have my Bodyslide shortcut in ./Apps.

What I'll probably end up doing is adding a section at the bottom kind of like an addendum or appendix.  As with most of my other documentation I try to get my 10 year old to test it. If he doesn't need help with it, then I know it's good. 

Thanks again for that tip. That's great. :)

**Comment by BeermotorWB** [comment] 2017-08-24 14:25
@Utumno I'm still having issues, namely due to the fact that I have git set up for my work SSH key and the ssh-agent on MacOS isn't recognizing either the Github hostname, the remote path in git, or some combination of the two.

I deleted my fork and a few minutes later found [this guide](https://gist.github.com/larrybotha/10650410) that shows how to squash changes from a forked repo back into the master.  I'll give it a whirl to see what kind of movement I can make on it.

**Comment by BeermotorWB** [comment] 2017-08-30 12:59
Update: the Bodyslide guide has been updated. 

@pipboycolor  I'm going to update it with your technique tonight when I get home since I'm on my Mac right now. Thanks again for sharing that.

**Comment by BeermotorWB** [comment] 2017-09-06 00:02
Update: I've got the screenshots and text written for the Bodyslide update, but ran out of time before I could complete the documentation. Will update tomorrow.

**Comment by BeermotorWB** [comment] 2017-09-06 20:37
The last BodySlide guide update has been pushed with the shortcut trick courtesy of @pipboycolor  :)

**Closed** 2017-09-07 12:54 UTC
Labels: bain, enhancement

**Comment by Gavvers** [comment] 2017-12-20 03:52
Was this feature included in the latest version?

I am using the installer version 'Wrye Bash 307 beta1 - Installer-20032-307' and it does not recognize the Tools directories in mod archives. For BodySlide, it lists the structure as unrecognized, and in other mods that have Tools directory in a sub-package, the sub-package is not listed and nothing is shown in the skipped section.

**Comment by Utumno** [comment] 2017-12-20 10:11
The bugs marked as fixed are fixed in the dev branch here
