### ISSUE TITLE
Edit translatable strings for easier translation.

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#55] opened 2014-02-25 05:16 UTC
This is in relation to [Unicode Guidelines](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-Unicode-Guidelines):

Go through all translatable strings and update them to:
- [x] Remove wtxt formatting
- [x] Remove newline characters
- [x] Remove leading and trailing whitespace
- [x] Change formatting specifiers `%s` into `%(name)s` ones

Blockers:
 - [x] #460

Useful resources:
 - Tracking regex for `%s` vs `%(name)s` etc.: `_\(\s*u?['"][^%)]*%[^( ]`
 - Tracking regex for `%s` vs `f{}` and `%(name)s` etc. `%[^( ]`

**Comment by Utumno** [comment] 2015-01-16 20:16
Most of it is done - `_\(u'([^%)]*)([%].)'\)` gives 31 matches. Putting it in the back burner for now. Keep in mind that causes dust (translations break). Let's wait till the dust settles from basher refactoring also (new help items from menus etc).

**Comment by Utumno** [comment] 2015-01-18 13:52
Now that I come to think about it this must be carried out - changing the strings little by little would break translations every time so it's to be done once and for all - putting this under 307 but I don't open it yet to avoid seeing it first thing in the tracker.

**Comment by Utumno** [comment] 2019-09-15 14:47
Once we move to python3 we should use f-strings - this will need recreating the translations but will get us rid of the issues here - closing for good

**Comment by Infernio** [comment] 2020-04-17 01:02
So I just now realized that f-strings don't work with gettext, [by design](https://bugs.python.org/issue33189). The substitution is done before the string goes to gettext, so f-strings straight up can't be used with it :(

**Comment by Utumno** [comment] 2020-04-18 11:21
> So I just now realized that f-strings don't work with gettext, by design. 

That's bad I was afraid so. Well one of the first things I wanted to do on py3 was use f-strings _everywhere_

Let's see - I mean we should probably stay with the dict approach then

**Comment by Infernio** [comment] 2020-04-18 11:24
Yeah, probably use

```python
_(u'Open the selected %(file_type)s for editing') % {u'file_type': sel_file_type}
```

for translatable, user-facing strings. We can still use f-strings for non-translatable internal stuff I guess?

**Comment by Utumno** [comment] 2020-04-18 11:27
> We can still use f-strings for non-translatable internal stuff I guess

Definitely! f-strings are one of the best py3 goodness

I would like to devise an algo to preserve translations however - I am particularly fond of the Chinese ones by bluesky

**Comment by Infernio** [comment] 2020-04-20 12:20
> I would like to devise an algo to preserve translations however

Do you mean an algorithm to keep translations for unchanged input strings around in the generated dump (which is something Dump Translator already does), or something like 'if the only difference between the two input strings is %s -> %(name_here)s, just make that change in the translation as well'?

**Comment by Utumno** [comment] 2020-04-20 12:34
>  'if the only difference between the two input strings is %s -> %(name_here)s, just make that change in the translation as well'?

This!

**Comment by Infernio** [comment] 2022-08-28 09:41
Unblocked since commit mentioned above, reopening.

**Closed** 2024-01-07 21:16 UTC
Labels: C-todo, A-l10n

**Comment by Utumno** [comment] 2024-01-08 00:15
Thanks Inf - will go ahead and rebase nightly
