### ISSUE TITLE
Names Patcher: Stop listing game master file as one of the files to process.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#328] opened 2016-10-02 22:25 UTC
A game's master file is showing up in the Names patcher for no apparent reason. This applies to all supported games right now. There is no reason it should be there as including it will cause it to then override everything down the line in the load order that doesn't also have its own Names tag.

No other patchers list the game's master file so Names really shouldn't be doing this either, especially since it's selected by default.

**Comment by Utumno** [comment] 2016-10-04 23:21
@Arthmoor: try latest utumno-wip - fixed although what worries me is that it was in there from initial commit
@Sharlikran: this makes `namesPatcherMaster` unneeded

**Comment by Sharlikran** [comment] 2016-10-05 00:52
Well let me explain it again because Wrye's patchers need to be consistent.  In addition to that the names patcher listed Oblivion.esm so if you remove that then the names patcher for oblivion be affected.

**Comment by Sharlikran** [comment] 2016-10-05 01:01
Also before I type my explanation, I changed it over two years ago in this commit https://github.com/Sharlikran/wrye-bash/commit/fec25d6a079c434fbb535b0b187f45ba0e929f67

**Comment by Sharlikran** [comment] 2016-10-05 01:28
So first I respect both of you.  Utumno knows Python and I don't.  Arthmoor has forgotten more about modding then I know most likely.  So I always try to be respectful toward both of you.  Yes sometimes I rant or cause some discontent when I am arguing a point but in the end how I feel toward the two of you never changes.  I would really appreciate it if the patcher was working correctly rather then remove namesPatcherMaster.

You both know that the winning mod with the winning bash tag wins.  You also know that when the winning record is already correct that it should not be written to the Bash Patch.  That part is already established and well documented throughout the community.  So the names patcher needs to function that way.  It should not be altered to work as desired but as intended.

Oblivion.esm or Skyrim.esm would be the only master.
ModA.esp Alters Names of all cells from English to German.  Bash Tags appropriate for name changes.
ModB.esp Alteres climate and weather. Bash Tags appropriate for climate and weather.
ModC.esp Alters the water height to create a drought. The mod author altered every river and body of water and created ponds to add a very intense level of realism.  Bash Tags appropriate for water height changes.

The patcher compares one value with another.  As mentioned this is done with long fid conversion.  So FormID 000145F3 is converted to ('Skyrim.esm', 0145F3) and so on for DLC and mods.  For ModA it will compare the FULL record for ('Skyrim.esm', 0145F3) and ('ModA.esp', 0145F3).  If there is a change and the appropriate bash tag it will keep that value to be written to the Bash Patch. 

ModB.esp and ModC.esp do not change the names.  So the comparison if it happens at all (because I don't know the code) would compare to ('Skyrim.esm', 0145F3) and ('ModB.esp', 0145F3) and see no change and no names bash tag.  Same with ModC.esp.

When the patcher for climate and weather runs the names are from vanilla Skyrim so the Patcher will keep only the climate and weather changes.

When the patcher for water height runs the drought mod will alter the water height but again doesn't alter names.

The end result is the names will be in German not English form ModA.esp, and the appropriate climate and weather changes from ModB.esp, and lastly a drought has effected the landscape giving the user exactly what they expected.  Without Wrye the user would only have a drought and no alteration to climate and weather and the names will be in English not German since ModC.esp is the winning mod by default.  Thus why Wrye was invented in the first place.

If any patcher, in this example the names patcher doesn't look at the masters in the plugins' header how will it know if there is a change or not?  Are you expecting Wrye to know what changed between (nil, nil) and ('ModA.esp', 0145F3) ?

I feel the bug should be the named Bug in Names Patcher for Skyrim.

**Comment by Arthmoor** [comment] 2016-10-05 01:43
The main reason I'm saying this behavior should not be the norm is because it didn't used to be a long time back. The game's master file has never been considered something that should assert its settings over the entire load order. That completely defeats the purpose of mods that intend to change names but have no reason to force that against other mods following it in the load order. This master file check as it currently stands is literally forcing all mods that change FULL records for any reason to tag themselves with Names in order to avoid getting clobbered by the master file.

No other patcher does this, so the behavior is also inconsistent and entirely unexpected. The master file is selected by default during patch build and most of the tutorial material out there tells people to go with the selected defaults. This will (and has, hence this report) lead to bashed patches with the wrong data included in them. It will cause unnecessary support issues for mod authors and quite likely for the Bash team as well.

So IMO, I still think this change needs to be reversed because it's inconsistent with the operation of the rest of the program's patch conditions. I am aware it would affect Oblivion as well, but that's expected, because for Oblivion this was never considered normal either.

**Comment by Sharlikran** [comment] 2016-10-05 01:48
In case you posted after I added the screen shot, please note that my screen shot is from 295.5 released in 2012.

**Comment by Sharlikran** [comment] 2016-10-05 02:08
Also before Utumno responds I'm not arguing the end result I'm arguing the programming behind it.  I think we have always agreed that the names patcher is writing values into the Bash Patch that should not be there.

What has always been ironic in regards to the names patcher is that the end result should work as you have explained Arthmoor, and it should follow my example.  I am pretty sure the two of you would agree that my example is valid.

The patcher doesn't work correctly and needs to be changed.  Once it is fixed, then you would leave Oblivion.esm or Skyrim.esm checked.  Mods that don't alter FULL records would no longer affect the Bash Patch and only mods that have the names bash tag and alter FULL records would be written to the bash patch.

**Comment by Utumno** [comment] 2016-10-05 10:06
> fixed although what worries me is that it was in there from initial commit

So yes it was there since forever. I do not completely grok the patcher code as I said before. @lojack5, @jfpelland may know more. Still from the little I understand if a mod is tagged with names the Bash patch should look at all the records with names and keep them. Then the bashed patch should look at all the mods and see what would be the winning record information _anyway_. If this differs it would keep the name otherwise discard it. So indeed the master esm does not need to be considered. Maybe it was added as a workaround for another bug ? Dunno

Fort the moment what you should do is test this branch. _Does it do the right thing ?_ If it does we go on without much explanation - till I get to the other name patcher bugs and I have a closer look. Which brings me to:

**The patcher needs _tests_.** 

I may finally get round to setting up a testing repository - I will need modders to commit mods in it. It will contain testing routines to test the individual patchers work right. As long as this is not set up the patcher can't be ever completely fixed, we will keep patching stuff and cross our fingers nothing broke someplace else. But that's _a lot_ of work. It should be old news by now, but I need developers.

----

Glad to see you back @Sharlikran. Just that. I am a slow typist, can't write volumes and I have a lot on my plate anyway. But I think your quitting the project was rather hasty.

**Comment by Sharlikran** [comment] 2016-10-05 16:04
The project is important and again regardless of how I present my opinions I appreciate the work you have done and I respect you for doing as much as you have.  That said I wouldn't say I'm back nor have I changed my mind about things.

I wasn't sure I wanted to respond but I feel the names patcher doesn't function as intended.  I feel Arthmoor has been right about all along that the Bash Patch contains changes that should not be there so it warrants commenting and making sure in the end the patcher functions as intended.

With the addition of a properly work LOOT API I will be enabling the Leveled List patcher for Fallout 4 and getting it up and running just no ETA on that.

**Comment by Utumno** [comment] 2016-11-04 22:48
@lojack5 - I am ready to merge this but do you happen to remember why we do include the game master here ? Seems unneeded as reported here but maybe we are missing something ?

**Closed** 2016-11-12 01:05 UTC
Labels: bug, patcher
