### ISSUE TITLE
Bashed Patch Failing and giving an error (Nexus release 306)

### ISSUE THREAD

**Issue by jatkinson85** [wrye-bash/wrye-bash#281] opened 2016-03-16 10:16 UTC
Using version 306 I'm getting this error when rebuilding the bashed patch:

[spoiler]
Traceback (most recent call last):
  File "bash\balt.pyo", line 1796, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 190, in Execute
  File "bash\cint.pyo", line 14257, in save
WindowsError: exception: access violation reading 0x1C6AC287
[/spoiler]

After some testing with my recently installed mods I found that it was happening when ZUAMOPatch.esp (http://www.nexusmods.com/oblivion/mods/44822/?)was present in my load order.  The plugin is mergeable and has the following BASH tags : 

=== Current Bash Tags:
[spoiler]
- ZUAMOPatch.esp
  - From Description: Actors.AIData, Actors.AIPackages, Actors.Spells, Actors.Stats, Delev, Factions, Invent, Names, Relations, Relev, Scripts, SpellStats, Stats
  - Result: Actors.AIData, Actors.AIPackages, Actors.Spells, Actors.Stats, Delev, Factions, Invent, Names, Relations, Relev, Scripts, SpellStats, Stats
    [/spoiler]

It appeared to throw the error at the point of assigning hairs and eyes close to the end of the process but I couldn't be sure.  Here is my current load order:

Active Mod Files:
[LoadOrder#281.txt](https://github.com/wrye-bash/wrye-bash/files/187009/LoadOrder.281.txt)
Utumno: attached the load order - local equivalent of spoiler tags

Is this a bug with Wrye Bash or the plugin (TES4Edit reports no errors)?

Artorius.

**Comment by jatkinson85** [comment] 2016-03-16 23:19
I've posted the report on github (username jatkinson85 there) but I've now found a new error after installing Better Cities version 6.06 and trying to rebuild the Bashed Patch.  The patch would break when it came to patching Item Interchange - Placement for FCOM,esp : CREA records.  (Item Interchange - Placement for FCOM.esp is from Cobl 1.74)  Removing that esp allows the bashed patch to complete properly.  Otherwise it produced this error:

Traceback (most recent call last):
  File "bash\balt.pyo", line 414, in <lambda>
  File "bash\balt.pyo", line 1574, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 193, in PatchExecute
  File "bash\patcher\patch_files.pyo", line 617, in buildPatch
  File "bash\patcher\patchers\importers.pyo", line 2137, in apply
  File "bash\cint.pyo", line 10662, in CopyAsOverride
WindowsError: exception: access violation reading 0x00000000

After much experimentation I found that the plugin that caused it to break at this point from Better Cities was Better Cities Resources.esm.  Even after removing all other Better Cities plugins except for Better Cities Resources.esm the bashed patch would break down when encountering Interchange - Placement for FCOM,esp : CREA.  Without Better Cities installed this plugin throws no issues when building the bashed patch.  This applies to versions 6.06, 6.05 and 5.53a versions of Better Cities Resources.esm.

I also tried updating to your latest standalone version of 307 (Nice colouration for markers and general speed improvements for heavy load orders by the way ;) ) but did not produce any different result, nor did deleting the old bashed patch and creating a new blank one to rebuild produce different results.

My current Load Order:

Active Mod Files:
[spoiler][xml]
00  Oblivion.esm
01  GTAesgaard_2.esm
02  All Natural Base.esm  [Version 1.36]
03  Francesco's Leveled Creatures-Items Mod.esm  [Version 5.0]
04  Francesco's Optional New Items Add-On.esm  [Version 5.0]
05  Cobl Main.esm  [Version 1.74]
06  Oscuro's_Oblivion_Overhaul.esm  [Version 1.37]
07  Mart's Monster Mod.esm  [Version 3.8b1]
08  TamrielTravellers.esm  [Version 1.39c]
09  FCOM_Convergence.esm  [Version 0.9.9MB8b1]
0A  Armamentarium.esm  [Version 1.35]
0B  Artifacts.esm  [Version 1.1]
0C  Better Cities Resources.esm  [Version 6.0.6]
0D  Fundament.esm  [Version ision]
0E  CM Partners.esm
0F  SDR.esm  [Version 8.260]
10  CustomSpellIcons.esm
11  Knights - Revelation.esm
12  Unofficial Oblivion Patch.esp  [Version 3.5.4a]
13  DLCShiveringIsles.esp
14  Unofficial Shivering Isles Patch.esp  [Version 1.5.8]
15  SM Plugin Refurbish - SI.esp  [Version 1.30]
16  Better Cities .esp  [Version 6.0.5]
17  Francesco's Creatures and Items Resources.esp  [Version 5.0]
18  Francesco's Optional Chance of Stronger Bosses.esp  [Version 5.0]
19  Francesco's Optional Chance of Stronger Enemies.esp  [Version 5.0]
1A  Francesco's Optional Chance of More Enemies.esp  [Version 5.0]
1B  Francesco's Optional Leveled Guards.esp  [Version 5.0]
++  FCOM_Francescos.esp  [Version 0.9.9MB8b1]
++  FCOM_FrancescosItemsAddOn.esp  [Version 0.9.9MB8b1]
1C  FCOM_FrancescosNamedBosses.esp  [Version 0.9.9MB8b1]
1D  Fran Armor Add-on.esp
1E  All Natural.esp  [Version 1.36]
1F  All Natural - SI.esp  [Version 1.36]
++  All Natural - MMM Patch.esp  [Version 1.3]
20  Immersive Interiors.esp  [Version 0.8.1]
21  Immersive Interiors - Bravil.esp  [Version 2.01]
22  Immersive Interiors - Landscape Addon.esp
23  SnowGusts.esp
24  drifting seeds.esp
25  atmospheres.esp
++  Symphony of Violence.esp
26  Atmospheric Oblivion.esp
27  GOSH.esp
28  GOSH Region Ambiance.esp
29  Sounds of Cyrodiil.esp  [Version 1.1]
2A  Storms & Sound.esp
2B  All Natural - Real Lights.esp  [Version 1.36]
2C  WindowLightingSystem.esp
2D  1em_GiveAGift.esp  [Version 1.2]
2E  AliveWaters_nofish.esp
2F  Chapel Tithe.esp
30  DialogTweaks.esp  [Version 1.2.1]
31  Dialogue Idles.esp
32  Glowing Wonders.esp
33  My Voice Extender.esp
34  Paladin.esp
35  pmRealTimeInteractions.esp
36  Camping.esp
37  PTFallingStars.esp
38  Enhanced Economy.esp  [Version 5.4.3]
39  Display Stats.esp  [Version 2.0.1]
3A  kuerteeCleanUp.esp
3B  MigMiscellanea.esp  [Version 1.82]
3C  OblivionReloaded.esp
++  OblivionReloadedArenaCombat.esp
3D  P1DmenuEscape.esp
3E  Quest Log Manager.esp  [Version 1.3.2]
3F  skycaptains NPCFF.esp
40  StatCleaner.esp
41  Dynamic Map.esp  [Version 2.1.1]
42  Map Marker Overhaul.esp  [Version 3.9.3]
43  Map Marker Overhaul - SI additions.esp  [Version 3.9.3]
44  Enhanced Hotkeys.esp  [Version 2.3.1]
45  DLCSpellTomes.esp
++  DLCSpellTomes - Unofficial Patch.esp  [Version 1.0.1]
46  DLCSpellTomes - OBSEfixer.esp
++  MaleBodyReplacerV5.esp
**  Armamentium female.esp
47  Cobl Glue.esp  [Version 1.73]
48  Cobl Si.esp  [Version 1.63]
++  Cobl Patch - Hunger Tongue.esp
49  Cobl Patch - Silent Misc Item Equip.esp  [Version 01]
4A  Bob's Armory Oblivion.esp
4B  FCOM_BobsArmory.esp  [Version 0.9.9MB8b1]
4C  Oblivion WarCry EV.esp  [Version 1.09]
4D  Better Dungeons.esp
4E  Oscuro's_Oblivion_Overhaul.esp  [Version 1.37]
++  Alluring Wine Bottles.esp
**  OMOBS_SI.esp  [Version 2.0]
++  ArmamentariumLLVendors.esp  [Version 1.35]
4F  ArmamentariumArtifacts.esp  [Version 1.35]
50  Mart's Monster Mod - Additional Enemy NPC Vars.esp  [Version 3.8b1]
51  FCOM_Convergence.esp  [Version 0.9.9Mb8b1]
++  FCOM_EntropicOrderRebalance.esp  [Version 0.9.9beta2]
52  FCOM_RealSwords.esp  [Version 0.9.9MB8]
++  FCOM_SpawnRatesStronger.esp  [Version 0.9.9Mb3]
53  Mart's Monster Mod - More Wilderness Life No Gates.esp  [Version 3.8b1]
++  FCOM_SaferRoads.esp  [Version 0.9.9]
++  Mart's Monster Mod - Looting NPCs & Creatures.esp  [Version 3.8b1]
54  Mart's Monster Mod - Gems & Gem Dust.esp  [Version 3.7b7]
55  Mart's Monster Mod - Farm Animals.esp  [Version 3.8b1]
56  Mart's Monster Mod - Diverse WaterLife.esp  [Version 3.8b1]
++  Mart's Monster Mod - Slof Horses Complete.esp  [Version 3.7b4a]
++  Mart's Monster Mod - Diverse Runeskulls Loot G&GD.esp  [Version 3.8b1]
++  TamrielTravellerAdvscript.esp  [Version 1.40Alpha]
57  TamrielTravellers4OOO.esp  [Version 1.39c]
58  TamrielTravellersItemsCobl.esp  [Version 1.39c]
59  ShiveringIsleTravellers.esp  [Version 1.39c]
++  FCOM_TamrielTravelers.esp  [Version 0.9.9]
++  FCOM_BobsGuardUnity.esp  [Version 0.9.9]
++  FCOM_HungersUnitySI.esp  [Version 0.9.9]
++  Mart's Monster Mod - Diverse Wisp and VASE Addon.esp  [Version 3.8b1]
++  Mart's Monster Mod - More Passive Wildlife.esp  [Version 3.8b1]
5A  Mart's Monster Mod - Mummies.esp
**  FCOM_FriendlierFactions.esp  [Version 0.9.9]
++  FCOM_MoreRandomSpawns.esp  [Version 0.9.9]
++  FCOM_MoreRandomItems.esp  [Version 0.9.9]
5B  FCOM_NewItemsTemplate.esp  [Version 0.9.4]
++  Cobl Patch - MMM Gems and Gem Dust.esp
++  Cobl Tweaks - FCOM.esp  [Version 1.72]
++  Mart's Monster Mod - Shivering Isles.esp  [Version 3.8b1]
++  ArmamentariumLL4OOO.esp  [Version 2.01]
++  ArmamentariumLLMagicOOO.esp  [Version 1.35]
**  Fransfemale.esp
**  EVE_StockEquipmentReplacer4FCOM.esp
**  EVE_StockEquipmentReplacer for OOO.esp
**  DiverseDremoraArmorFCOM.esp  [Version 0.95]
5C  Orden des Drachen.esp  [Version 2016]
5D  EM_CompInnsleeping.esp  [Version 0.9]
5E  Ivellon.esp  [Version 1.8]
5F  AleswellHomeQuest.esp
60  Artifacts.esp  [Version 1.1]
**  ArtifactsFemaleArmor.esp
++  Artifacts - ArmaCompleteAddon.esp  [Version 1.0]
61  BHC_Expanded.esp  [Version 1.2]
62  CDEP-UnderpallCave.esp
63  EM_RedRoseManor.esp  [Version 2.0]
64  em_packrideponies1.esp
65  Fighters Guild Quests.esp
66  Hidden Treasure Chests-UL edition.esp
67  Kragenir's Death Quest.esp
68  KDQ - Rural Line Additions.esp
69  Kvatch Rebuilt.esp  [Version 3.0]
++  Kvatch Rebuilt Fixes.esp
6A  Mages Guild Quests.esp
6B  The Imperial Water.esp
6C  Northern Front.esp
6D  GTAesgaard.esp  [Version 1.3]
6E  GTAesgaard_2.esp
6F  QOTW Season One.esp
70  QOTW Season Two.esp
71  QOTW Season Three.esp
72  QOTW Season Four.esp
73  The Ayleid Steps.esp  [Version 3.6]
++  Aylied Steps - AN Real Lights patch.esp  [Version 1.00]
74  CDEP_FanaCeya.esp
75  Vampire Hunting - Order of the Virtuous Blood.esp
76  VHBloodlines 1.2.esp  [Version 1.5.6]
++  Vampire Hunting Bloodlines Patch.esp
77  Cyrodiil Travel Services.esp  [Version 3.1]
78  BrumaGuildReconstructed.esp  [Version 1.0.2]
79  Knights.esp
7A  Knights - Unofficial Patch.esp  [Version 1.1.8]
7B  Knights - Revelation.esp
**  EVE_KnightsoftheNine.esp
**  Knights_MOBS.esp  [Version 2.0]
++  SM Plugin Refurbish - Knights.esp  [Version 1.06]
7C  Knights - Cobl.esp  [Version 2.6]
7D  Sounds of Cyrodiil - KOTN Add-on.esp  [Version 1.0]
7E  The Lost Spires.esp
7F  AFK_Weye.esp  [Version 2.32.COBL]
80  MannimarcoRevisited.esp
81  MannimarcoRevisitedOOO.esp  [Version 0.1]
++  FCOM_Knights.esp  [Version 0.9.9MB8b1]
82  ElsweyrAnequina.esp
83  Unofficial Elsweyr Anequina Patch.esp
++  ElsweyrAnequina - Races HGEC-Robert.esp  [Version 1.2]
84  Roads of Cyrodiil.esp  [Version 1.0]
++  ROC-Elsweyr DOA - Patch.esp
++  ROC+Fighters Guild Quests.esp
85  HeartOftheDead.esp  [Version 6.5]
86  JungleHasMoreGroundcover.esp
87  Faregyl.esp  [Version 2.0.11]
88  Faregyl+Anequina Patch.esp  [Version 2.0]
89  Feldscar.esp  [Version 1.0.13]
8A  Gottshaw Village.esp  [Version 1.0.1]
8B  Molapi.esp  [Version 1.0.1]
8C  Reedstand.esp  [Version 1.0.4]
8D  Urasek.esp  [Version 1.0.4]
8E  Vergayun.esp  [Version 2.0.2]
8F  xuldarkforest.esp  [Version 1.0.5]
++  LostSpires-DarkForest patch.esp
90  xulStendarrValley.esp  [Version 1.2.2]
91  xulTheHeath.esp
92  xulEntiusGorge.esp  [Version 1.2.1]
93  xulFallenleafEverglade.esp  [Version 1.3.1]
++  LostSpires-Everglade patch.esp
++  Anequina-Fallenleaf-Patch.esp
94  xulColovianHighlands_EV.esp  [Version 1.2.2]
95  xulChorrolHinterland.esp  [Version 1.2.3]
96  xulBeachesOfCyrodiilLostCoast.esp  [Version 1.6.5]
97  xulBravilBarrowfields.esp  [Version 1.3.5]
98  xulLushWoodlands.esp  [Version 1.3.3]
99  xulAncientYews.esp  [Version 1.4.4]
9A  xulAncientRedwoods.esp  [Version 1.6]
++  ROC+Ancient Redwoods.esp  [Version 1.0]
9B  xulCloudtopMountains.esp  [Version 1.0.3]
9C  xulArriusCreek.esp  [Version 1.1.4]
9D  xulPatch_AY_AC.esp  [Version 1.1]
9E  HeartoftheDead-ArriusCreek patch.esp
9F  xulRollingHills_EV_withoutWheat.esp  [Version 1.3.3]
A0  xulPantherRiver.esp
A1  xulRiverEthe.esp  [Version 1.0.2]
A2  xulBrenaRiverRavine.esp  [Version 1.1.1]
A3  xulImperialIsle.esp  [Version 1.6.8]
A4  xulBlackwoodForest.esp  [Version 1.1.1]
A5  xulCheydinhalFalls.esp  [Version 1.0.1]
A6  DungeonsOfIvellon-CheydinhalFalls patch.esp
A7  xulAspenWood.esp  [Version 1.0.3]
A8  xulSkingradOutskirts.esp  [Version 1.0.2]
++  ROC+UL Skingrad Outskirts Patch.esp
A9  xulSnowdale.esp  [Version 1.0.6]
++  Feldscar+Snowdale Patch.esp  [Version 1.0.2]
AA  OrdenDesDrachen-Snowdale patch.esp  [Version 1.1]
++  OOO-Snowdale Patch.esp  [Version 1.1]
++  GatesToAesgaardEp2-Snowdale patch.esp  [Version 1.0]
AB  xulCliffsOfAnvil.esp  [Version 1.1.3]
AC  OOO-CliffsOfAnvil patch.esp  [Version 1.2]
AD  xulSilverfishRiverValley.esp  [Version 1.0.4]
++  Lost Spires + Silverfish River Patch.esp  [Version 1.0]
AE  xulJerallGlacier.esp  [Version 1.0.2]
AF  OOO-JerallGlacier patch.esp  [Version 1.0]
B0  OrdenDesDrachen-JerallGlacier patch.esp  [Version 1.1]
++  GatesToAesgaardEp1-JerallGlacier patch.esp  [Version 1.0]
B1  xulTheEasternPeaks.esp  [Version 1.2]
++  ROC+UL-II Patch.esp  [Version 1.0]
B2  KragenirsDeathQuest-UniqueLandscapes Merged patch.esp  [Version 2.0]
B3  Salmo the Baker, Cobl.esp  [Version 3.08]
B4  Sutch Village.esp  [Version 1.0.4]
++  LostCoast + SutchVillage Patch.esp  [Version 1.0]
++  FCOM_UnofficialFranArmorAddon.esp  [Version 0.9.9]
B5  Harvest [Flora].esp  [Version 3.0.0]
++  Harvest [Flora] - Shivering Isles.esp  [Version 3.0.0]
**  ApparatusIcons.esp
B6  Banes Guilds UnitedOOO.esp
++  Banes Guilds United BrumaGuild patch.esp
++  Banes Guilds United KR patch.esp
++  Banes Guilds United Integration patch.esp
B7  Elz - No Floating Weapon.esp
B8  EVE_ShiveringIslesEasterEggs.esp
B9  GuildAdvancementBGU.esp
BA  LastUnicorn.esp
BB  MagicArrows.esp  [Version 2.0]
BC  pmNPCServices.esp
BD  pmPersuasionOverhaul.esp
BE  pmRepairRecharge.esp
BF  SnusDungeons.esp
C0  SnusDungeons - OOO patch.esp
++  SnusDungeons - TAS patch.esp
C1  SnusDungeons - BD patch.esp
C2  Soulgem Magic.esp  [Version 2.0]
C3  StarX Vampire Deaths.esp
C4  Toggleable Quantity Prompt.esp  [Version 3.2.0]
C5  Alternative Beginnings.esp  [Version 1.4.3]
C6  HUD Status Bars.esp  [Version 6.3.2]
C7  Basic Primary Needs.esp  [Version 6.3]
C8  StarX Vanilla Vampires Revised.esp
C9  StarX VVR_OOO_FCOM Patch.esp
++  Starx-OVB Patch.esp
CA  Vampire Revolution.esp  [Version v1.13]
CB  MidasSpells.esp
CC  Midas OscuroGems.esp
++  Midas Betterholy.esp
++  Mart's Monster Mod - Midas Creature Ingredients.esp
++  Midas Tigernolevel OBSE.esp
CD  Midas BeastFortify Fix OBSE.esp
CE  Friendlier Summons.esp
CF  pmAlchemyOverhaul.esp
D0  pmLockpicking.esp
D1  Enhanced Grabbing.esp  [Version 0.5]
D2  Duke Patricks - Combat Archery.esp  [Version 7.3.5]
D3  Duke Patricks - Near Miss Magic And Arrows Alert The Target.esp  [Version 7.1]
D4  Duke Patricks - Fresh Kills Now Alert The NPCs.esp  [Version 4]
D5  Duke Patricks - Melee Combat NO RECOIL.esp  [Version 5.9]
D6  Bundlement.esp  [Version ision]
D7  nGCD.esp
D8  nGCD Oghma Infinium.esp
++  nGCD Skeleton Key.esp
D9  Glowing Respawning Varla & Welkynd Stones 14-28 Days.esp
++  Item interchange - Extraction.esp  [Version 88]
++  Item interchange - Placement for FCOM.esp  [Version 88]
++  Item interchange - Option, Ingredients in Bulk, reduced.esp  [Version 88]
DA  Atmospheric Loading Screens - No Text.esp
**  MOBSification of MODS.esp
DB  1em_Vilja.esp  [Version 4.04]
DC  ViljaOCO.esp
**  1em_Vilja OOO FCOM Fix.esp
**  1em_Vilja MMM FCOM Fix.esp
DD  ViljainAleswell.esp  [Version 1.3]
DE  ViljainRedRoseManor.esp  [Version 1.2]
DF  bgBalancingEVCore.esp  [Version 10.52EV-D]
++  DiverseDremoraRBPCosmetics.esp  [Version 0.95]
++  EVE_KhajiitFix.esp
E0  Oblivion_Character_Overhaul.esp  [Version 2.0]
**  TamrielTravellers Cosmetics Cobl or RBP.esp
E1  ZUAmberMadnessOverhaul.esp  [Version 0.13]
E2  ZUSIO-RatsInCrucible.esp
++  ZUSIO-MMM SI-patch.esp
++  ZUSIO-Map MarkerOverhaul SI-patch.esp
++  ZUSIO-SM Plugin Refurbish SI-patch.esp
E3  bgMagicEV.esp  [Version 1.7EV]
++  Banes Guilds United LAME patch.esp
++  bgMagicSpellTomes_for_WryeBash.esp  [Version 1.68EV]
++  bgMagicItemSigil.esp  [Version 1.68EV]
++  bgMagicEVStartspells.esp  [Version 1.68EV]
E4  bgMagicBonus.esp  [Version 1.7EV]
++  bgMagicEVAddEnVar.esp  [Version 1.68EV]
E5  bgMagicEVPaperChase.esp  [Version 1.68EV]
E6  bgMagicAlchemy.esp  [Version 1.57]
++  bgMagicPotionNumberSoulGemValue.esp  [Version 1.68UV]
++  SDR_Oblivion.esp  [Version 8.260]
E7  bgBalancingOptionalLessHealth.esp  [Version 10.0UV-U]
++  bgBalancingEVOptionalClasses.esp  [Version 9.0EV-U]
++  bgBalancingEVOptionalFangs.esp  [Version 10.0EV-D]
++  bgBalancingEVOptionalMoreEyes.esp  [Version 10]
++  bgBalancingEVOptionalFCOMAdditions.esp  [Version 10.]
E8  bgBalancingEVLAMEAddition.esp  [Version 10.51EV-D]
++  bgBalancingEVLAMEGlue.esp  [Version 10.0EV-D1.62EV]
**  bgBalancingEVOptionalNPCDiversityLAME.esp  [Version 10.5EV-D]
E9  bgIntegrationEV.esp  [Version 1.0b]
++  IntegrationTheStrandedLight-SilverfishRiverValley patch.esp  [Version 1.1]
++  IntegrationTheStrandedLight-EasternPeaks patch.esp  [Version 1.1]
++  RBP+OCO patch.esp  [Version 2.1]
EA  Better Cities Full.esp  [Version 6.0.6]
EB  Better Cities - IC Imperial Isle.esp  [Version 6.0.2]
**  Better Imperial City.esp  [Version 6.0.6]
EC  Better Cities Chorrol - Immersive Interiors.esp  [Version 6.0.4]
++  Better Cities - All Natural.esp  [Version 6.0.4]
ED  Better Cities Chorrol - ODD patch.esp  [Version 6.0.0]
EE  Better Cities Chorrol - Knights of the Nine.esp  [Version 6.0.4]
EF  Better Cities Full - OOO.esp  [Version 6.0.6]
F0  Better Imperial City - OOO.esp  [Version 6.0.6]
++  Better Cities - Storms & Sound.esp  [Version 6.0.0]
F1  Better Cities - VHBloodlines.esp  [Version 6.0.0]
F2  Better Cities - The Lost Spires.esp  [Version 6.0.2]
++  Better Cities - COBL.esp  [Version 6.0.4]
F3  Better Cities - Leyawiin Flooded.esp  [Version 6.0.0]
++  FCOM_BetterCities-Bravil.esp  [Version 6.0.6]
++  Disable Tutorial Text.esp
F4  Automatic Timescale.esp  [Version 1.1.1]
**  [GFX]_Initial_Glow-all.esp
F5  Duke Patricks - Magic you can believe in.esp
**  bgMagicEVShader.esp  [Version 1.7EV]
F6  bgMagicLightningbolt.esp
F7  Companion Compatibility.esp
++  ROC Standard Road Record.esp
++  Bashed Delayers - MERGE ONLY.esp  [Version 3.1.29b]
++  Cobl Filter Late MERGE ONLY.esp  [Version 1.53]
++  Oscuro's_Oblivion_Overhaul - Harvest Containers - SI.esp  [Version 0.99b]
++  OOO Harvest Containers Filter patch for mods.esp  [Version 1.03]
**  All Natural - Indoor Weather Filter For Mods.esp  [Version 1.36]
++  Storms & Sound - Filter Patch.esp
F8  Bashed Patch, 0.esp
F9  Duke Patricks - Fortress of Fear.esp
FA  DukePatricksFortressOfFear-Snowdale patch.esp  [Version 1.0]
FB  Duke Patricks - Combat Magic II.esp
FC  Maskar's Oblivion Overhaul.esp  [Version 4.6.3]
[/xml][/spoiler]



As you can see it is a pretty heavy load order but other than that issue above bash has no problems building a bashed patch.

I've also posted this to github in the same comment section as the other bug.

Artoriius.

**Comment by Slangens** [comment] 2016-06-02 15:52
I have had this error, too. It isn't related to the WB patcher, it's a problem with Item Interchange and Better Cities, if the BC version is too high. 
II contains some injected records that originally were overrides of an older BC version. Now these records were removed and II injects the records, which for some reason makes the patcher crash. 
This can be easily resolved by loading II into Tes4Edit and removing all the records that are being injected into the BC esm. 

So, problem solved, no patcher issue.

**Comment by Utumno** [comment] 2016-06-02 16:37
Thanks !

The issue in the first post however seems to be related to another plugin ? Or is it the same thing under covers ? @jatkinson85  what you say ?

**Comment by CaiqueSell** [comment] 2018-08-04 15:33
Do u got fix this?

**Comment by Infernio** [comment] 2019-12-18 00:10
Please comment / reopen if this can be reproduced again.

**Closed by Infernio** 2019-12-18 00:10 UTC
Labels: R-works-for-me, A-patchers
