### ISSUE TITLE
(Oblivion, Linux) Wizard install fails to install files

### ISSUE THREAD

**Issue by paolobolzoni** [wrye-bash/wrye-bash#315] opened 2016-07-06 21:57 UTC
I am using Wrye Bash 306 in my Linux system and it works fine for making the Bashed Patch and loading or not mods. But when used to install mods via Wizard it does not copy some files. The problem manifest both in case-sensitive and case-insensitive partitions.

To reproduce, just try to install a mod with a Wizard like Francesco[1], in the Installer tabs the operation will appear successful, close wrye bash and open it again, some files will be missing.

[1]
www.nexusmods.com/oblivion/mods/40190

**Comment by m0lz** [comment] 2016-07-07 09:39
paolobolzoni I think this has already been fixed in the more recent 307 code

Have a look at installing the latest Wrye Bash, at the end of this post ..

http://forums.bethsoft.com/topic/1604190-wrye-bash-thread-110/#entry25181008

There are links for Python versions or the Standalone

**Comment by paolobolzoni** [comment] 2016-07-07 09:44
Indeed, I looks like issue 96[1], I'll test and report. Thanks.

[1]
https://github.com/wrye-bash/wrye-bash/issues/96

**Comment by Utumno** [comment] 2016-07-07 18:26
You are using WINE right ? Which version ?

<Unfortunately I do not have Linux set up here and this will have to wait a bit>

**Comment by paolobolzoni** [comment] 2016-07-07 20:05
Yes, I am using wine. It's not the newest, but it's fairly updated.

```
% wine --version
wine-1.9.11 (Staging)
```

**Comment by Utumno** [comment] 2016-07-07 20:54
Excellent thanks - always interested in making Bash WINE (and eventually bare bones Linux) compatible - 306 is the first release to run on wine after a while. Please keep using the 307 version and report slight glitches in the wine issue - #240.

Don't hold your breath however - I have a lot on my plate and I am moving for the summer.

@m0lz - thanks for chiming in

**Comment by paolobolzoni** [comment] 2016-07-08 07:47
Then you should start calling Wine "Wine" and not "WINE." "Wine" is indeed the correct capitalization.
See also here: https://web.archive.org/web/20080713223549/http://wiki.winehq.org/FAQ (Question 1.11)

About the topic, I see in https://github.com/wrye-bash/wrye-bash/issues/96 is a patch to remove the SHFileOperation, that are broken in Wine, and use the normal Python calls. At the moment the patch does not apply to 307, but how difficult would it be to fix in that way? I tried to understand the code, but it appears really windows focused.

Really, installing the Wizard is the main problem I have with wrye bash. Some mods are pretty difficult to install manually. Examples include the Robert Male body replacer and the Animated Window Lighting System and Chimneys.

**Comment by Utumno** [comment] 2016-07-08 19:05
Let's call it wINE ok ? ;)

Now, to the issue at hand - it's not as simple as it seems - follow the commits linked in #96 to see why.

Does a simple install work ? I mean you can use the wizard to select the correct files then right click install.

If not so, it is not a wizard problem but an install problem - in this case can you provide me a simple reproducer ? That is pack a complex BAIN (but not too complex)  and link me to that and post me which files are not installed and which are.

Plus I am not really sure which path is used in wine. I added a commit that disables the SHFileOperation path for sure - here is the source:

https://github.com/wrye-bash/wrye-bash/archive/utumno-315.zip

This should use pure python (completely bypass the SHFileOperation path), is the problem still present ?

I do not have access to a linux set up so this must wait - but let's see what exactly is wrong first

**Comment by paolobolzoni** [comment] 2016-07-08 20:31
wINE lOOKS cOOL tOO!

About this version utumno-315, the "Select and use Install" works fine.

But the Wizard gives this error:
```
An unhandled error occurred while parsing the wizard:
Line 12:	RequireVersions "1.2.0.416","0.0.19.4","","292"

Traceback (most recent call last):
  File "bash\belt.py", line 940, in Continue
    self.RunLine(newline)
  File "bash\ScriptParser.py", line 502, in RunLine
    key(*self.tokens)
  File "bash\ScriptParser.py", line 367, in __call__
    def __call__(self, *args, **kwdargs): return self.tkn(*args, **kwdargs)
  File "bash\ScriptParser.py", line 294, in __call__
    return self.execute(*args)
  File "bash\ScriptParser.py", line 259, in execute
    return self.function(*args)
  File "bash\belt.py", line 1632, in kwdRequireVersions
    self.page = PageVersions(self.parent, bGameOk, gameHave, game, bSEOk, seHave, se, bGEOk, geHave, ge, bWBOk, wbHave, wbWant)
  File "bash\belt.py", line 553, in __init__
    linkGame = _link(bush.game.displayName, bush.game.patchURL)
  File "bash\belt.py", line 550, in _link
    url=url)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_controls.py", line 6632, in __init__
    _controls_.HyperlinkCtrl_swiginit(self,_controls_.new_HyperlinkCtrl(*args, **kwargs))
TypeError: Required argument 'id' (pos 2) not found
```

However, it appears one of those small bugs we apparently always forget in the code... I read the file in v306 and I simply changed line 549 of (utumno-315)belt.py to:
```
        def _link(label, url): return wx.HyperlinkCtrl(self, label=label, id=wx.ID_ANY,
                                                       url=url)
```

And it works fine! WELL DONE!

(At least the first super quick test of installing and updating the wrye bash data and giving a quick glance to the Data directory)

**Comment by Utumno** [comment] 2016-07-08 20:44
Grrr, they are supposed to accept keyword arguments - will fix (I added this `_link` thingy exactly to bin wx.ID_ANY).

----

Anyway, in  utumno-315 the only think I do is disable the SHFileOperation - so it seems it indeed fails on Wine - we pass in a glob pattern in BAIN install and may be this fails. All these are guesses, I still have to run it myself and this may take a while.

Maybe add a `--wine` command line switch ?

**Comment by paolobolzoni** [comment] 2016-07-08 20:56
There is a way to detect wine:
https://www.winehq.org/pipermail/wine-devel/2008-September/069387.html
In python I am afraid you have to use ctypes, unless something easier is already there.

However, as explained in the FAQ[1] this is frowned upon as Wine is supposed to work as Windows. Still, since in this case it obviously does not I think it's fine... at least until Wine catches up with the bugs in SHFileOperation.

[1]
https://wiki.winehq.org/Developer_FAQ#How_can_I_detect_Wine.3F

**Comment by paolobolzoni** [comment] 2016-07-08 21:16
About v307, I tried to install Francesco[1] asking to install everything to use this great mod standalone. In detail:

```
00 Core
01 SI + MOBS + Combat Tweaks/Francesco's Leveled Creatures-Items Mod.esm
02 Items Addon Resources
03 Items Addon SI + MOBS
04 Creatures Addon Resources
05 Creatures Addon SI
06 More Wilderness Life
07 Chance of More Enemies
08 Optional Extras SI
```

and v307 fails to install:
```
Docs\Francescos Creatures and Items - V5B1-40190-5-0B1.txt
docs\Francesco's Creatures and Items\Full Changelog.rtf
docs\Francesco's Creatures and Items\Loot Tables.xls
docs\Francesco's Creatures and Items\MOBS Weapon Stats.xls
docs\Francesco's Creatures and Items\Original Readme.htm
docs\Francesco's Creatures and Items\ReadmeBG01.jpg
docs\Francesco's Creatures and Items\ReadmeBG02.jpg
```
Interestingly I am fairly sure in my older test it was missing also to install the files in the ini directory. I am not sure why it's changed, perhaps between 1.9.11 and 1.9.13 (staging) some bug in SHFileOperation has been fixed? 

[1]
http://www.nexusmods.com/oblivion/mods/40190

**Comment by Utumno** [comment] 2016-07-08 21:18
> There is a way to detect wine:

Yes I am aware and I am aware it is frowned upon, won't go that way

----

Since you have this set up it would be nice if you checked the other wine issues here. The canVista=False for instance I commented on here: https://forum.winehq.org/viewtopic.php?f=8&t=25299&e=0&sid=3184e1736e37c2cfce91d2120e335c0f

Is this still the case with newer wine ? Don't reply to me here - #240 is for this.

---
General note - I have been running the project for almost 3 years now. Heck I rewrote the thing. But I am getting tired. Do not expect things to get readily fixed - plus there are some other tricky parts in the code that have priority.

Good technical information is valuable to me or whoever comes next.

Volunteers needed.

**Comment by Utumno** [comment] 2016-10-04 23:17
@paolobolzoni Fixed another little something in my latest iteration of utumno-wip that may solve this one - care to try ?

**Comment by Utumno** [comment] 2017-09-05 17:25
@paolobolzoni - newest utumno-wip has more fixes in install that may be relevant here - give it a whirl :)

**Comment by monyarm** [comment] 2018-03-30 15:04
I also have this issue, when i attempt to install a mod through Wrye Bash in wine i get the following error 
"0049:fixme:shell:check_flags Unsupported flags: 0231"

**Comment by ElementW** [comment] 2019-03-16 22:13
This was fun to track down. End-user WB fix at the bottom.
The issue resides in [`env.py:_fileOperation()`](https://github.com/wrye-bash/wrye-bash/blob/c911036b08f754a45197d2668d4ddad9f049d49b/Mopy/bash/env.py#L460). On Windows/Wine, the file operations use the `shell32` API, and Wine's implementation of `SHFileOperation` seems to not be the exact same as on Windows, perhaps due to undocumented details of that function; 
I'm thinking directory creation semantics as the file I tested on tried to install to `
DATA\SKSE\Plugins\` which didn't exist yet. When I created those directories, install worked, then I deleted them to test further.
Wine implements neither of `FOF_NO_CONNECTED_ELEMENTS`, `FOF_NOCOPYSECURITYATTRIBS`, `FOF_NORECURSEREPARSE`, `FOF_RENAMEONCOLLISION` and `FOF_WANTMAPPINGHANDLE` at the moment and explicitly checks for these flags in order to give the warning @monyarm noticed. In their case and generally the unsupported flag is `FOF_WANTMAPPINGHANDLE`, but this isn't even the issue.
The issue here is **Wine doesn't implement directory creation for `FO_MOVE`!** Surprisingly.
It is implemented for copy operations and is even part of their test suite, but `dlls/shell32/shlfileop.c:move_files()` checks for the existence of target directories, and if they are not, `return ERROR_CANCELLED;` translating in the `aborted` return param of `shell.SHFileOperation` being `True`, in turn deleting the unpacked files.
Not using the shell API by setting the default parameter `__shell=False` made copying work properly on Wine.

What needs to be done is fix Wine's behaviour, as it obviously is incorrect as [the MSDN doc for `struct SHFILEOPSTRUCTA`](https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/ns-shellapi-_shfileopstructa) explicitly mention
> Copy and Move operations can specify destination directories that do not exist. In those cases, the system attempts to create them and normally displays a dialog box to ask the user if they want to create the new directory. To suppress this dialog box and have the directories created silently, set the FOF_NOCONFIRMMKDIR flag in fFlags.

For a fix on Wyre Bash's users' side, open `Mopy/bash/env.py` and replace `__shell=True` by `__shell=False`.

**Comment by Utumno** [comment] 2019-03-16 22:50
This was fun to read :P (and thanks for taking the time!). Unfortunately, since  `SHFileOperation ` is deprecated, the chances they fix the bug are slim.

We could implement a command line flag (like `--wine`) for setting the `__shell` to false but that goes a bit too far - Wine compatibility touches this part of the code with vista dialogs (and other such stuff like app buttons) that was somewhat hacky and it shows. It's useful that it shows but we can't do much about those at the moment - wx3 and eventually python 3 rewrite should take care of all that.

There is another angle to that - namely filesystem operations - I am not really satisfied with the current wrappers but again this must wait, see #241 where I also mention `IFileOperation`, but I think it's not even in python winapi

For now we should add the user side fix to the main readme and close this

**Comment by Utumno** [comment] 2019-03-16 23:06
On an afterthought reverting part of https://github.com/wrye-bash/wrye-bash/commit/9fcbbefc26145be3711ea260828942558e6f2fa7?w=1 could cure this - but would reintroduce creating a bunch of directories that would remain even if install failed for other reasons - yak those operations should be atomic but this is another limit - copy operations may fail (say lack of disk space) and leave stuff partly moved anyway

**Comment by t0suj4** [comment] 2021-02-08 12:04
If anyone is interested in compiling wine I'm attaching this patch [fileop.txt](https://github.com/wrye-bash/wrye-bash/files/5943413/fileop.txt), it only takes care of this specific problem where it doesn't create directories when moving multiple files and it's largely untested outside of Wrye Bash. This specific change was done against lutris wine 5.7-11.

If you already have lutris wine binaries, it is enough to replace `~/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/lib/wine/shell32.dll.so` and `~/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/lib64/wine/shell32.dll.so` by `dlls/shell32/shell32.dll.so` for their respective architecture.

If you're going to compile Wine yourself, get familiar with [build instructions](https://wiki.winehq.org/Building_Wine) especially with [multilib](https://wiki.winehq.org/Building_Wine#Shared_WoW64) unless you're running strictly 32bit system.

For this specific version of Wine I also had to disable `winegstreamer` in `winecfg` and install `amstream` and `quartz` through `winetricks`. I suggest to use special wine prefix for Oblivion.

I've done it this way because I wanted to use the binary Wrye Bash version.

**Comment by llde** [comment] 2021-02-08 20:04
@t0suj4 
Oblivion doesn't need to diable winegstreamer from wine 1.x something. You just need to properly install the correct 32bit gstreamer plugins. 
Please don't spread false info that make people continue to use a broken install.

I'm gonna refactoring a bit the patch and upload it to the community patches repo for wine-tkg

**Comment by t0suj4** [comment] 2021-02-08 21:06
Calling it false info is a quite strong word. I'm on elementary OS 5.1.7 Hera and 32bit gstreamer is pain.

My change made some of the wine move tests fail, if you're gonna upload it, make sure those tests pass. I've changed behavior when there is more sources than destinations, should get reverted, and I'm not quite sure about behavior when the target is only a directory.

**Comment by t0suj4** [comment] 2021-02-10 08:49
I came back, fixed failing test and created new one to cover the functionality a bit better.
[fileop_move.txt](https://github.com/wrye-bash/wrye-bash/files/5956858/fileop_move.txt)

**Comment by llde** [comment] 2021-02-11 14:46
@t0suj4 Patch is commited in https://github.com/Frogging-Family/community-patches

**Comment by Infernio** [comment] 2023-10-21 20:43
We're not putting any more effort into better support for wine now that our Linux support has advanced massively in 312. Closing in favor of #243.

**Closed by Infernio** 2023-10-21 20:43 UTC
Labels: R-rejected, A-wine
