### ISSUE TITLE
[Oblivion] Bashed Patch changing hardcoded FormIDs

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#92] opened 2014-05-31 20:29 UTC
[svn](https://sourceforge.net/p/oblivionworks/bugs/257/)

[Discussed in the forum thread](http://forums.bethsoft.com/index.php?app=forums&module=forums&section=findpost&pid=22419626), when a bashed patch alters a record from a mod that doesn't have Oblivion.esm as master, and said record uses a hardcoded formID, the patch is changing the formID in the record to have the modIndex of the first master available for the mod, or of the mod itself if it has no master, instead of leaving it as 00 like it should.
Hardcoded formIDs are for those objects that are available in the CS with no mods loaded (Player, PlayerRef, CreatureFaction, Lockpick, Gold001...)

**Comment by XJDHDR** [comment] 2016-03-21 13:39
I actually reported this same bug back in mid 2011. You can find the bug I published for the CBash patcher here: ([https://sourceforge.net/p/oblivionworks/bugs/88/](https://sourceforge.net/p/oblivionworks/bugs/88/)). I'm not sure what happened to the Python patcher's bug report, assuming it ever existed.

You can replicate this bug using a mod I published at the time and which is still up with the same problem. In my particular case, my mod doesn't work at all after being merged into the Bashed Patch and as I concluded at the time, it is because Oblivion sees that my script has a non-existent record and ignores it. 

1. Go here ([http://www.nexusmods.com/oblivion/mods/37983/?](http://www.nexusmods.com/oblivion/mods/37983/?)) then download and install the file "Play Special Music v1.1c" (if you see this file in the "Old Versions" section, download that one as I will probably soon release an update that works around this bug; I do apologize but if this bug hasn't been fixed after nearly 5 years, I'm not too hopeful it will be fixed in the near future).
2. Download and install "Plugin Resources" ([http://www.nexusmods.com/oblivion/mods/37684/?](http://www.nexusmods.com/oblivion/mods/37684/?)). The other requirements won't be needed unless you are going to use the mod in your game.
3. Rebuild the Bashed Patch and choose to merge the Play Special Music plugin. You will also need to make the Bashed Patch dependant on Oblivion.esm to see the effects of this bug. You can do so either by merging an Oblivion.esm dependant plugin or selecting a tweak that patches Oblivion.esm ("As Intended: Boars/Imps" is what I remember using at the time).
4. If done correctly, you should see something similar to the attached picture if you open the Bashed Patch in TES4Edit.

![wrye bash hardcoded formid bug](https://cloud.githubusercontent.com/assets/7355441/13919866/97644d1c-ef78-11e5-8306-2d4afa893f67.png)

**Comment by Utumno** [comment] 2016-03-21 15:03
Thanks for detailed report - the python variant from the OP https://sourceforge.net/p/oblivionworks/bugs/257/

I have no time to look into this but the detailed report with reproducer will help - not sure at all if it can be fixed - there are things like design bugs and if we hit some such there's little to be done

**Comment by XJDHDR** [comment] 2017-02-12 00:18
I recently started thinking about this bug again and I think I have an idea of what is going on inside Wrye Bash that causes this problem. I hope my explanation is clear enough.

As far as I'm aware (correct me if I'm wrong at any point), when WB merges mods into the Bashed Patch, it copies all of the records from those plugins and adds them to the BP's collection of records. At some point, WB will also create a list of plugins that need to be added to the BP's master list and arrange them as per the user's current load order. At some point after that, WB will then need to determine what ModID needs to be assigned to each record that is in the BP. 
This is how I think WB determines the ModID for each record: WB will figure out what plugin that record was copied from. WB will then look at the ModID of that plugin's record then look at the plugin's master list to find the name of the master mod that contained the record that the plugin modified. WB will then search through the BP's master list to find out the master mod's position in that list. The record in the BP will then be assigned a ModID based on that master's position.
I may be wrong but this explanation makes the most sense based on what I'm seeing.

This process beaks down when it comes to specific circumstances where all of the following are true:
- The mergable mod and it's masters don't depend on Oblivion.esm
- The Bashed Patch does depend on Oblivion.esm
- The mergable mod modified hardcoded records

It breaks down because when WB searches through the mergable mod, it calculates that the hardcoded record came from the first mod in that plugin's master list and then, in the BP, assigns a ModID based on that master's position in the BP master list when it should actually be assigned the ModID 0x00.

=
I will try to give a simple example to help illustrate the above process. Let's say we have **Script.esm**, which contains a script, and **Gold.esp**, all it does is attach the script in **Script.esm** to _Gold001_ (a hardcoded reference). Neither **Script.esm** nor **Gold.esp** is dependent on **Oblivion.esm**; because Gold001 is a hardcoded reference, the construction set will allow you to add a script to it. 
Because **Gold.esp** only modifies records, it can be merged into the BP. 
Now let's say a user installs both of these mods and merges **Gold.esp** into the BP. The user also selects a few options in the BP to modify some of the game's settings. When building the BP, WB will copy some records from **Oblivion.esm** to apply those game settings changes and will also copy _Gold001_ from **Gold.esp**. WB will also determine that **Oblivion.esm** and **Script.esm** are required in the BP's master list with **Oblivion.esm** having the ModID 0x00 and **Script.esm** having the ModID 0x01. At some point, WB will calculate the ModID that _Gold001_ requires in the BP. It looks at **Gold.esp** and sees that _Gold001_ in that plugin has the ModID 0x00. WB then looks at **Gold.esp**'s master list and sees that **Script.esm** is at position 1 in that list. WB then looks for **Script.esm** in the BP's and sees that it is in position 2 in _that_ list. As a result, WB assigns the ModID 0x01 to _Gold001_ in the BP.

This next bit depends entirely on where and how in WB's code the above process happens and it's relationship with the rest of WB's code.
My suggestion for solving this bug would involve something along the lines of the following: 
Search for the portion of the code that does what I mentioned above and add this at the start of it:
```
; Start of ModID determination code
If FormID < 0x800
    ModID = 0x00
Else
    ; The original code that does what I mentioned above
    ...
    ...
    ; End of the original code that does what I mentioned above
EndIf
```
Unfortunately, I don't really know anything about Python and so I doubt I can help with this. I do hoped that this comment helps you though.
If you're wondering where I got the _FormID < 0x800_ line from, Warradur stated in the original bug report that "Any FormID with an ObjectID < 0x800 is considered to be owned by Oblivion.exe":
[https://sourceforge.net/p/oblivionworks/bugs/88/#261f](https://sourceforge.net/p/oblivionworks/bugs/88/#261f)

**Comment by Utumno** [comment] 2017-02-12 11:20
That's an amazing job - thanks a lot! I will try and have a look but does the same condition (`If FormID < 0x800`) hold true for other games ?

(Python is an amazing language - I recommend you give it a whirl, plus I could use coders, especially people with record knowledge - not my area of expertise)

**Comment by Sharlikran** [comment] 2017-02-12 15:35
The hard coded FormIDs from the respective CK are in all of the .dat files included with xEdit. All games have these.

**Comment by XJDHDR** [comment] 2017-02-13 09:53
@Utumno
I just tested your monkey patch and I think this bug has been fixed:
![hardcoded id working](https://cloud.githubusercontent.com/assets/7355441/22877337/dfeb5598-f239-11e6-830a-c1775bdd950a.png)
In case you're wondering what you're looking at, I built two Bashed Patches with the same configuration. One with the 307 beta 1 version uploaded to Oblivion Nexus (ignore the typo in the BP's name) and the other with the latest version of your WIP branch. The 307b1 BP has an incorrect FormID assigned for the script's reference (0x01000014) and the WIP branch BP has the correct FormID assigned (0x00000014). 

You asked whether FormID < 800 is true for the other games as well. I have noticed that when I open the Construction Set and create a new record with no masters or plugins loaded, the CS assigns the FormID 0x00000800 to that record and every record created after that will be assigned the FormIDs 801, 802, 803 and so on. I think that this is because the CS will not assign a FormID in the hardcoded range and so starts with the first FormID immediately outside that range. I decided to test what would happen if I did the same thing in the GECK/Creation Kit for Fallout 3, New Vegas, Skyrim and Skyrim Special Edition (don't have Fallout 4 and so can't test that). 
I found that the GECK/CK also assigned **0x00000800** for the first new record **except** for Fallout 3's GECK which assigned the FormID **0x000008"49"** as the first FormID. 
I believe that this defines the range; Oblivion, New Vegas and the two Skyrims use the range 0 - 799 for hardcoded FormIDs and Fallout 3 uses the range 0 - 848. Someone who has Fallout 4 will have to do the same test to figure out it's range.

On a side note, I discovered a small bug. In the Wrye Bash Mod tab, I clicked on a mod, changed it's name under the "File:" text box then clicked on **Save**. The plugin's name was changed and a traceback appeared. This is what it said for your WIP branch:
```
Traceback (most recent call last):
  File "bash\balt.py", line 417, in <lambda>
    if onButClick: self.Bind(wx.EVT_BUTTON, lambda __event: onButClick())
  File "bash\basher\__init__.py", line 1453, in DoSave
    bosh.modInfos.rename_info(oldName, newName)
  File "bash\bosh\__init__.py", line 2324, in rename_info
    return self._rename_operation(oldName, newName)
  File "bash\bosh\__init__.py", line 3510, in _rename_operation
    FileInfos._rename_operation(self, oldName, newName)
  File "bash\bosh\__init__.py", line 2534, in _rename_operation
    fileInfo.abs_path = self.store_dir.join(newName)
AttributeError: can't set attribute
```
Too tired. Will type the rest tomorrow.

**Comment by Sharlikran** [comment] 2017-02-13 15:55
@XJDHDR I was going to give Utumno some info on the bug you reported, but from the mods tab there is no rename to rename a file. I can change the name of the installers from the Installers but you said the mods tab. If I right click the file itself or the column header there is no rename to rename a plugin.

**Comment by Sharlikran** [comment] 2017-02-13 16:07
@XJDHDR NM I found what you mean.

**Comment by Utumno** [comment] 2017-02-13 16:34
Excellent thanks - will fix the bugsie (good catch) - zilav of xEdit seems to believe that all games are in the same range (http://forums.bethsoft.com/topic/1615914-wrye-bash-thread-114/page-4#entry25317608) - will poke him again

You actually fixed a bug ;)

**Comment by Utumno** [comment] 2017-02-14 10:15
Latest python wip should contain the fix for the renames plus as discussed in the thread the fix for the issue at hand (according to zilav all games most probably use the 0x800 range)

**Comment by XJDHDR** [comment] 2017-02-15 08:52
If Zilav says that the range ends at 799, I think I will defer to his judgement. 
I just tested the latest WIP and can confirm that the rename bug has been fixed. The hardcoded FormIDs bug is also still fixed. I also decided to test with the CBash patcher as well and found that the bug is fixed there too. 
I'm satisfied that this bug is fixed. If you're happy, I think this issue can be closed.

It's funny to think that after nearly 6 years, fixing this bug only required editing three lines of code.

As for learning Python, I am willing to look into it at least. Unfortunately, I have a lot on my plate right now, including an important course at my college. I'm not sure when I will have time to learn Python but I will keep it in mind when I do.

**Comment by Utumno** [comment] 2017-02-15 10:11
Thanks for confirmation, much appreciated - I close issues from commits so
let me do that

> It's funny to think that after nearly 6 years, fixing this bug only
required editing three lines of code.

Well it's code I am not familiar with, so if someone turns up and explains
what's going on as you did then I can easily fix it - the hard part is to
grok what goes wrong and you did that for me. I am sure the rest of the
patcher bugs will be such easy fixes - but people still don't give me
minimal reproducers as in minimal mods and patch options.

Plus it's clear that all this will be monkey patching till we have unit
tests for the patchers

> As for learning Python, ...

Studying CS ? You seem to know something about it. I use heavilly OO python
so focus on that  - set up pycharm as detailed in our wiki, it really helps
(and you can get the professional edition with your school account)

**Closed** 2017-02-20 00:45 UTC
Labels: bug, patcher, svn

**Comment by XJDHDR** [comment] 2017-02-22 08:39
Sorry for the late reply.

>>  It's funny to think that after nearly 6 years, fixing this bug only required editing three lines of code.

>Well it's code I am not familiar with, so if someone turns up and explains what's going on as you did then I can easily fix it

If you got the impression that I was criticising anyone, I apologise. I was simply making an observation. I was not criticising anyone, especially not you (you did say before that you weren't familiar with that code). 

You did grab my interest though. How exactly did my explanation help you find the lines of code that needed to be edited?


>> As for learning Python, ...

>Studying CS ? You seem to know something about it.

No, I'm actually studying Electrical Engineering. I do know a lot of things about computers, including a rudimentary level of knowledge in programming, but the majority of it was self-taught. My programming knowledge actually started with writing scripts for my Oblivion mods. More recently, I've needed to learn how to write Shell and AutoHotkey scripts to automate various tasks on my linux server and PC, respectively. Then there was one time 3 months ago where I had to learn a little bit about Assembly to make some modifications to an EXE. I haven't used any major programming languages (yet?) but I have picked up a few things about programming in general. 

Like I said, when I have some free time available, I'll give learning Python some consideration.

**Comment by Utumno** [comment] 2017-02-22 15:48
Hey - no I didn't think you were criticizing anyone but it's always nice to be nice :)

Your explanation helped me map the bug to the code (I am somewhat familiar after all) and actually it explained some parts of the code to me.

Python is an Object Oriented language - and to me OO _is_ programming. There is the central notion of a class representing an abstract notion and the concrete instances of that class (the objects).

It's a long way (I have a degree in programming btw, and it does take some effort) but I find it very interesting (obviously).

I need help in other levels too - you seem to have a talent for explaining stuff and you are probably familiar with records and game mechanics. Just _commenting_ the patchers code would be a huge help ;)

(Btw Autohotkey was my first programming language, I couldn't write a line in it now but I did write some stuff once http://www.nexusmods.com/oblivion/mods/25031/?)
