### ISSUE TITLE
Mergeable plugins do not auto deactivate

### ISSUE THREAD

**Issue by alt3rn1ty** [wrye-bash/wrye-bash#157] opened 2014-09-11 18:00 UTC
Reference post on BGS forum http://forums.bethsoft.com/topic/1507008-relz-wrye-bash-thread-38/#entry23763120

Found a minor problem with Wrye Bash 305 Standalone, for Skyrim

Example mod ( Just found this recently, really nice and a potential Bash Tweak ? ) - http://www.nexusmods.com/skyrim/mods/57376/?

Its just a couple of GMST tweaks, if you choose the second file as an option, it is fully mergeable in the bashed patch

Problem 1 = After merging into the bashed patch, the mod is not auto-deselected ( + instead of a tick ) ( I do not have Oblivion anymore but I recall this used to be the expected behaviour and worked consistently well in the past )

In the following screenshot, I have already previously merged the mod into the bashed patch, to show that the mod still has a Tick, instead of the expected +, and then I selected Rebuild Patch to show the options as they were chosen - http://i.imgur.com/JgnInwY.jpg

Problem 2 = After manually setting this to +, after the first rebuild of the bashed patch, then closing and reloading Wrye Bash, the + had gone back to a tick. However after de-selecting it to a + a second time ( with the bashed patch already having merged the plugin previously ), then closing Wrye Bash and reloading it for a third time .. The de-selected state had stuck at a + this time around. http://i.imgur.com/fmZ5wY0.jpg

I did check the details of the bashed patch after rebuilding it for the first time to see if the GMSTs were actually included - http://i.imgur.com/wniGGmQ.jpg

**Comment by Utumno** [comment] 2015-04-23 01:30
@Sharlikran: is this still valid in Skyrim ? Would like to have it in 306 if it proves an easy fix

**Comment by Utumno** [comment] 2015-05-25 13:34
Downloaded the patch and followed the steps and I can't reproduce - related to https://github.com/wrye-bash/wrye-bash/commit/28580e75b72df63d93e372793ed508f7ccaea553 ?

Can anyone verify ?

**Comment by Utumno** [comment] 2015-06-01 00:32
@alt3rn1ty: please download my latest branch https://github.com/wrye-bash/wrye-bash/archive/utumno-163-wip.zip

Problem 2 should be gone

RE: problem 1 - did indeed Bash prompt you to desactivate _after_ rebuilding the patch ? Cause if not problem 1 is no problem - Bash will correctly prompt you to deactivate _before_ building the patch and leave it alone after building the patch

Please verify cause I want this in 306

Thanks

**Comment by Sharlikran** [comment] 2015-06-01 01:44
@Utumno @alt3rn1ty inadvertently resolved part of that issue when deleting some of the .dat files in relation to a Bash Tags issue.  Even though the issue he was resolving was unrelated to the prompt to disable mods he [did report](http://forums.bethsoft.com/topic/1507008-relz-wrye-bash-thread-38/?p=23771110) that he was prompted as expected.

**Comment by Utumno** [comment] 2015-06-01 12:07
I guess I should just patch the docs then to clarify that one is prompted _before_ building the patch

**Comment by Utumno** [comment] 2015-06-01 12:07
I guess I should just patch the docs then to clarify that one is prompted _before_ building the patch

@Arthmoor - did Bash ever prompt you _after_ building the patch ?

**Comment by Arthmoor** [comment] 2015-06-01 19:54
No, Bash should always be prompting for deactivating mergable mods BEFORE the patch is built. The only thing it should prompt for AFTER is if you want to activate the newly made Bashed Patch if it's not already active.

**Comment by alt3rn1ty** [comment] 2015-06-01 20:36
@ Utumno - Just downloaded the WIP, but sorry I cannot do anything with it, I do not wish to have python installed on my machines these days, I haven't used anything but standalone since .. I cant remember when.

**Comment by Utumno** [comment] 2015-06-01 21:03
@Arthmoor : thanks ! pheww

@alt3rn1ty : you grumpy old dragon - I will built a standalone for you then soon ;)

**Comment by Utumno** [comment] 2015-06-01 22:05
@alt3rn1ty : link in second post (or for now: https://www.dropbox.com/s/jommhovk5qj5fb6/Wrye%20Bash%20306.201506012308%20-%20Standalone%20Executable.7z?dl=0)

:)

**Comment by alt3rn1ty** [comment] 2015-06-01 22:59
As far as I have tested :) Its working as expected

After choosing to Rebuild the Bashed Patch, I was asked if I wanted to deselect the mod I have which is mergeable

[url=http://i.imgur.com/ljhtjcZ.jpg]screenshot 1[/url]

The Build dialogue also has this mod as one of its new Tweaks, so I left that unselected so that I merge the mod plugin instead of using the GMST tweak

[url=http://i.imgur.com/2UMg9pO.jpg]screenshot 2[/url]
( Also noticed the new Import Names its catching for Skyrim.esm )

After building the Bashed Patch, I was asked if I wanted to activate the Bashed Patch, I clicked yes and it did .. While also deselecting with a merged + the mod which has been merged into the bashed patch :+1: 

Closing, and then reloading Wrye Bash, I have everything ticked and deselected as they were before exiting Wrye Bash =

Thats problem solved imho :)

**Closed** 2015-06-03 20:12 UTC
Labels: bug
