### ISSUE TITLE
Names patcher

### ISSUE THREAD

**Issue by kaliban71** [wrye-bash/wrye-bash#167] opened 2014-10-13 09:43 UTC
I am using 306.0.11 the patchers are only adding from Skyrim.esp and Update.esp
![dwm 2014-10-13 04-19-38-01](https://cloud.githubusercontent.com/assets/9027857/4611617/2239d0b0-52bd-11e4-87b6-ac0b11af162e.gif)
![dwm 2014-10-13 04-26-22-17](https://cloud.githubusercontent.com/assets/9027857/4611619/2248b76a-52bd-11e4-822e-c2bb56e65f82.gif)
![dwm 2014-10-13 04-32-20-34](https://cloud.githubusercontent.com/assets/9027857/4611618/22429902-52bd-11e4-83b2-c00498485280.gif)

**Comment by Sharlikran** [comment] 2015-01-16 16:31
@lojack5 If you have time I could really use some clarification on this.  @Utumno, lojack will probably know off the top of his head.  However, if he doesn't have time to answer over the next few days.  Could you try and go over the patchers and look for something for me.  I'm not saying to go over all the patchers, or just the Names Patchers, but to look at the Names Patcher and skim over the main patching routine in general to see if this is expected behavior.

Scenario: The [long post here](http://forum.step-project.com/topic/6872-wrye-bashsmashflash-patcher-updates/?p=110732) might be too much to read but it has screen shots to fake plugins to illustrate this.  When two mods alter names they both need the Names Bash Tag.  PermaCore might change PERK and AVIF records as well as others.  The other mod SneakPickPoision alters the Names of Poisions which are ALCH Records or ingestibles.  So in theory the two should never conflict.  What if a third mod, SomeMod.esp, alters some of the same records as PermaCore but not the names.  The end result is that PermaCore's name changes get set back to vanilla values.

Question: If all three mods have all the DLC that would be Skyrim.esm, Update.esm, Dawnguard.esm, Hearthfires.esm, and Dragonborn.esm.  The names patcher manages the FULL record but does it compare the values in the plugin against ALL the DLC.  Meaning that when two mods conflict, the winning plugin has the winning Bash Tag but does not alter the FULL record of the DLC or other masters will that change be ignored thus allowing the Change from PermaCore to take place.

Hypothesis:  The Wrye Bash patcher will function exactly as I described in the post.  The resulting Bash Patch uses the winning plugin with the winning Bash Tag and unfortunately sets the Name back to a vanilla value instead of using the name from PermaCore.

Can I get some clarification on this?

**Comment by Utumno** [comment] 2015-05-21 18:56
Don't know when I will get round to this - probably 307+ - but having a _reproducer_ (as in links to a couple mods needed to reproduce and 1-2-3 instructions on how to build the patch and what to watch for in TESXXX) would help

**Comment by Infernio** [comment] 2019-11-10 21:37
The third screenshot in this issue was fixed by 8364a9ff54bc7339ae4517c902217dfd43756fe3. I can't reproduce the other two:
 - The rename from USSEP is carried forward correctly.
 - The adjusted armor price from 'Gold Worth Something' is carried forward correctly.

Marking as needinfo for now, but can probably be moved to 307 and closed.

**Comment by Infernio** [comment] 2019-12-18 00:01
Closed in 8364a9ff54bc7339ae4517c902217dfd43756fe3 - if anyone can reproduce the other two screenshots, please comment / reopen.

**Closed by Infernio** 2019-12-18 00:01 UTC
Labels: bug, patcher
