### ISSUE TITLE
Failing to build Bashed Patch for Fallout 4

### ISSUE THREAD

**Issue by nexlarker** [wrye-bash/wrye-bash#485] opened 2020-01-25 22:19 UTC
Reported this on discord earlier.

Failing to build bashed patch automatically. If I add any esp (even an empty one) manually into Override Delev/Relev Tags window, bashed patch is built without any problems.

<details>
  <summary>BashBugDump</summary>

```
localize.pyo   89 setup_locale: Set wx locale to 'English' (en_GB)
localize.pyo   97 setup_locale: Set Wrye Bash locale to 'English'
bash.pyo  182 dump_environment: Using Wrye Bash Version 307.202001251613 (Standalone)
bash.pyo  182 dump_environment: OS info: Windows-10-10.0.18362, running on Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
bash.pyo  182 dump_environment: Python version: 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
bash.pyo  182 dump_environment: wxPython version: 3.0.2.0 msw (classic)
bash.pyo  182 dump_environment: pyyaml version: 5.3
bash.pyo  182 dump_environment: python-lz4 version: 2.2.1; bundled LZ4 version: 1.9.2
bash.pyo  182 dump_environment: Input encoding: None; output encoding: None
bash.pyo  182 dump_environment: Filesystem encoding: mbcs
bash.pyo  182 dump_environment: Command line: ['D:\\Steam\\steamapps\\common\\Fallout 4\\Mopy\\Wrye Bash.exe', '--debug', '--Language', 'English', '--no-uac']
bash.pyo  182 dump_environment: Using scandir v1.10.0
bash.pyo  396 _import_bush_and_set_game: Searching for game to manage:
bush.pyo   89 _supportedGames: The following games are supported by this version of Wrye Bash:
bush.pyo   92 _supportedGames:  Enderal, Fallout 3, Fallout 4, Fallout 4 VR, Fallout New Vegas,
bush.pyo   92 _supportedGames:  Oblivion, Skyrim, Skyrim Special Edition, Skyrim VR
bush.pyo   94 _supportedGames: The following installed games were found via Windows Registry:
bush.pyo   96 _supportedGames:  Enderal: D:\Steam\steamapps\common\Enderal
bush.pyo   96 _supportedGames:  Fallout4: D:\Steam\steamapps\common\Fallout 4
bush.pyo  153 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo  159 _detectGames: Set game mode to Fallout4 found in parent directory of Mopy:  D:\Steam\steamapps\common\Fallout 4
bush.pyo  174 __setGame:  Using Fallout4 game: D:\Steam\steamapps\common\Fallout 4
loot_parser.pyo   46 <module>: Using LibYAML-based parser
mods_metadata.pyo   47 __init__: Initialized loot_parser, compatible with libloot v0.15.x
loot_parser.pyo  116 load_lists: Error when parsing LOOT masterlist
Traceback (most recent call last):
  File "bash\bosh\loot_parser.pyo", line 109, in load_lists
  File "bash\bosh\loot_parser.pyo", line 587, in _parse_list
  File "yaml\__init__.pyo", line 114, in load
  File "yaml\constructor.pyo", line 66, in get_single_data
  File "ext\_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext\_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext\_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext\_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext\_yaml.pyx", line 774, in _yaml.CParser._compose_node
  File "ext\_yaml.pyx", line 853, in _yaml.CParser._compose_sequence_node
  File "ext\_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
ScannerError: while scanning an anchor
  in "C:\Users\skyla\AppData\Local\LOOT\Fallout4\masterlist.yaml", line 173, column 5
did not find expected alphabetic or numeric character
  in "C:\Users\skyla\AppData\Local\LOOT\Fallout4\masterlist.yaml", line 173, column 26

__init__.pyo 3257 initBosh: Found main game INI at C:\Users\skyla\Documents\My Games\Fallout4\Fallout4.ini
testing UAC
MERGE/SCAN ERROR: Fallout4.esm
Traceback (most recent call last):
  File "bash\gui\events.pyo", line 167, in _post
  File "bash\balt.pyo", line 1522, in _conversation_wrapper
  File "bash\basher\patcher_dialog.pyo", line 200, in PatchExecute
  File "bash\patcher\patch_files.pyo", line 253, in scanLoadMods
  File "bash\patcher\patchers\special.pyo", line 138, in scanModFile
  File "bash\parsers.pyo", line 3954, in __getattr__
TypeError: 'NoneType' object is not callable
```
  
</details>
<details>
  <summary>Active Mod Files</summary>

```
00  Fallout4.esm
01  DLCRobot.esm
02  DLCworkshop01.esm
03  DLCCoast.esm
04  DLCWorkshop02.esm
05  DLCWorkshop03.esm
06  DLCNukaWorld.esm
07  ccFRSFO4001-HandmadeShotgun.esl
08  ccRZRFO4001-TunnelSnakes.esm
09  ccTOSFO4001-NeoSky.esm
0A  ccTOSFO4002_NeonFlats.esm
0B  ccBGSFO4046-TesCan.esl
0C  CWWorkshopMaster.esm
0D  XDI.esm
0E  Reptilic_DeathClaws_4K.esl
0F  Lucid's Texture Upgrades.esl  [Version 2.0]
10  AORobcoReconScope.esl
11  CROSS_Wasteland_Ronin.esl
12  SavrenXPropsAndJunk.esp
13  SavrenXHdDlcPowerArmor.esp
14  SavrenXCreaturesPackDlcREDONE.esp
15  SavrenXHDSettlementAndSetDressingDLC.esp
16  SavrenXHDSettlementAndSetDressing.esp
17  SavrenXSynthHD.esp
18  SavrenXFoodAndFoodware.esp
19  SavrenX SuperMutant Armor HD.esp
1A  SavrenX HD Vanilla Clothes Optimized.esp  [Version 2.0]
1B  SavrenX HD Vanilla Armor.esp
1C  SavrenX HD DLC Armor and Clothes.esp
1D  SavrenXBetterRobotHDLibertyPrime.esp
1E  FlaconOil_BA2_2K_Part1.esp
1F  FlaconOil_BA2_2K_Part2.esp
20  FlaconOil_BA2_2K_Part3.esp
21  ValiusHDTextures2K.esp
22  Langleys HD Texture Workshop.esp
23  NMC Bundle HIGH.esp
24  Gritty Subway Stations.esp
25  Natural Landscapes.esp
26  Cliffs of the Commonwealth.esp
27  Dilapidated Roads - Charcoal.esp
28  Indubitable Ivy.esp
29  True Caves.esp
2A  CC's HQ Quarry Textures - 2K.esp
2B  detailedferalghouls2K.esp
2C  ODT - Raider Armors Retextured.esp
2D  Better LOD.esp
2E  WET.esp
2F  dD-Enhanced Blood Basic.esp
30  Vault Outfits Redux.esp
31  Faded Glory - Soundtrack Expansion.esp
32  LMBTOverlays.esp
33  AzarPonytailHairstyles.esp
34  MiscHairstyle.esp
35  KSHairdos.esp
36  The Eyes Of Beauty.esp
37  LookingStranger.esp
38  LooksMenu.esp
39  LooksMenu Customization Compendium.esp
3A  KSHairdos_oel.esp
3B  MIA.esp
3C  DCVendorOverhaulAIO.esp
3D  NaiRaeCozyScavver.esp
3E  RegsPrefabs.esp
3F  creativeclutter.esp
40  BasementLiving.esp
41  CompactCrafting.esp
42  Barricades.esp
43  Nuka-Mix_Lantern_Workshop.esp
44  TotW.esp
45  BetterJunkFences.esp
46  SolarPower.esp
47  GrafsSecurityFences.esp
48  KURO.esp
49  Eli_Crafting Shiz 9000.esp
4A  woodysWastelandStuff.esp
4B  Not Your Average Neon.esp
4C  dinoshelf.esp
4D  evan_modular kitchen.esp
4E  OCDispenser.esp  [Version 1.1.3]
4F  OCDecorator.esp  [Version 1.1.3]
50  OCDecoratorDLC.esp  [Version 1.1.3]
51  Better Cooking Stations.esp
52  Better Cooking Stations - Far Harbor + Nuka World patch.esp
53  Better Cooking Stations Immersive Patch.esp
54  RBValentineJawSync.esp
55  mcgFemaleWalk.esp
56  mcgFemaleWalk-Granny-eng.esp
57  wasterArmor.esp
58  Eli_WastelanderClothing.esp
59  GR123 West Tek Tactical Gloves.esp
5A  FOC_NCR_Armors.esp
5B  Classic Combat Armor.esp  [Version 4.3.5]
5C  BostonFPSFixAIO.esp
5D  MilitarizedMinutemen.esp
5E  MilitarisedMinutemen_ScarvesFix.esp
5F  Synth Overhaul.esp
60  Synth Overhaul - White Patch.esp
61  Synth Overhaul - No level requirements Patch.esp
62  CreationClubDelay.esp  [Version 1.3]
63  CROSS_MojaveManhunter.esp
64  MREs.esp
65  F4NVServiceRifleRedux.esp
66  WattzLaserGun.esp
67  G11.esp
68  F4NV-AMR.esp
69  StealthSuitDrk.esp
6A  BullpupBozar.esp
6B  Archimedes-II.esp
6C  CROSS_2077.esp
6D  TheKite_Railroad_Handmaiden.esp
6E  CROSS_Blades.esp
6F  CROSS_BrotherhoodRecon.esp
70  CROSS_CoA.esp
71  CROSS_InstituteExpeditionarySuit.esp
72  CROSS_CourserStrigidae.esp
73  Dank_CrossArmorIntegration.esp
74  F3metalarmor.esp
75  Scavver's Backpacks.esp
76  TFRangerGear.esp
77  F4NV-N99.esp
78  10mmSMG.esp
79  WM Chinese Assault Rifle - Standalone.esp
7A  GreaseGunSMG.esp
7B  ThompsonSMGReplacer.esp
7C  InstitWeapPosit.esp
7D  BF1 Animations - Deliverer v1.0.esp
7E  BF1 Animations - Hunting Rifle v1.3.esp
7F  BF1 Animations - Double Barrel Shotgun v2.3.esp
80  DP_CaravanShotgun.esp
81  HuntingRevolver.esp
82  PD_LowerWeapon.esp  [Version 1.4]
83  PollutedClimate.esp
84  InteriorColorCorrection.esp
85  CompanionsGoHome.esp
86  FirstPersonMessagesMerged.esp
87  2xEnemyDamage.esp
88  2xPlayerDamage.esp
89  No 3D Objects - All DLC + Unoffical Patch.esp
8A  RemoveBlur.esp
8B  CustomCamera.esp
8C  NO NPC GREETINGS.esp
8D  PA-Quick Animations.esp
8E  Project Reality Footsteps FO4.esp
8F  SettlementMenuManager.esp
90  ESPExplorerFO4.esp
91  spacefiddle_Follower-Stealth-Distance-Fixes.esp
92  Concept Art Characters - AIO-DLC-PiperAlt.esp
93  VermillionFrost.esp
94  VermillionFrostLooks1.esp
95  OWR.esp
96  OWR2.esp
97  Insignificant Object Remover.esp
98  Immersive Fallout - Movement (DLC).esp
99  Immersive Fallout - Realistic Jumping.esp
9A  Immersive Fallout - Realistic ADS (DLC).esp
9B  Immersive Fallout - Real Recoil (DLC).esp
9C  RAW INPUT.esp
9D  SilentProtagonist.esp
9E  Pip-Boy Flashlight.esp
9F  StartMeUp.esp
A0  Faster Terminal Displays (20x).esp  [Version 3.0]
```

</details>

[BashBugDump.log](https://github.com/wrye-bash/wrye-bash/files/4112928/BashBugDump.log)

**Comment by Infernio** [comment] 2020-01-26 14:06
I added some more descriptive into the latest nightly, please make another bashbugdump with that: https://www.dropbox.com/sh/iazpayeexiyazeh/AAAbGeVHrlIksp2AFgI4w48Oa?dl=0

**Comment by nexlarker** [comment] 2020-01-26 18:08
With the latest nightly it gives me this error after failing to build bashed patch:

```
Fallout4.esm: Failed to retrieve top class for LVLI; load factory is <LoadFactory: load 0 types (), discard others>
```

<details>
  <summary>BashBugDump</summary>

```
localize.pyo   89 setup_locale: Set wx locale to 'English' (en_GB)
localize.pyo   97 setup_locale: Set Wrye Bash locale to 'English'
bash.pyo  182 dump_environment: Using Wrye Bash Version 307.202001261357 (Standalone)
bash.pyo  182 dump_environment: OS info: Windows-10-10.0.18362, running on Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
bash.pyo  182 dump_environment: Python version: 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
bash.pyo  182 dump_environment: wxPython version: 3.0.2.0 msw (classic)
bash.pyo  182 dump_environment: pyyaml version: 5.3
bash.pyo  182 dump_environment: python-lz4 version: 2.2.1; bundled LZ4 version: 1.9.2
bash.pyo  182 dump_environment: Input encoding: None; output encoding: None
bash.pyo  182 dump_environment: Filesystem encoding: mbcs
bash.pyo  182 dump_environment: Command line: ['D:\\Steam\\steamapps\\common\\Fallout 4\\Mopy\\Wrye Bash.exe', '--debug', '--Language', 'English', '--no-uac']
bash.pyo  182 dump_environment: Using scandir v1.10.0
bash.pyo  397 _import_bush_and_set_game: Searching for game to manage:
bush.pyo   89 _supportedGames: The following games are supported by this version of Wrye Bash:
bush.pyo   92 _supportedGames:  Enderal, Fallout 3, Fallout 4, Fallout 4 VR, Fallout New Vegas,
bush.pyo   92 _supportedGames:  Morrowind, Oblivion, Skyrim, Skyrim Special Edition, Skyrim VR
bush.pyo   94 _supportedGames: The following installed games were found via Windows Registry:
bush.pyo   96 _supportedGames:  Enderal: D:\Steam\steamapps\common\Enderal
bush.pyo   96 _supportedGames:  Fallout4: D:\Steam\steamapps\common\Fallout 4
bush.pyo  153 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.pyo  159 _detectGames: Set game mode to Fallout4 found in parent directory of Mopy:  D:\Steam\steamapps\common\Fallout 4
bush.pyo  174 __setGame:  Using Fallout4 game: D:\Steam\steamapps\common\Fallout 4
loot_parser.pyo   46 <module>: Using LibYAML-based parser
mods_metadata.pyo   47 __init__: Initialized loot_parser, compatible with libloot v0.15.x
loot_parser.pyo  116 load_lists: Error when parsing LOOT masterlist
Traceback (most recent call last):
  File "bash\bosh\loot_parser.pyo", line 109, in load_lists
  File "bash\bosh\loot_parser.pyo", line 587, in _parse_list
  File "yaml\__init__.pyo", line 114, in load
  File "yaml\constructor.pyo", line 66, in get_single_data
  File "ext\_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext\_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext\_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext\_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext\_yaml.pyx", line 774, in _yaml.CParser._compose_node
  File "ext\_yaml.pyx", line 853, in _yaml.CParser._compose_sequence_node
  File "ext\_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
ScannerError: while scanning an anchor
  in "C:\Users\skyla\AppData\Local\LOOT\Fallout4\masterlist.yaml", line 173, column 5
did not find expected alphabetic or numeric character
  in "C:\Users\skyla\AppData\Local\LOOT\Fallout4\masterlist.yaml", line 173, column 26

__init__.pyo 3257 initBosh: Found main game INI at C:\Users\skyla\Documents\My Games\Fallout4\Fallout4.ini
testing UAC
MERGE/SCAN ERROR: Fallout4.esm
```

</details>

[BashBugDump.log](https://github.com/wrye-bash/wrye-bash/files/4113952/BashBugDump.log)

**Comment by Infernio** [comment] 2020-01-26 19:20
Thanks! I managed to replicate it, will push a fix in a bit.

**Comment by Infernio** [comment] 2020-01-26 19:31
Happens on dev as well.

**Comment by Infernio** [comment] 2020-01-26 19:32
Bisection result:
```
$ git bisect good
bee2ae9c3fa0d05c41e312392c2ff13367bfe972 is the first bad commit
commit bee2ae9c3fa0d05c41e312392c2ff13367bfe972
Author: MrD <the.ubik@gmail.com>
Date:   Mon Oct 28 20:39:28 2019 +0200

    WIP - getRead/WriteClasses pruning:

    Kept isActive check although this must be handled in patchFile

    Mopy/bash/game/oblivion/patcher/importers.py:

    Initially I did this here too

    @@ -39,2 +39,3 @@ class RoadImporter(ImportPatcher, _ARoadImporter):
         logMsg = u'\n=== ' + _(u'Worlds Patched')
    +    _read_write_records = ('CELL', 'WRLD', 'ROAD',)
    ...

    but keep in mind there is a silly override in ImportPatcher

        def getReadClasses(self):
            """Returns load factory classes needed for reading."""
            return tuple(
                x.classType for x in self.srcClasses) if self.isActive else ()

    This needs some thought - we could bin this along with classestemp
    attribute, seems to just complicate stuff

    We also must make sure we import correctly

    @@ -86,3 +86,3 @@ def _overhaul_compat(self, mods, _skip_id):
     class ListsMerger(_AListsMerger, ListPatcher):
    -    _read_write_records = bush.game.listTypes
    +    _read_write_records = bush.game.listTypes # is it imported correctly ?

    We should add an assert_game_set() on all files that use bush.game to
    avoid nasty surprises (or not, investigating on nightly)

    Finally, all this needs better names - _read_record_signatures and some
    properties to replace getRead/WriteClasses (or rather override class
    variables)

    Under #312

 Mopy/bash/game/oblivion/patcher/special.py        | 33 +++----------------
 Mopy/bash/patcher/base.py                         |  9 ++---
 Mopy/bash/patcher/patchers/multitweak_clothes.py  | 10 +-----
 Mopy/bash/patcher/patchers/multitweak_settings.py | 12 ++-----
 Mopy/bash/patcher/patchers/special.py             | 40 +++++++----------------
 5 files changed, 23 insertions(+), 81 deletions(-)
```

**Comment by Infernio** [comment] 2020-01-26 19:42
Alright, spotted the problem. ListsMerger had the following getReadClasses/getWriteClasses:
https://github.com/wrye-bash/wrye-bash/blob/e4dc76995703f16ee97fb07d495b6db635a2c6a8/Mopy/bash/patcher/patchers/special.py#L110-L116
But in that commit, it got refactored to use the new `_read_write_records` variable. That variable is only returned by the base class if the patcher is active:
https://github.com/wrye-bash/wrye-bash/blob/bee2ae9c3fa0d05c41e312392c2ff13367bfe972/Mopy/bash/patcher/base.py#L79-L85

The patcher does not actually check if self.isActive (since the leveled list patcher can do meaningful work even without any source mods). So it runs, but no record types have actually been loaded by PBash. That's why manually adding/tagging a single mod for the patcher works - it forces the BP process to load the appropriate record types.

**Comment by Infernio** [comment] 2020-01-26 19:47
@Utumno not sure how we want to fix this - this would work:
```diff
diff --git a/Mopy/bash/patcher/patchers/special.py b/Mopy/bash/patcher/patchers/special.py
index 5e4a32212..60d8db847 100644
--- a/Mopy/bash/patcher/patchers/special.py
+++ b/Mopy/bash/patcher/patchers/special.py
@@ -97,6 +97,7 @@ class ListsMerger(_AListsMerger, ListPatcher):
     #--Patch Phase ------------------------------------------------------------
     def initPatchFile(self, patchFile):
         super(ListsMerger, self).initPatchFile(patchFile)
+        self.isActive = True # can always do work, even with no sources
         self.srcs_ordered = self.srcs
         self.srcs = set(self.srcs) & patchFile.loadSet
         self.type_list = dict([(rec, {}) for rec in self._read_write_records])
```
... but reassigning isActive feels ugly. Another option would be to add the overrides back in:
```diff
diff --git a/Mopy/bash/patcher/patchers/special.py b/Mopy/bash/patcher/patchers/special.py
index 5e4a32212..eccbde5df 100644
--- a/Mopy/bash/patcher/patchers/special.py
+++ b/Mopy/bash/patcher/patchers/special.py
@@ -107,6 +107,12 @@ def initPatchFile(self, patchFile):
         _skip_id = lambda x: (GPath(u'Oblivion.esm'), x)
         self._overhaul_compat(self.srcs, _skip_id)

+    def getReadClasses(self):
+        return self.__class__._read_write_records
+
+    def getWriteClasses(self):
+        return self.__class__._read_write_records
+
     def scanModFile(self, modFile, progress):
         """Add lists from modFile."""
         #--Level Masters (complete initialization)
```
... but honestly, I think that's an even uglier solution.

**Comment by Utumno** [comment] 2020-01-26 19:47
> (since the leveled list patcher can do meaningful work even without any source mods)

confusing this bit never quite got it - so we should pin isActive to true? Bear in mind all this is refactored on 312 branch, good opportunity to clarify this isActive part

**Comment by Utumno** [comment] 2020-01-26 19:49
haha ninj'ed - I would go for solution 1 - already used in race patcher (?)

**Comment by Infernio** [comment] 2020-01-26 19:52
Well, the leveled list patcher merges lists. The tags just give it extra info about  how to do so. Let's say I have a leveled list in `Skyrim.esm` with 3 items. The I have a mod `A.esp`, which adds a single item to that list and mod `B.esp`, which adds a *different* item to the list. The leveled list patcher can now create a result that takes the two additions and combines them, creating a final list with all 5 items in it. No tags or source mods were necessary for this.

As for the tags, they allow you to express that a mod does some special actions to leveled lists:
`Delev` means that deletions of items in lists by the tagged mod should be respected. Normally, the leveled list patcher ignores deletions completely.
`Relev` means that the tagged mod may change the *level* of items in lists. Normally, the leveled list patcher ignores releveling completely.

**Comment by Infernio** [comment] 2020-01-26 19:57
Here's a screenshot from xEdit illustrating what the situation described above would look like. First entry is `Skyrim.esm`, second is `A.esp`, third is `B.esp`, last is `Bashed Patch, 0.esp`:

![MergingLVLI](https://user-images.githubusercontent.com/2845240/73140899-496a9480-407e-11ea-9cd3-d3cca7a6c859.png)

**Comment by Utumno** [comment] 2020-01-26 19:57
Thanks! So effectively the  sources are actually the whole active/merged mods

**Comment by Infernio** [comment] 2020-01-26 20:01
I'll go for the `self.isActive = True` for now, but we should really rework the whole 'always active' thing from the race patcher (and CBash version of the contents checker) at some point. It's incredibly unintuitive that you can *uncheck* it in the GUI, but it'll still run.
There's also #43 - hiding those patchers entirely might be an option too, though I bet it would just confuse users...

**Comment by Infernio** [comment] 2020-01-26 20:18
Confirmed fixed on Discord.

**Closed** 2020-01-26 20:18 UTC
Labels: regression
