### ISSUE TITLE
[SSE] BAIN Wizard installer requirements reads SSE exe version from the wrong field.

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#436] opened 2019-03-15 02:50 UTC
I was testing a wizard installer today and realized that BAIN is not looking at the correct field on the SkyrimSE.exe file to pull the current version. Yes yes, I know, Bethesda is putting it in the wrong space and all that. Since we're not going to get THEM to fix that, it should be fixed on this end. Here's what the installer told me:

https://i.imgur.com/kVteN0j.jpg

This is what you see if you right click the exe and check the details tab:

https://i.imgur.com/YIfwb8D.jpg

Hopefully isn't too big a hassle to fix.

**Comment by Infernio** [comment] 2019-03-15 13:30
I'm probably going to need to installer or at least the wizard script to reproduce and fix this.

**Comment by Infernio** [comment] 2019-03-15 14:05
Nevermind, I know what the issue is. Wrye Bash checks the file version, SSE uses the product version. This doesn't seem to be trivial to fix though.
From `env.py`:
```python
def get_file_version(filename):
    """Return the version of a dll/exe, using the native win32 functions
    if available and otherwise a pure python implementation that works
    on Linux. The return value is a 4-int tuple, for example (1.9.32.0)."""
    if win32api is None:
        return _linux_get_file_version_info(filename)
    else:
        info = win32api.GetFileVersionInfo(filename, u'\\')
        ms = info['FileVersionMS']
        ls = info['FileVersionLS']
        return win32api.HIWORD(ms), win32api.LOWORD(ms), \
               win32api.HIWORD(ls), win32api.LOWORD(ls)
```
Those `FileVersionMS` and `FileVersionLS` strings need to be `ProductVersionMS` and `ProductVersionLS` in SSE, according to the [DkmModuleVersion documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger.dkmmoduleversion?view=visualstudiosdk-2017).

But I can't import have env import bush to retrieve info about the current game, since bush already imports env...
@Utumno Any ideas?

**Comment by Utumno** [comment] 2019-03-15 14:38
Yep was afraid so - get_product_version and conditionally use that in belt? Ugly but edge case

**Comment by Infernio** [comment] 2019-03-15 14:51
I think I'm going to pass an optional parameter to get_file_version that defaults to `'FileVersion'`, format those strings with that parameter, and then set the parameter in a game-specific way in belt.

**Comment by Arthmoor** [comment] 2019-03-15 16:59
If you still need a test subject for this, you can use this mod: https://www.afkmods.com/index.php?/files/file/1891-bee-hives/

It's got a very simple wizard but it'll display the version problem. It's the one I was testing when it cropped up.

**Comment by Infernio** [comment] 2019-03-16 21:40
Should be fixed in https://github.com/wrye-bash/wrye-bash/commit/7724813cd2d3b82f66167a9742fca4ddc0647618.

**Closed** 2019-03-24 18:05 UTC
Labels: bain, bug, skyrim-se
