### ISSUE TITLE
More visible BAIN comands

### ISSUE THREAD

**Issue by lojack5** [wrye-bash/wrye-bash#48] opened 2014-02-25 05:01 UTC
[sourceforge](https://sourceforge.net/p/oblivionworks/enhancements/208/)

Make it easier and more visible to do some of the most common actions: Install/Uninstall/Wizard, Anneal. At the very least, move these items to the top of the context menu, probably bolding the Install/Uninstall/Wizard. We could go further and make a column of buttons down the left hand side (it's the place where it'd require the least amount of mouse movement to get at), for these common actions.

Also, having both an Install and an Uninstall command is redundant. Install should change to Uninstall, based on the package's status. Install Last appears to have no real use other than a shortcut to dragging a package to the ==Last== marking and installing. We can probably cut that one out. Install Missing still has its uses though.

**Comment by Utumno** [comment] 2019-01-05 10:07
practically duplicate of #421

**Closed by Utumno** 2019-01-05 10:07 UTC
Labels: R-duplicate, M-svn, A-bain
